### ISSUE TITLE
Occur evil integration not working

### ISSUE THREAD

**Issue by Grimscythe1983** [emacs-evil/evil-collection#100]
I manually add modes that I want to enable, like such:
```
(setq evil-collection-mode-list '(arc-mode
                                    avy
                                    bookmark
                                    calendar
                                    dired
                                    eshell
                                    ibuffer
                                    occur
                                    popup
                                    profiler
                                    quickrun
                                    realgud))
```

All work apart from `occur`. I seem to have to do this to start it:
```
(require 'evil-collection-occur)
(evil-collection-occur-setup)
```

Side note: `occur` seems to be lacking a key binding for `q`

**Comment by jojojames** [comment]
Yup, check the contents of the list. Occur is a special case since there isn't an 'occur' feature.

```
    ;; occur is in replace.el which was built-in before Emacs 26.
    (occur ,(if (<= emacs-major-version 25) "replace" 'replace))
```

> Side note: occur seems to be lacking a key binding for q

PR welcome! :)

**Comment by Grimscythe1983** [comment]
So should I change `occur` to `replace` inside of the list? or do just leave it the way I have it?

**Comment by jojojames** [comment]
You can add the line I pasted to your list.

```
    (occur ,(if (<= emacs-major-version 25) "replace" 'replace))
```

If still confused, you can just take a look at the original definition in evil-collection.

**Comment by Grimscythe1983** [comment]
Ahh I see. Sorry I misunderstood you. Thank you so much!
