### ISSUE TITLE
anaconda-mode: gf bound to non-interactive command

### ISSUE THREAD

**Issue by hlissner** [emacs-evil/evil-collection#105]
In `anaconda-mode-map`, `gf` is bound to `anaconda-mode-find-file` [which isn't an interactive command](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L717-L719). This causes a `command-execute: Wrong type argument: commandp, anaconda-mode-find-file` error.

**Comment by jojojames** [comment]
You're right, I wonder what we should do here. Looks like that function is an inner function used by something else.

I guess we could remove the gf binding for that unless that function really is useable as an interactive function.

@proofit404

**Comment by proofit404** [comment]
Hi, yes, this is an internal function used in definitions and assignments search. You can safely remove the binding.
Regards, Artem.

**Comment by jojojames** [comment]
Thanks, sounds good. Removed.
