### ISSUE TITLE
Remap :wq and :q for some modes

### ISSUE THREAD

**Issue by noctuid** [emacs-evil/evil-collection#107]
This this is potentially useful for a lot of modes  (e.g. org capture, org src, magit with-editor/commit, etc.). For example, I have something like this in my config:
```
(evil-define-key nil org-capture-mode-map
  [remap evil-save-and-close] #'org-capture-finalize
  [remap evil-save-modified-and-close] #'org-capture-finalize
  [remap evil-quit] #'org-capture-kill)
```

I usually use dedicated confirm ("RET") and cancel keys personally, but some people might find this useful.

**Comment by Ambrevar** [comment]
I like this!

**Comment by Somelauw** [comment]
Those for org-mode at least are already present in evil-org. Please create
an issue on https://github.com/Somelauw/evil-org-mode/issues if any of them
is missing.

**Comment by jojojames** [comment]
This looks good to do. I think the next steps is just to add a section to the rationale about it and compile a list of modes that might want :w/:wq/:q. I'll add those bindings as I come across them.

**Comment by miguelmartin75** [comment]
There's a small issue with this. If you do :w and then :q - the note will be destroyed, whereas the intent here is to save. I'll just have to remember to wq before going further.
