### ISSUE TITLE
binding of "q" in magit-blame-mode changed by evil-collection

### ISSUE THREAD

**Issue by ambihelical** [emacs-evil/evil-collection#108]
In magit-blame-mode (via magit-blame), "q" is mapped to quit-window instead of magit-blame-quit, which should be the case.  This causes the window to go away instead of just reverting the blame annotations. 

If I disable evil-collection, the problem goes away.  This was puzzling because there isn't much magit stuff in evil-collection, but I traced it to evil-collection-view, as magit-blame-mode hooks view-mode-hook to put its keymap before view-mode.  If I comment out the q key mapping in evil-collection-view.el, the problem goes away.   I doubt if this is the right fix, but it at least provides some information.  I have no idea how to fix it correctly. 

Interestingly I found that if I force evil-magit to load before evil-collection as in the following, the first blame on a file works correctly, but subsequent ones don't.  I don't have any idea why this is, but it might be useful information.  

```
(use-package evil-collection
  :after ( evil evil-magit )
  :init
  :defer 1
  :config
  (evil-collection-init))

```

**Comment by Ambrevar** [comment]
Thanks for reporting this.  Indeed, magit-blame uses view-mode (I was not aware of this).

Not sure about the best way to fix this.  Maybe remove `q` and set `ZZ` and `ZQ` instead.

**Comment by ambihelical** [comment]
I think more accurately magit-blame-mode handles the case when view mode is also active by making sure its bindings come before view mode. I have view-read-only set, this causes any read-only files to use view mode.  If I use the default for that, view is not enabled for magit-blame-mode, and things also work correctly.

**Comment by jojojames** [comment]
FWIW I can't repro this with my own configuration.

Can you provide a small emacs -Q recipe for this?

**Comment by ambihelical** [comment]
Not quite a emacs -Q recipe, but here is a small init.el which has the problem.  Open any file with git history, run magit-blame, and then "q":

;;; -*- lexical-binding: t -*-

(require 'package)

(setq package-archives '(("melpa" . "http://melpa.milkbox.net/packages/")
                          ("org"   . "http://orgmode.org/elpa/")
                          ("gnu"   . "http://elpa.gnu.org/packages/")))
(package-initialize)
(unless package-archive-contents
   (package-refresh-contents))
(unless (package-installed-p 'use-package )
   (package-install 'use-package))
(eval-when-compile
   (require 'use-package))

;; using this causes it: 
(setq view-read-only t)

(use-package evil
  :ensure t
  :init
  (add-hook 'prog-mode-hook #'evil-mode)
  (add-hook 'text-mode-hook #'evil-mode)
  (setq evil-want-integration nil)           ; use evil-collection instead
  :config
  (evil-mode 1))

(use-package evil-collection
  :ensure t
  :after ( evil )
  :config
  (evil-collection-init))


(use-package magit
  :ensure t
  :after evil
  :config)

**Comment by Ambrevar** [comment]
I can reproduce this.

**Comment by jojojames** [comment]
By binding view-mode-map, it looks like we're putting view-mode-map's keys into emulation-mode-map-alists which has a higher precedence than minor-mode-map-alist.
Since evil-magit doesn't bind q, view-mode-map's q binding takes precedence over the key set by define-key in magit-blame.el.

I think one approach is to bind q in evil-magit-minor-mode-map-bindings in evil-magit to magit-blame-quit. @justbur

Another is to do something at the evil-collection layer. Probably the same as just binding q to the right function.

I'd prefer the magit + evil related stuff to go in the evil-magit repo but we can do something here too if that's not a good idea.

**Comment by jojojames** [comment]
Added a workaround for now. Lemme know if it doesn't work for you @ambihelical.

**Comment by ambihelical** [comment]
It seems to work.  Thanks!

**Comment by ambihelical** [comment]
And its back.  I just updated after a long gap, and this behaviour has returned.

**Comment by ambihelical** [comment]
It looks like magit renamed its view-based blame mode to magit-blame-read-only-mode.   I'd create a PR but I'm not sure about the "temporary" bit on the previous commit and also the change needed is trivial.  Is there a more permanant fix in the works?

**Comment by jojojames** [comment]
@ambihelical Woops, sorry this slipped by. Are you still seeing any issues?

**Comment by ambihelical** [comment]
I have turned off view-read-only=t in my config so I haven't been noticing.  After updating evil-collection and adding (setq view-read-only t) in my config, the binding is still wrong.

**Comment by jojojames** [comment]
OK, at some point I'll look at this. It's low priority to me though so don't expect much. :)

**Comment by jojojames** [comment]
Added something for this with some quick testing.

Lemme know if it doesn't work for ya.
