### ISSUE TITLE
Change diff-mode to use a minor mode

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#114]
This is to avoid using motion state.

See https://github.com/emacs-evil/evil-collection/issues/21

I don't use diff-mode so not a good person to fix this.

**Comment by ambihelical** [comment]
Not really sure how a minor mode will work, but I may just be confused. Sometimes it is useful to edit the buffer in diff-mode by toggling read-only-mode (C-x C-q).  One use case is marking up a diff with comments.  In diff-mode, when read-only, evil refuses to go into insert mode, so I'm not sure why normal-mode isn't sufficient here.

**Comment by jojojames** [comment]
I think @Ambrevar or @noctuid would know more than me about how diff-mode works.

**Comment by Ambrevar** [comment]
@ambihelical: I'm not sure I understand your use case: You want to insert comment into the diff file, you want to modify the diff file that is.
If so, I wonder how safe it is, it could get `diff` really confused.  But fair enough :)

I did not understand your issue in read-only mode: I can edit the buffer when read-only is toggled off.  Did you expect to be able to modify the buffer when read-only is on?

**Comment by ambihelical** [comment]
Editting a diff (in my case a .patch) file can be useful for several reasons.  You may want to modify the header part.  Or if you are reviewing a patch, insert comments into the file.  In this case you don't expect diff or patch to use the result, the extra text is for a human being.   Sometimes, but rarely, it is necessary to make modifications directly to the diff to fix a problem. 

I don't have an issue with read-only-mode.  Diff-mode starts out in read-only-mode, and this works well with evil normal mode.  Any insert command just emits a message about the file being read-only.  I do have an issue with a minor mode that doesn't let me use all the evil normal mode insert bindings to edit the diff once I've turned off read-only-mode.  

Like I said I may be confused what this minor mode would do, but just providing some motion-mode-like bindings is what it sounds like it would do.  This would be a regression in that case.

**Comment by Ambrevar** [comment]
OK, now I understand what you meant.  The minor mode in question is not to prevent editing, in fact it would only be enabled in read-only mode.
