### ISSUE TITLE
Discussion of isearch in info-mode

### ISSUE THREAD

**Issue by jgkamat** [emacs-evil/evil-collection#122]
In info mode, `n/p` is bound to the isearch next/previous commands [currently](https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-info.el#L74). 

However, `/` is not bound to evil-ex-search, and this means that normal evil searches do not have a working next/previous.

I wanted to bring up a larger point though, I personally don't like isearch and prefer to use the default evil ex search behavior everywhere (I have it customized and I want to keep those customizations without duplicated them for isearch). 

Would it sound OK to add a `evil-collection-want-ex-search` to turn off isearch bindings? Does anyone else have thoughts on better solutions?

Is there a reason for bidning to isearch at all, when evil default search works fine? In this case, it might search across pages, but I personally find that more confusing. :P

**Comment by Ambrevar** [comment]
> In this case, it might search across pages, but I personally find that more confusing. :P

Precisely this reason.  How to you search an entire manual otherwise?

Which features do you miss from evil-ex-search?

**Comment by jgkamat** [comment]
I have a lot of issues with isearch:

1. isearch next/previous prints `Wrapped I-Search` in the minibuffer, rather than nothing for evil.
2. isearch in info pages dosen't wrap on the individual section, rather, it wraps on the entire manual. Pressing `n` and going to a new page is really jarring to me.
3. I'm not sure if there's an equivalent command, but I couldn't find a replacement for `evil-ex-nohighlight`
4. Isearch highlighting and evil highlighting can be active at the same time, which is confusing
5. The cursor is not in the minibuffer when using isearch directly, which is distracting, and takes my attention away from where I'm typing.
6. There seems to be a delay to seeing other search results when using isearch directly (probably configurable though)
7. A few things like `gn` won't work with isearch

I personally have never wanted to search the entire manual, to me `/` should always search the current visible buffer, and other commands could be used to do other things, if only for the sake of consistency. To me at least, this feels the same as evil n/p search searching the entire project, rather than the current file. For something like a project or info search, I would much rather prefer a helm/ivy style interface, although I'm not sure if one exists for the manual.

While most of these issues could probably be fixed with customization, I'd rather just have evil search everywhere so I don't need to customize more than one thing.

**Comment by jojojames** [comment]
Those sound like reasonable points. What do you think @Ambrevar?

**Comment by Ambrevar** [comment]
While it's obviously no issue to add a customization option, I disagree with most of your points.

1. Isearch provides you with more information then.  I personally think it's a good thing, but I understand some might find it too verbose.

2. Yes, it's the intended behaviour.  Without out, it's impossible to search the manual for a specific term (index aside), which in my opinion is a very important feature.

3. Once you confirm an isearch with RET, the highlighting should be turned off.  It's turned off again when you keep searching (`n` with Evil, `C-s` with Emacs).

4. That's because you use the evil-ex-search module.  I did not understand your issue at first.  So let's fix it this way: if evil-ex-search is on, then leave `n` / `N` be untouched, otherwise bind them to isearch commands as I have.

5. Matter of taste I guess.

6. I don't experience any delay.  Can you provide a recipe?

7. What does `gn` do?

Would point 4. be an acceptable solution?

**Comment by jgkamat** [comment]
> So let's fix it this way: if evil-ex-search is on, then leave n / N be untouched, otherwise bind them to isearch commands as I have.

This sounds like a good idea, I'm assuming you mean `(eql evil-search-module 'evil-search)` right? That seems like the best solution to me :) I'd be willing to submit a PR if that sounds good.

> I don't experience any delay. Can you provide a recipe?

Here's what I can reproduce in a clean `make emacs` from evil
![peek 2018-05-09 09-24](https://user-images.githubusercontent.com/4349709/39826847-989268de-53a5-11e8-8729-7964119d9088.gif)

`gn` selects the next occurence of a selection. It's incredibly useful for batch operations where you don't feel like making a regexp:

![peek 2018-05-09 09-27](https://user-images.githubusercontent.com/4349709/39826933-e69b6d5a-53a5-11e8-8d96-f72bac64467b.gif)

**Comment by Ambrevar** [comment]
Feel free to submit a PR! :)

`gn`: got it, it is very similar in purpose to iedit, isn't it?

Delay: Hmmm, it's not easy to see the delay from the gif... Can you provide a textual recipe instead?

**Comment by jgkamat** [comment]
I've just submitted the PR.

I haven't tried iedit, but they seem similar. I personally use `:%s/` for things that iedit seems to offer, I use gn when I need to verify every occurrence.

The delay is on the other matching texts, not the first one. I'm able to type the full search before the other occurrences are highlighted.
