### ISSUE TITLE
Remove the "beta" warning from the README

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil-collection#125]
I think evil-collection is mature enough, we could remove that warning.  What do you think?

**Comment by jojojames** [comment]
> Warning: This project is still in an early development phase, expect some default bindings to change in the future.

I'd probably want this part in still:

> expect some default bindings to change in the future.

Otherwise, I think you're right.

**Comment by Ambrevar** [comment]
Fixed.
