### ISSUE TITLE
Add number support to SLIME backtrace buffer

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil-collection#126]
SLIME has a dedicated buffer for backtraces (with `sbcl` at least) in which the next action can be selected either with `RET` or the corresponding number.

With Evil, the numbers are not mapped.  Is it an oversight?

**Comment by jojojames** [comment]
Probably oversight.

**Comment by Ambrevar** [comment]
Fixed: 400b9f0c4f3cb05b2ea96c114ce5eee6f9b337f1.
