### ISSUE TITLE
Unable to use calc's functions in the first time

### ISSUE THREAD

**Issue by mssdvd** [emacs-evil/evil-collection#127]
Hi, when I press a key binded to a calc function I get this message:
`command-execute: Wrong type argument: commandp, <name of the function>`
The only way to end this behavior is to write some number or switch to Emacs mode.

**Comment by Ambrevar** [comment]
Which binding, which function in particular?  I can't seem to reproduce.

**Comment by mssdvd** [comment]
![peek 2018-05-16 22-41](https://user-images.githubusercontent.com/18464329/40142924-50bd450a-595a-11e8-8ac9-1cfc3f44081c.gif)

**Comment by Ambrevar** [comment]
If you look at the `evil-collection-calc.el`, you'll see that it takes special provision to load calc's extension in `evil-collection-calc-ext-setup`.
It works for me so I'm not quite sure what's going wrong for you.  Have you tried on a vanilla config?

Also note that `calc` support is in general very unfinished. See #84.

**Comment by mssdvd** [comment]
25.3.
The latest from Melpa

**Comment by mssdvd** [comment]
One more thing that I noticed is that I can't set the emacs mode as default for calc's buffers.

**Comment by mssdvd** [comment]
Even if calc-mode is in the emacs list  it starts in normal mode.

**Comment by Ambrevar** [comment]
This is normal if you use Evil Collection, it calls
```
(evil-set-initial-state 'calc-mode 'normal)
```
explicitly.  The whole point of this module is to define Evil bindings and that only makes sense if the module is in some Evil state.

Are you expecting a different state?  Do you have some Calc-related config?

**Comment by mssdvd** [comment]
I didn't try a vanilla confing but I haven't any specific configuration
related to calc or evil-collection.

Il mer 16 mag 2018, 23:47 Pierre Neidhardt <notifications@github.com> ha
scritto:

**Comment by mssdvd** [comment]
Thank you for the workaround. However, calc doesn't work well with evil-collection even in Emacs vanilla. I executed those commands:
```emacs
(setq evil-want-integration nil)
(add-to-list 'load-path "/home/davide/.emacs.d/elpa/evil-20180506.1341")
(require 'evil)
(evil-mode 1)
(add-to-list 'load-path "/home/davide/.emacs.d/elpa/evil-collection-20180514.1311")
(require 'evil-collection nil t)
(evil-collection-init)
```

**Comment by jojojames** [comment]
Where are you removing calc in your snippet?

**Comment by mssdvd** [comment]
I meant that calc has the same problems also with Emacs vanilla

**Comment by jojojames** [comment]
Could you explain what each scenario does for you? It seems like you're having a problem with Emacs + Calc and not Emacs + Calc + Evil-(collection).

Emacs + Calc

Emacs + Calc + Evil

Emacs + Calc + Evil + Evil-Collection

Emacs + Calc + Evil + Evil-Collection - (evil-collection-calc)

**Comment by Ambrevar** [comment]
OK, I can reproduce.  I'm not sure why this happens but anyways, is there a use case where you would not enter a number first?
I never realized the issue before because it never occurred to me to call `calc-*` functions on an empty stack.

**Comment by mssdvd** [comment]
I often use calc to calculate averages and variances and to do so I create a vector with `calc-begin-vector` (`[`) and this does not work on the first attempt.

**Comment by Ambrevar** [comment]
Good point.  I'll try to fix it.
Any `calc` expert out there?

**Comment by Ambrevar** [comment]
I think I've fixed it.  Feel free to re-open this issue if there is any more trouble.

**Comment by mssdvd** [comment]
It works! Thank you very much!
