### ISSUE TITLE
a suggestion on prog-mode keybind

### ISSUE THREAD

**Issue by VonFry** [emacs-evil/evil-collection#130]
[smart-jump](https://github.com/jojojames/smart-jump/) provide a framework to manage jump to defination.

[repl-toggle](https://github.com/tomterl/repl-toggle/) provide a framework for repl.

These are probably better than changing the same keybinding for each language.

By the way, the `g r` is used in `evil-mc` by default.

**Comment by jojojames** [comment]
> smart-jump provide a framework to manage jump to defination.

Yup! I'd prefer to leave it separate though as it's fairly oppinionated.

> repl-toggle provide a framework for repl.

This looks interesting. I'll probably check this out at some point but might fall in the same oppinionated category.

> By the way, the g r is used in evil-mc by default.

Yup, that makes things tricky since gr is used for refresh generally.

**Comment by jojojames** [comment]
Closing for now but feel free to re-open if you had any more thoughts on this! Thanks for the feedback!
