### ISSUE TITLE
How do I activate this collection?

### ISSUE THREAD

**Issue by mrbig033** [emacs-evil/evil-collection#132]
I'm sorry for the silly question, but I installed evil-collection using MELPA and now I don't know if it's activated or not. Do I have to configure anything, or does it work out of the box?

**Comment by Ambrevar** [comment]
Simply call `(evil-collection-init)`.

**Comment by jojojames** [comment]
@Ambrevar answered it. You can check out the readme for more details.

Thanks!

**Comment by mrbig033** [comment]
I added the example from the readme and it works now. Can you tell what it does?

**Comment by Ambrevar** [comment]
Press `C-h f evil-collection-init` to see the documentation of the function.
Basically what it does is running through the modes listed in `evil-collection-mode-list` and setting "Evil" bindings for them.

Let me know if anything else isn't clear.

**Comment by mrbig033** [comment]
Thank you!
