### ISSUE TITLE
Incompatibility with helm

### ISSUE THREAD

**Issue by mrbig033** [emacs-evil/evil-collection#133]
* MX LINUX 17
* GNU Emacs 26.1.50
* [.emacs](https://gitlab.com/mrbig/dotfiles/blob/master/emacs/.emacs)
* [.emacs.d](https://gitlab.com/mrbig/dotfiles/tree/master/emacs/.emacs.d)
* evil 20180529.1810
* evil-collection 20180529.1810
* helm 20180527.2241
* [complete environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

## Issue

When evil-collection is activated, helm doesn't work.

* `C-x c searchterm TAB`
  * `Invalid function: with-helm-buffer`

When evil-collection is disabled, helm works.

**Comment by Ambrevar** [comment]
We had this issue with the `with-helm-buffer` macro in the past.  Looking back at the log, I don't understand why we left one instance of it instead of removing all of them. 

I'm also surprised nobody complained about it earlier.  Maybe it only occurs on some setups?

**Comment by mrbig033** [comment]
I don't know. Unfortunately, I'm not able to provide more information because I just switched to ivy. Thanks anyway.

**Comment by Ambrevar** [comment]
I think this is the same as #101 and should be fixed with bca66d36fd7840284e553970ba9913e59521ef14.
