### ISSUE TITLE
Bindings in Helm not working

### ISSUE THREAD

**Issue by Artraxon** [emacs-evil/evil-collection#134]
Hello everyone,
for some reason, the bindings for helm ("C-j", "C-k") are not working. Other Bindings from evil-collection are working.
I am using the latest evil-collection package from MELPA, emacs 25.3.1.
The relevant parts of my init.el are 

```emacs lisp
 (use-package helm
  :bind (("M-x" . 'helm-M-x)
	 ("C-x C-f" . 'helm-find-files)
	 ("C-x r b" . 'helm-filtered-bookmarks)
	 ("C-x C-b" . 'helm-buffers-list))
  :after evil-collection
  :straight t
  :config
  (helm-mode 1))

(use-package evil
  :init
  (setq evil-want-integration nil)
  :straight t
  :config (evil-mode 1))


;; Collection of evil keybindings
(use-package evil-collection
  :straight t
  :after evil
  :config (evil-collection-init))

```

What am i doing wrong? Do i have to setup something else?

**Comment by Ambrevar** [comment]
Isn't it the same as #133?

**Comment by Artraxon** [comment]
No, helm works with evil-collection enabled. Only the keybindings don't work

**Comment by jojojames** [comment]
Do you want 

```
 :after evil-collection
```

here?

Can you try without it?

**Comment by Artraxon** [comment]
It was one of the things i tried out, hoping it would make it work.
Removing the line does not help.

**Comment by Ambrevar** [comment]
Sorry I'm a bit busy these days, I'll come back to this as soon as possible.

**Comment by Ambrevar** [comment]
Wait, are you saying that _only_ the `C-j` and `C-k` bindings are not working?
If so, then it's absolutely normal, evil-collection-helm uses `M-j` and `M-k` instead.  This is because it also uses `M-h` and `M-l` to go back and forward.  Using `C-h` is not possible because it's a key reserved for help functions.

**Comment by NetherOrb** [comment]
For me none of the bindings are working. I have only normal emacs bindings in helm.

**Comment by speyejack** [comment]
I believe i am having the same problem as well. However, when i use "M-j" and "M-k" it puts a newline instead of moving.

**Comment by Ambrevar** [comment]
@speyejack: Can you post a minimal recipe / init file?

**Comment by speyejack** [comment]
Here is a init file that should produce the mentioned bug.

File: [https://github.com/speyejack/dotfiles/blob/orgConversion/configs/emacs.d/helm-collection.el](url)

Thank you very much for taking the time to help out!

**Comment by deviantfero** [comment]
I'm having this issue too! what can I do to help?

**Comment by Ambrevar** [comment]
OK, this is because you haven't enabled minibuffer bindings:
```
(setq evil-collection-setup-minibuffer t)
```

This is confusing too many people.  I'll make it more explicit in the documentation.

**Comment by deviantfero** [comment]
I already had that but I'm still having this issue, but I discovered the reason.

I'm using terminal emacs, it works fine on normal terminal, but when inside a tmux session it stops working, it has most likely nothing to do with `evil-collection` in that case, but still it would be good to do what you said, it is a bit confusing

**Comment by Ambrevar** [comment]
@deviantfero: This limitation is strictly due to terminals.  In fact, many default Emacs bindings also fail to be recognized.

If you can, I strongly recomment you switch to graphical Emacs (use Eshell + TRAMP for an overpowered replacement of tmux).

**Comment by speyejack** [comment]
@Ambrevar Thank you! Worked like a charm, I apologize for not realizing that earlier.

Thank you for the help!

**Comment by Ambrevar** [comment]
You are welcome!
@Artraxon Please re-open if this does not work for you.

**Comment by Artraxon** [comment]
Sorry, i meant "M-j" and "M-k", just switched to "vanilla" emacs from spacemacs recently.
Unfortunately, this doesn't help. Current use-packe section  looks like this:
````(emacs lisp)
;; Collection of evil keybindings
(use-package evil-collection
  :straight t
  :after evil
  :config 
  (evil-collection-init)
  :init
  (setq evil-collection-setup-minibuffer t))
````
"M-j" still adds newline

**Comment by Ambrevar** [comment]
I don't use `use-package` so maybe there is something wrong with the load order.  Try without `use-package` and set `evil-collection-setup-minibuffer` before loading `evil-collection`.

**Comment by deviantfero** [comment]
I do use `use-package` and this works for me

```lisp
(use-package evil-collection
  :after (evil helm)
  :ensure t
  :config
  (setq evil-collection-setup-minibuffer t)
  (evil-collection-init))
```

**Comment by Artraxon** [comment]
Ok, found the issue. I realized that i configured helm to load after evil-collection, which of course overwrote the keybindings. Setting evil-collection-setup-minibuffer to t in :config doesn't work for me, i put in in :init, which works fine.

A big thank you to everyone who helped me!
