### ISSUE TITLE
New Feature: Reserved keys

### ISSUE THREAD

**Issue by justbur** [emacs-evil/evil-collection#135]
It would be nice if I could provide a list of keys in states up front that wouldn't be overwritten by this package. This is most useful if you have a non-standard leader key. I know I can correct the bindings after loading the package, but then I have to go and find every conflict, which gets annoying. 

I'm imagining writing a custom `evil-collection-evil-define-key` that filters the keys before making bindings. I could write one.

**Comment by Ambrevar** [comment]
I think this is already possible with the key translation feature.
From the readme:

>   A more common use case of `evil-collection-translate-key` would be for keeping
>   the functionality of some keys that users may bind globally. For example, `SPC`,
>   `[`, and `]` are bound in some modes. If you use these keys as global prefix
>   keys that you never want to be overriden, you'll want to give them higher
>   priority than other evil keybindings (e.g. those made by `(evil-define-key
>   'normal some-map ...)`). To do this, you can create an "intercept" map and bind
>   your prefix keys in it instead of in `evil-normal-state-map`:

```elisp
(defvar my-intercept-mode-map (make-sparse-keymap)
  "High precedence keymap.")

(define-minor-mode my-intercept-mode
  "Global minor mode for higher precedence evil keybindings."
  :global t)

(my-intercept-mode)

(dolist (state '(normal visual insert))
  (evil-make-intercept-map
   ;; NOTE: This requires an evil version from 2018-03-20 or later
   (evil-get-auxiliary-keymap my-intercept-mode-map state t t)
   state))

(evil-define-key 'normal my-intercept-mode-map
  (kbd "SPC f") 'find-file)
;; ...
```

Would that work for you?

**Comment by justbur** [comment]
It's fine if you don't want to do this. I can work around it. I understand what intercept maps are, but those potentially cause other precedence issues to deal with. Translating keys is needlessly complicated for what I want to achieve. 

For a simpler example, suppose I only want evil-collection to rebind `hjkl` consistently across emacs (or some other set of keys. I don't know). Would it not make sense to have a whitelist of keys that evil-collection can touch for that case? My original request was for a blacklist.

I was just suggesting a simple tool to have a little more control over what evil-collection does. I feel this would also make it more predictable.

**Comment by jojojames** [comment]
It sounds like something we might be able to support. I noticed @hlissner's doom also has a few keys disabled which might be an ongoing burden to have to remove those keys everytime evil-collection adds new commands.

https://github.com/fread2281/doom-emacs/commit/a5ce6d145751dde11d0f6dae5c0ebd1b68652d46

My big worry is really evil-collection-evil-define-key gets a little wordy...

Curious what you guys think @Ambrevar @noctuid @hlissner.

**Comment by noctuid** [comment]
Intercept keymaps are the only sane solution to the blacklist issue in my opinion. I use non-standard prefix keys, and there are a lot of packages besides evil-collection that bind my non-standard prefix keys. Getting every package to provide a way to reserve keys is unnecessary work and will never be as foolproof as just using intercept keymaps to prevent the issue in the first place.

> potentially cause other precedence issues to deal with

Could you elaborate?

> ongoing burden to have to remove those keys everytime evil-collection adds new commands.

If these key bindings are mode-local, doom could just make them after evil-collection. If they are global but not "truly global" (shouldn't be bound in an intercept map), doom could unbind them using evil collection's hook (there's no need to manually unbind them in every single keymap). I think that's already a simple enough alternative for that specific issue.

`evil-collection-define-key` does seem like the best solution for the whitelist example. Evil collection's hook could also be used to unbind all keys except a whitelist, and that would require less changes to evil-collection, but it wouldn't, for example, handle the case where the user made keybindings in the keymap first (those would also be deleted). I think an `evil-collection-define-key` could also potentially be extended in the future to make other types of customization easier, so it sounds like a good idea to me.

**Comment by justbur** [comment]
> Could you elaborate?

I think the biggest issue with introducing intercept maps is that it introduces yet another level of keymap to think about. As you know, basic evil exacerbates the problem of having so many levels that is already present in basic Emacs. 

My sense is that promoting the use of intercept maps as a way to override all other keybindings is "wrong" in the sense that it adds more complication and is not an accurate statement. Intercept maps fall below some of the maps used in magit for example. 

My preference would be to promote the consistent use of evil-define-key for the (fictional) "average user" and if you are using evil-define-key exclusively, blacklists make sense. 

For an example of where using intercept maps might cause an issue, look at edebug-mode-map which is treated as intercept map, so using a private intercept map could (unintentionally) interfere with your edebug bindings. 

I understand that these are rare instances where problems arise, but I wanted to present a different perspective.

**Comment by noctuid** [comment]
> My sense is that promoting the use of intercept maps as a way to override all other keybindings is "wrong" in the sense that it adds more complication and is not an accurate statement. Intercept maps fall below some of the maps used in magit for example.

Well in all the readmes I've written that suggest using intercept maps, I only claim that intercept maps have a higher priority than other standard evil keybindings. In my evil guide, I explicitly mention text/char property keymaps and magit, and whitelisting/blacklisting with `evil-define-key` doesn't handle this case either. As for even higher precedence keymaps (e.g. used by hydra), generally you want these keybindings to override those made in intercept keymaps, so it's a good thing that intercept maps don't have the highest precedence.

As for complication, syntactically, using intercept keymaps doesn't need to be more complicated. I agree understanding intercept keymaps involves extra work on the part of the user, but I think that's true for any potential solution to this issue.

> My preference would be to promote the consistent use of evil-define-key for the (fictional) "average user" and if you are using evil-define-key exclusively, blacklists make sense.

I definitely agree that this is more flexible and would be useful for `evil-collection`, but the issue for me is that this requires every evil-related package to do this to be a generic solution. I guess if you implemented this directly in `evil-define-key(*)`, `evil-local-set-key`, and `evil-define-minor-mode-key`, you (probably) wouldn't have to worry about any packages. However, altering `evil-define-key` still wouldn't handle overriding keymaps, which is a potential advantage to using intercept keymaps. This wouldn't matter for users who exclusively use evil-collection, but `evil-make-overriding-map` can be quite nice for new modes where you want to use normal state without explicitly defining any keys.

> For an example of where using intercept maps might cause an issue, look at edebug-mode-map which is treated as intercept map, so using a private intercept map could (unintentionally) interfere with your edebug bindings.

I don't use `edebug-mode-map` as an intercept keymap, but edebug keybindings have precedence for me when it is an intercept map. This is by coincidence and not design currently, but it should be easy to handle for all cases. Auxiliary intercept maps only make sense for user keybindings, so they could just be added/checked after non-auxiliary intercept keymaps. I won't say the current implementation of intercept keymaps is perfect (inheritance handling could potentially be improved, though the same is the case for auxiliary keymaps), but I don't think any implementation issues are inherent to or invalidate the concept.

**Comment by Ambrevar** [comment]
Closing now whitelists and blacklists have been merged.
