### ISSUE TITLE
pdf outline keybinding

### ISSUE THREAD

**Issue by concavegit** [emacs-evil/evil-collection#138]
I may be missing something, but there does not seem to be a key binding to `pdf-outline` or an equivalent in `evil-collection-pdf.el`. If there is to be a keybining, `o` or `O` look attractive, but they are bound to `tabulated-list-sort` and `tablist-sort`. I have not used either function, but reading their descriptions it looks like there are not any use cases for a pdf and so I would personally bind `pdf-outline` to `o`.

Do you all agree that `pdf-outline` should be bound to `o`? Paging @Ambrevar to get the author's opinion.

**Comment by Ambrevar** [comment]
Absolutely, but I could swear this was how it used to be bound.  Not sure what happened.  I'll fix this.

**Comment by concavegit** [comment]
Thanks

**Comment by Ambrevar** [comment]
You said that `o` and `O` are bound to `tabulated-(list-)sort`?  That should only be true in a "PDF Occur" buffer.  Can you confirm?

**Comment by Ambrevar** [comment]
I know the reason for this oversight: The PDF bindings used to be in motion state and "o" automatically fell back to the binding of "o" in Emacs state then.  The infamous "motion->normal" transition pitfall.

**Comment by Ambrevar** [comment]
Fixed in 92e01bdbc7940cf1aad581e1978bbf6bb937d7f5.
