### ISSUE TITLE
Discussion: Support for already existent packages

### ISSUE THREAD

**Issue by maxsandova** [emacs-evil/evil-collection#140]
There are already some great packages like evil-mu4e and evil-org/org-evil that implement compatibility with evil-mode, but most of them don't quite agree with bindings implemented in evil-collection, some in minor things and some not at all. e.g. `go` in `mu4e-view-mode` does not open urls or links. Is the door open to do "light" re-implementations of these packages within evil-collection? or should I directly suggest keybindings to those packages?

**Comment by jojojames** [comment]
> Is the door open to do "light" re-implementations of these packages within evil-collection? or should I directly suggest keybindings to those packages?

I think we can do both. A small compatibility layer over existing evil-* packages that makes it a little more in line with evil-collection works for me.

**Comment by Ambrevar** [comment]
I'm working with upstream on bringing eivl-mu4e to par with Evil Collection.
Also `gx` (not `go`) is supposed to open URLs as per the rationale.

**Comment by Ambrevar** [comment]
https://github.com/JorisE/evil-mu4e/pull/14

**Comment by Somelauw** [comment]
The agenda bindings in evil-org are made by @Ambrevar and mostly (used to) follow evil-collection guidelines. 

I have given @Ambrevar collaborator status to evil-org in case he wants to work on providing consistency between bindings in org-agenda and evil-collection.

**Comment by Ambrevar** [comment]
@Somelauw: Thanks!

**Comment by Ambrevar** [comment]
Evil Ediff is now in.

Lispyville will probably remain out for the moment.

I'm OK for merging Evil Org but maybe not everyone is, so we can still discuss this.

I suggest we merge evil-magit.  @jojojames @noctuid @justbur ?

**Comment by justbur** [comment]
I don't want to merge evil-magit until the documentation is made easily accessible. I'm not sure how you want to handle this problem

**Comment by maxsandova** [comment]
evil-magit is big, it makes sense that it has its own section on a wiki. On another topic

I still have to put 
```lisp
(general-define-key
 :states 'emacs
 :keymaps 'magit-popup-mode-map
 "j"	 'forward-button
 "k"	 'backward-button)
```
in my config since magit-popup uses emacs-state by default (contrary to magit-status), can this be changed to normal state?

**Comment by Ambrevar** [comment]
I suppose you should report this to
https://github.com/emacs-evil/evil-magit :)

**Comment by jojojames** [comment]
> So you'd like to have per-package documentation beyond the binding tables?

FWIW, I think it's a good idea, barring any other better ideas.

**Comment by justbur** [comment]
>  So you'd like to have per-package documentation beyond the binding tables?

>> FWIW, I think it's a good idea, barring any other better ideas.

evil-magit is complicated enough that I think it deserves some verbal explanation that is easily found, especially since it provides toggles to change the behavior. Whether that's in a README, on the wiki or through some internal doc is not as important to me.

**Comment by jojojames** [comment]
@justbur Yup, I agree.

**Comment by jojojames** [comment]
I'll close this in favor of smaller more focused issue threads.

Thanks for bringing this up @maxsandova !
