### ISSUE TITLE
Move to Savannah / GitLab / NotABug?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil-collection#141]
Hot topic, I know...

What do you people think about the recent GitHub acquisition and using an actually open platform (e.g. Savannah) or a more-or-less open platform such as GitLab?

**Comment by Ambrevar** [comment]
There is also sr.ht: https://meta.sr.ht ?

**Comment by concavegit** [comment]
Disclaimer: I have never used Savannah or sr.ht though.

Well, I personally use GitLab so I am partial to it. The only downside of GitLab I have seen so far is that it is less well-known and checkedi-on and the occasional slow or frozen server.

**Comment by jojojames** [comment]
I don't have a strong opinion at this point though I'm open to switching if most feel it's the right choice.

**Comment by noctuid** [comment]
I don't have a strong opinion either, but I think it makes sense to only move if emacs-evil does too.

**Comment by concavegit** [comment]
No strong opinion here either.

**Comment by Ambrevar** [comment]
@noctuid: Absolutely.
@wasamasa: What do you think?

**Comment by wasamasa** [comment]
I think it's a hasty decision.  Let the smoke settle down and see what changes actually happen.  It's not as if GitHub was an open platform before, that aspect of won't change for the worse.  The only reasons I see for moving away are ideological ("I finally realized how evil it was to rely on GitHub! Let me repent by doing a 180!") or based on fear ("Microsoft is going to ruin GitHub just like it ruined all of its previous acquisitions!").  If the latter actually happens, that would be a good reason to move away.

Also, let's not forget that Evil was migrated from Bitbucket to GitHub for reasons such as visibility and familiar UI.  You'd lose either visibility (GitLab, NotABug, anything self-hosted), familiar UI (moving back to Bitbucket) or both (Savannah).

**Comment by Ambrevar** [comment]
I absolutely agree with that: GitHub wasn't great before and the "news" are not the one reason why we should change.

But independently of the news, the fact remains: GitHub is a rather closed platform and we could be better off moving to a more open platform.  Our projects are under GPL and it stands for a cause.  Keeping it hosted on GitHub somewhat defeats this cause.

Visibility has always been the main reason for me to use GitHub.  But it's a fallacious argument because it satisfies itself ("we stay here because everyone is here because we are here").

The acquisition might not be the proper argument for change, but it could be a global signal for a coordinated move away from GitHub: if we all move now, visibility will come along.

**Comment by jojojames** [comment]
Closing this for now as there seems to be no more discussion but open to more discussion of course.
