### ISSUE TITLE
Properly fix numeric argument for PDF-tools 

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil-collection#152]
In pull request #137, @concavegit added a workaround for an issue I could not reproduce, namely that numeric prefix argument did not work properly.

I'd like to know if other users can reproduce the issue when the workaround is not active.

**Comment by jojojames** [comment]
I think the burden to test this in the reverse is probably too much which is why this issue is still around. (I don't even use PDF-tools.) Maybe we can remove the patch, see if users complain and go from there?
