### ISSUE TITLE
evil-collection-diff-mode breaks magit-commit

### ISSUE THREAD

**Issue by Deewiant** [emacs-evil/evil-collection#156]
The way in which `evil-collection-diff-mode` unconditionally enables `read-only-mode` breaks committing in Magit (similarly to the way `diff-default-read-only` used to: https://github.com/magit/magit/issues/3170).

Should be easy to reproduce by attempting to commit anything with Magit after calling `evil-collection-init` but here are from-scratch reproduction instructions anyway, starting in a terminal:

```sh
$ mkdir test
$ cd test
$ git init
$ cat > file
(package-initialize)
(setq evil-want-integration nil)
(require 'evil)
(evil-mode 1)
(require 'evil-collection)
(evil-collection-init 'diff-mode)
(require 'magit)
$ git add file
$ emacs -Q file
```

And now in emacs:

```emacs
M-: (eval-buffer)
M-x magit
; (EDIT: updated this to include --verbose)
; Call magit-commit with --verbose to trigger the error
c -v c
; At this point, instead of the commit message buffer opening properly there's an error,
; so let's view the process buffer to see it:
$
```

At this point the process buffer should look like:

```
  1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Buffer is read-only: #<killed buffer>
error: There was a problem with the editor '/bin/emacsclient --socket-name=/tmp/emacs1000/server9279'.
Please supply the message using either -m or -F option.
```

Which pointed me to https://github.com/magit/magit/issues/3170. The fix there — https://github.com/magit/magit/commit/746f2361ba5e0299f05a7878e530da2c7c8f749b — overrides `diff-default-read-only` but that's not something that affects the behaviour of `evil-collection-diff-mode` in any way. Maybe it should? I could also see this being considered as another Magit bug but I'm not sure if it's reasonable for Magit to detect an arbitrary hook that sets `read-only-mode`.

**Comment by Ambrevar** [comment]
I'll look into it soon, thanks for reporting!

**Comment by Ambrevar** [comment]
I could not reproduce but you've highlighted a weakness in the read-only switch.
I've added a check so that only `diff-mode` is affected.

@Deewiant: Let me know if that works for you.
By the way, you can use `emacs -Q -l file` to save the `M-: (eval-buffer)` step :)

**Comment by Ambrevar** [comment]
OK, I could reproduce this time.
I've decided not to switch to read-only mode by default.   See 5affbdb02c5a6328b702a8a3da52d3d21fcea35d.  This is how vanilla Emacs behave, so it should work.  Let me know if you can come up with a better fix.

**Comment by Deewiant** [comment]
Thanks, that indeed works. I think it makes sense for `evil-collection` to stick with that and let read-onlyness be handled by other things like the vanilla `diff-default-read-only` setting (which Magit also understands).
