### ISSUE TITLE
Incompatibility with neotree: `evil-collection-neotree-setup: Invalid function: neotree-make-executor`

### ISSUE THREAD

**Issue by mrbig033** [emacs-evil/evil-collection#158]
* [init.el](https://gitlab.com/mrbig/dotfiles/blob/master/emacs/emacsv2/init.el)
* [.emacs.d](https://gitlab.com/mrbig/dotfiles/tree/master/emacs/emacsv2)
* [my complete environment (refer to the Manjaro install)](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

After I customized neotree and rebooted Emacs, it started showing the following message:
`evil-collection-neotree-setup: Invalid function: neotree-make-executor` after `M-x neotree` and `M-x neotree-toggle. It doesn't work anymore. Here's the [use-package](https://gitlab.com/mrbig/dotfiles/blob/master/emacs/emacsv2/customizations/custom-settings/use-packages.el#L265). I also tried without the extra settings (hook, theme etc). Same results. But when I disabled Evil-collection, neotree worked. For this reason I'm posting the issue here.

**Comment by Ambrevar** [comment]
I don't use neotree.  @jojojames ?

**Comment by Ambrevar** [comment]
@mrbig033 : Feel free to re-open if this does not work for you.
