### ISSUE TITLE
evil-collection: nil is not a keymap

### ISSUE THREAD

**Issue by djrmarques** [emacs-evil/evil-collection#167]
Hello.

When I try to initialize `evil-collection` via `evil-collection-init` I get an error:
 `evil-colletion: nil is not a keymap`. 

I have been trying to figure out what the problem iwith no success so far. In my config I have the usepackage tldr copied from the Readme. Does anybody know wha the problem is?

Thanks!

**Comment by Ambrevar** [comment]
My bad, this should be fixed with 9436d96d008fc50df4fcc4e419c6921ee7738e8e.

**Comment by Ambrevar** [comment]
MELPA rebuilds the entire repository every 4-5 hours I think.  Since the fix was
already pushed yesterday, I guess you can fetch the update from MELPA now.

**Comment by Ambrevar** [comment]
Feel free to close this issue if it's fixed for you.
