### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#169]
As we begin integrating more external packages (evil-ediff @justbur, evil-mu4e @JorisE, etc), what do you guys think of adding the maintainers of those packages to evil-collection (commit access for example).

I've touched on this in a few threads but I think those that merge their package in should, at the very least, be able to commit back to their merged package. It feels a little strange @JorisE can't make a quick change to evil-collection-mu4e for example.

Alongside this, I am thinking of others that would be welcome too (evil-org @Somelauw, @noctuid, etc).

Interested in hearing other thoughts! @Ambrevar

**Comment by Ambrevar** [comment]
I wonder why we haven't done it already! :)

I suggest we add a note in the README to contributors know that we are open to give contributor access to the repo.

**Comment by jojojames** [comment]
FWIW, I don't think I have the power to invite people to this repository anymore. I think we might have to look into 'Teams' or something. I don't really know how github works here.
