### ISSUE TITLE
evil-magit

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#170]
I think discussion around evil-magit is floating around in one of these threads so I'm opening a new one for more visibility.

In the interest of not letting this topic stall out, I want to make sure we know what steps we need to do to move forward. @justbur 

A wiki is fine, directly porting over evil-magit's is fine with me. I know there were quick discussions (@Ambrevar) around an in-emacs documentation. I don't want to bikeshed too much on the exact way so we can just 'pick one and go with it'!

**Comment by Ambrevar** [comment]
Well, I don't have a strong opinion either.

I think we could expand the `-describe-bindings` function to include per-mode documentation.

**Comment by justbur** [comment]
My opinion is that the readme should be easily accessible on the web in an obvious place. I expect that many people using this repo are coming from vim with little experience with emacs, so the in-emacs documentation doesn't make as much sense for them. Personally, it took a while for it all to click with me. 

I'd like it if each mode were treated as a "plugin" with its own folder and corresponding readme (the readme might just be a stub for some of them). Then clicking the corresponding folder brings up the readme directly. I've seen a bunch of projects on github organize things this way, and it seems like a natural way to browse the repo. 

If you don't like that idea, then the wiki is fine as long as it's organized and not just a mess of pages.

In-emacs documentation is great too, but my sense is that the web interface is more important for newcomers.

**Comment by Ambrevar** [comment]
I like the idea!

I don't see any issue with subfolders, it's a rather trivial change.
Besides we could also group related modes together which would bring more visility to some of them (e.g. image+ and image, or mu4e-conversation and mu4e).

**Comment by justbur** [comment]
A couple of more thoughts:

 1. It shouldn't be too hard to autogenerate/update the bindings portions of the readmes
 2. Once the readmes are there and assuming they're org files, we could write a function to do a completing read on the package and bring up the readme inside emacs quickly.

**Comment by jojojames** [comment]
Any thoughts on how to make requiring/loading the package seemless if the relevant files are moved one layer down?

I gave it a quick shot by just moving every file one layer down into a separate folder and with:

```
(let ((default-directory
          "/Users/james/.emacs.d/fork/evil-collection"))
    (normal-top-level-add-subdirs-to-load-path))
```

to add all the nested files to the load-path in order to load them. It's not much slower but is noticeable..

```
;; Before
Loading package evil-collection...
Configuring package evil-collection...done
```

```
;; After
Configuring package evil-collection...done (0.215s)
Loading package evil-collection...done (0.239s)
```

This is without byte compilation.

I think a package like evil-collection should start instantaneously.

**Comment by jojojames** [comment]
Nah, the process of adding all those paths to the load-path takes that long as it's done recursively.

**Comment by Ambrevar** [comment]
Is `normal-top-level-add-subdirs-to-load-path` so slow?
What about
```
(dolist (e (directory-files "."))
 (when (file-directory-p e)
  (push e load-path)))
```
?

**Comment by justbur** [comment]
I think manually using load and not polluting the load path is the right option here. We have control over the directory layout and adding lots of values to the load path slows down all requires. 

I’m sure there are other options too. I think you can get melpa  to dump everything in one directory. You could also just keep the readmes in folders and put the source elsewhere. It would be nice to keep them together but it’s not necessary. There’s gotta be a dozen approaches

**Comment by justbur** [comment]
Try https://github.com/justbur/evil-collection/commit/c6ff63b449c39717371a010492ebdb8bdc937ef5

**Comment by noctuid** [comment]
> I think we could expand the -describe-bindings function to include per-mode documentation.

> It shouldn't be too hard to autogenerate/update the bindings portions of the readmes

I have a customizable filtering system in the package I mentioned in #157 (`annalist.el`). For packages that use `defgroup` with `:prefix` and properly use that prefix for keymaps (as well as settings or commands if anyone ever wanted to record/display those in tables), it will be easy to generate per-package tables without needing to explicitly record the package. I haven't had any time to work on the package this week, but I'd also like to work on automatically generating keybinding tables and more complex filtering (e.g. maybe some basic form of tagging when recording) when I get the chance.

I also like the idea of using separate folders for separate READMES for the more complex packages.

**Comment by jojojames** [comment]
> Try justbur/evil-collection@c6ff63b

Works for me with a few minor changes (evil-collection-integration, evil-collection-settings) with no performance difference! I was trying to jigger the makefile to be able to compile recursively. Maybe @fbergroth knows how to do it.

**Comment by justbur** [comment]
@jojojames I fixed the makefile and the changes you referenced in a new commit on that branch

**Comment by jojojames** [comment]
@justbur Awesome, you actually fixed all the other small problems I found with it. Nice!

I think we can merge evil-collection-settings (independently) into evil-collection.el at some point. I had forgotten that file even existed.

This looks good to me, we can probably take a merge of that change (as a first step) unless you think there's something else needed before merging.

**Comment by justbur** [comment]
@jojojames I'll turn it into a pr

**Comment by jojojames** [comment]
@justbur 

Now that https://github.com/emacs-evil/evil-collection/commit/95dad4c734ae3d3811c05b259eea15ac4f3cb5c5 is in, ping on an intereset check.

**Comment by justbur** [comment]
Happy to do this, but I don't have a lot of time right now. If someone wants to take the lead, I'll help

**Comment by jojojames** [comment]
Sounds good, lets move discussions to https://github.com/emacs-evil/evil-collection/pull/259 @justbur
