### ISSUE TITLE
evil-org

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#171]
@Somelauw @Ambrevar 

I know there are some comments around evil-org and merging into this repo and/or moving to emacs-evil org at least.

Creating a topic here so things don't get lost in the shuffle.

As for me, I think it would be cool if it were moved to evil-collection (I use it myself so I'm a little biased. :))

**Comment by sondr3** [comment]
I'd love to see both evil-org and org-evil to be integrated, mostly because they overlap a ton but both are missing something that the other has (org-agenda in particular for me). 😄

**Comment by codygman** [comment]
Since evil-org has support for org and org-agenda now, should this be revisited?
