### ISSUE TITLE
evil-mc

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#184]
evil-mc has this keymap:

```
(defvar evil-mc-key-map
  (let ((map (make-sparse-keymap))
        (keys '(("grm" . evil-mc-make-all-cursors)
                ("gru" . evil-mc-undo-all-cursors)
                ("grs" . evil-mc-pause-cursors)
                ("grr" . evil-mc-resume-cursors)
                ("grf" . evil-mc-make-and-goto-first-cursor)
                ("grl" . evil-mc-make-and-goto-last-cursor)
                ("grh" . evil-mc-make-cursor-here)
                ("grj" . evil-mc-make-cursor-move-next-line)
                ("grk" . evil-mc-make-cursor-move-prev-line)
                ("M-n" . evil-mc-make-and-goto-next-cursor)
                ("grN" . evil-mc-skip-and-goto-next-cursor)
                ("M-p" . evil-mc-make-and-goto-prev-cursor)
                ("grP" . evil-mc-skip-and-goto-prev-cursor)
                ("C-n" . evil-mc-make-and-goto-next-match)
                ("grn" . evil-mc-skip-and-goto-next-match)
                ("C-t" . evil-mc-skip-and-goto-next-match)
                ("C-p" . evil-mc-make-and-goto-prev-match)
                ("grp" . evil-mc-skip-and-goto-prev-match))))
    (dolist (key-data keys)
      (evil-define-key 'normal map (kbd (car key-data)) (cdr key-data))
      (evil-define-key 'visual map (kbd (car key-data)) (cdr key-data)))
    map))
```

Which takes over the g/gr prefix. I think anyone using evil-collection and evil-mc is going to find some weird binding conflicts between the two.

I've had this HACK for a long time for evil-mc to remove the keymap completely and install my own.

```
  (defun +remove-evil-mc-keymap (&rest _args)
    "Brute force remove `evil-mc-key-map' from `evil-mode-map-alist'."
    (when-let ((evil-mc-map (assq 'evil-mc-mode evil-mode-map-alist)))
      (setq evil-mode-map-alist
            (delq evil-mc-map evil-mode-map-alist))))

  (advice-add 'evil-normalize-keymaps :after '+remove-evil-mc-keymap)
```

Anyone have a better idea on how to do this so we can make sure installing both packages is still a good experience?

**Comment by Ambrevar** [comment]
Since then I've dropped evil-mc, but my trick was to only enable it in prog-mode and text-mode.  Indeed, `gr` is mostly used in special modes.

**Comment by jojojames** [comment]
I found the bad behavior in something like wdired where there is editing but it's also a special mode.

**Comment by jojojames** [comment]
I think I'm going to go with ripping the keys out using the above approach if noone has something more elegant. :)

**Comment by jojojames** [comment]
Closing (added something for this) but open to other suggestions / PRs to make this better.

**Comment by ajgrf** [comment]
I think it would better to choose a different prefix than "gr" and use that to redefine all of the evil-mc bindings. Maybe "gc"?

**Comment by Silex** [comment]
If I enable `(global-evil-mc-mode)` the map is still active in visual mode. How do I completely remove the default map?

Also @ajgrf looks reasonable, but should we first make a PR for evil-mc which disables the default binding? or something that where at least we can configure the `gr` prefix.

**Comment by jojojames** [comment]
> How do I completely remove the default map?

Yeah, I see it too. Not sure how visual maps are bound in comparison to normal maps. I would've thought that alist is enough.

> Also @ajgrf 's suggestion looks reasonable, but should we first make a PR for evil-mc which disables the default binding? or something that where at least we can configure the gr prefix?

I'm up for a default prefix as well as the ability to just disable it. (Whichever default is OK.)

"gs" sounds good with me. I think there should be a PR on evil-mc side to set the binds properly though.

**Comment by Silex** [comment]
> "gs" sounds good with me. I think there should be a PR on evil-mc side to set the binds properly though.

Sounds like two PR, one here and one in evil-mc.

When you say "set the binds properly" what do you have in mind exactly?

**Comment by jojojames** [comment]
My thoughts on it haven't really materialized but I'm thinking evil-mc should probably make use of prefix keys instead of binding "gr*".

https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Keys.html

**Comment by Silex** [comment]
Ah, something like `C-c m *`? Yeah I kinda agree, multiple cursors is special enough for it to be treated differently.

**Comment by jojojames** [comment]
I just meant the "gr" binding should be a prefix. If you look at the binding definition, it's hardcoded to something like "grc", etc.

**Comment by Silex** [comment]
Ah right, thanks for clarifying :+1:

**Comment by jojojames** [comment]
I also dropped evil-mc a while ago and the current evil-mc impl in evil-collection seems passable.

Improvements can probably still be made to either evil-mc or evil-collection so someone with more passion on this integration is very welcome.

**Comment by Silex** [comment]
Started something in https://github.com/gabesoft/evil-mc/pull/100, will see how it goes.
