### ISSUE TITLE
SPC in evil-magit-todos

### ISSUE THREAD

**Issue by casouri** [emacs-evil/evil-collection#187]
Pressing SPC on a TODO entry in `evil-magit-todos-mode` allows you to "peek" the location.

Most people binds SPC to a leader key, could it be bound to some other key?

**Comment by noctuid** [comment]
You can bind `SPC` in an intercept map or add it to `evil-collection-key-blacklist`. You can then get whatever command SPC is bound to on another key for every mode using `evil-collection-translate-key`. I think this should be added to the FAQ.

**Comment by casouri** [comment]
Thanks, should I close this issue?

**Comment by jojojames** [comment]
@casouri I think what @noctuid mention should work.

You can also create a global intercept map too.

I just use general's override feature (which is similar to the intercept map approach).

```
(use-package general
  :ensure t
  :config
  (setq general-override-states '(insert
                                  emacs
                                  hybrid
                                  normal
                                  visual
                                  motion
                                  operator
                                  replace))
  (general-override-mode)
  (general-define-key
   :states '(normal visual motion)
   :keymaps 'override
   "SPC" 'hydra-space/body))
```
