### ISSUE TITLE
evil-paste-operator

### ISSUE THREAD

**Issue by Dickby** [emacs-evil/evil-collection#188]
I'm not shure if this package is meant to be only evilish key bindings, or if you are open for some functionality that would be nice to have, but that isn't present in vim and for that reason wouldn't be part of `evil-mode`.

If the latter is the case, i wrote a simple paste operator that i wrote a while ago, and use it a lot since.

the code goes like this:

```
(evil-define-operator my/evil-operator-paste (beg end)
  "Evil operator for paste over operator range"
  (interactive "<r>")
  (if (region-active-p)
      (evil-paste-after 1)
    (progn
      (evil-visual-make-region beg (1- end))
      (evil-paste-before 1))))
```

I bound it to `C-p` which already has `evil-paste-pop` bound to it, to use both on the same key
i use this function:

```
(defun my/evil-paste-pop-or-evil-paste-operator (count)
  (interactive "p")
  (if (memq last-command
	    '(evil-paste-after
	      evil-paste-before
	      evil-visual-paste))
      (evil-paste-pop count)
    (call-interactively 'my/evil-operator-paste)))

(define-key evil-normal-state-map (kbd "C-p") 'my/evil-paste-pop-or-evil-paste-operator)
```

I just thought it might be convenient for others too:
without
`viwp`
with it
`C-p iw`

It saves only one keypress, but at least for me, it feels much more vimy.
What do you think?

**Comment by Ambrevar** [comment]
I like it too, but then why not go all Vim-y and replace `p` instead?
- `pp`: paste below (equivalent to current `p`)
- `piw`: your example
- `p2j`: paste 2 lines below
- `pab`: paste "around braces"

etc.

That said, it think such a feature rather belongs to https://github.com/emacs-evil/evil.
Plus, since it departs from the default Vim behaviour, I think should be made an option.

**Comment by Dickby** [comment]
i like your keybindings, but i made my choice to impact the original bindings as little as possible.
I would be fine with both options though.
If this could be part of `emacs-evil` depends on what @wasamasa, @edkolev and @theBB think about this.

**Comment by edkolev** [comment]
This seems like a good package to me, but not really a part of evil itself - evil aims to follow vim.

**Comment by Dickby** [comment]
I expected that (and honestly i think it makes sense).
@Ambrevar are you shure you don't want it in evil-collection?
If so, i will consider to make it a package, but i would prefer not to.

**Comment by Ambrevar** [comment]
@edkolev: But it also has options such as `evil-want-C-u-scroll`.

@Dickby: the problem is I would not know where to fit it in.  Evil Collection only bothers with modes, not general bindings.

**Comment by noctuid** [comment]
See also [evil-replace-with-register] (https://github.com/Dewdrops/evil-ReplaceWithRegister).

**Comment by Dickby** [comment]
Oh, i saw this package, but i didn't realize that it works like my function if no register is specified.
Thanks @noctuid for pointing that out.
I close this issue.

**Comment by Dickby** [comment]
The only caveat is that evil-paste-pop doesn't work after evil-replace-with-register,
but i think that's not enough to make a package that is that similar.
