### ISSUE TITLE
evil-collection-elfeed.el -- adding read/star/auto-save

### ISSUE THREAD

**Issue by ibayer** [emacs-evil/evil-collection#190]
Thanks for this great set of evil configs.

I just started to use elfeed and realized that `evil-collection-elfeed.el` is
missing a few functions/key-maps that I think a crucial to effectively use `elfeed`.

1. fast way to mark post as read
2. fast way to mark interesting post `stared`
3. automatically save changes (otherwise tags are lost when closing emacs)

----

From the elfeed README [0] it looks like **1)** should only be a matter of adding key-maps.

----

The following sniped should address  **2)** - starring posts

```
(defalias 'elfeed-toggle-star
  (elfeed-expose #'elfeed-search-toggle-all 'star))

(eval-after-load 'elfeed-search
  '(define-key elfeed-search-mode-map (kbd "m") 'elfeed-toggle-star))
```
source [1]

----

The following sniped should add auto-saving **3)** on exit

```
;;write to disk when quiting
(defun bjm/elfeed-save-db-and-bury ()
  "Wrapper to save the elfeed db to disk before burying buffer"
  (interactive)
  (elfeed-db-save)
  (quit-window))
```
source [2]

I didn't manage to use  `evil-collection` together with the snippets listed above. Any suggestion on how to go about it would be much appreciated.

[0] https://github.com/skeeto/elfeed#getting-started see, second bullet point list
[1] http://pragmaticemacs.com/emacs/star-and-unstar-articles-in-elfeed/
[2] http://pragmaticemacs.com/emacs/read-your-rss-feeds-in-emacs-with-elfeed/
also note the comment that suggests changes for recent elfeed versions

**Comment by Ambrevar** [comment]
Very interesting indeed, but wouldn't such a change be a better fit upstream, in Elfeed itself?

**Comment by ibayer** [comment]
@Ambrevar 
Thanks for your answer. Only auto-saving (3) could be a candidate for upstream inclusion.
1 & 2 are only key mappings missing in `evil-collection-elfeed.el` IMO.

**Comment by Ambrevar** [comment]
1) You want a binding to only mark current post as read, correct?  Because we alread have `u` bound to `elfeed-search-untag-all-unread`.

2) I don't think Elfeed knows about "starred" item: here you are introducing an arbitrary tag, correct?  I think it's a nice feature, but Evil Collection only bothers with bindings, not features.  Which is why I think "starring items" should be merged upstream, not here.

Let me know if I misunderstood you.

**Comment by ibayer** [comment]
@Ambrevar 
Thanks for your patience. Your are right on both accounts, `u` works for read/unread and I can use `+` to create a `starred` tag. Even saving the changes works out of the box when I quit elfeed with `q`.

All I did was reinstalling all my packages and now everything is fine. :-)
