### ISSUE TITLE
Request: Tuareg Mode

### ISSUE THREAD

**Issue by WebsterWing** [emacs-evil/evil-collection#203]
Tuareg is the most common mode in emacs for editing OCaml code. However, it does not play nice with evil. Sometimes pressing escape while in insert mode will, instead of returning to normal mode, cause my cursor to jump backwards while displaying:
`abbrev-insert: Symbol’s function definition is void: tuareg-abbrev-hook`.
Adding a fix for this and also adding good keybindings would be much appreciated.

Thanks

**Comment by jojojames** [comment]
> abbrev-insert: Symbol’s function definition is void: tuareg-abbrev-hook

Hmnn an emacs -Q recipe for the ~evil~ repository would probably get you closer to a fix for that.

As for the rest of tuareg, I've never written a single line of ocaml so someone else might be better suited to doing it. I could give it a shot at some point though.

**Comment by condy0919** [comment]
Sorry, I can't reproduce the it.

https://github.com/emacs-evil/evil-collection/commit/25c395a175c7658cb7d7c12e7b2b11bc20c260a8 adds a minimal support for tuareg. Yes, only "gz" is added.

Closed, but feel free to reopen this issue.
