### ISSUE TITLE
binding for View-mode not work when visiting the buffer first time

### ISSUE THREAD

**Issue by BooAA** [emacs-evil/evil-collection#206]
Bug:

step1.  M-x dired, and enter any directory

step2. move cursor at any file, press "go" for dired-view-file

step3. inside the buffer opened, press "q", then it runs "evil-record-macro" rather than "quit-window"

This just happen for the first time visiting the file, actually you can press i to enter insert-state, than escape to normal-state, this time "q" will run "quit-window" as expected. Actually, any key bind on view-mode-map by evil-colletion has similar behavior (I have tested +, - , and get similar result)

My solution:

```lisp
(add-hook 'view-mode-hook 'evil-normalize-keymaps)

```

I fixed it by adding this line, "q" runs "quit-window" at first time as expected. I have met similar problem at other buffers not covered by evil-collection  (ex, the startup message buffer), it seems to be evil's problem.

**Comment by Ambrevar** [comment]
I've noticed similar issues with more sophisticate modes.  I've implemented a workaround for mu4e-conversation which uses `evil-normalize-keymaps`.  It's not pretty though :(

It seems to be an issue with Evil but I haven't investigated further.  Feel free to send a patch!

**Comment by Ambrevar** [comment]
No, I think we should still study if a "proper" workaround can be added to View mode.

**Comment by jojojames** [comment]
Thanks @BooAA . I added your workaround to View Mode. It works for me with that. If you see any other issues, please re-open.

@Ambrevar I think it's a known issue (not sure what exactly though). I just call evil-normalize-keymaps on misbehaving modes.
