### ISSUE TITLE
Request: Forge

### ISSUE THREAD

**Issue by Linuus** [emacs-evil/evil-collection#213]
[Forge](https://github.com/magit/forge) has been released. Can we add evil bindings for this package here or is it more appropriate to add it in evil-magit? There is an issue open for that here: https://github.com/emacs-evil/evil-magit/issues/54

What do you think?

**Comment by jojojames** [comment]
Lets wait for @justbur to respond. I think it would fit very well with evil-magit but I also think evil-magit could go into evil-collection at some point. Maybe once the new year passes, I'll look into https://github.com/emacs-evil/evil-collection/pull/178 to see if we can push this forward and hopefully get evil-magit integrated into evil-collection too.

**Comment by Linuus** [comment]
This has now been added in evil-magit 🎉
