### ISSUE TITLE
How to override existing binding in evil-collection?

### ISSUE THREAD

**Issue by Silex** [emacs-evil/evil-collection#214]
Hello,

I wanted to do something simple:

``` elisp
(use-package pack
  :after dired
  :bind (:map dired-mode-map
              ("P" . pack-dired-dwim)))
```

But because of https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-dired.el#L58, it does not work. I'm confused about where/how to handle this :sweat_smile:

**Comment by jojojames** [comment]
Hey, can you try https://github.com/emacs-evil/evil-collection/blob/4737aa47438a565119652212c16dade59f23b785/evil-collection.el#L489 to see if it works for you?

**Comment by Silex** [comment]
@jojojames: it does not work. If I disable `evil-mode`, the binding is correct (`P` calls `pack-dired-dwim`) but when I enable `evil-mode` it calls `dired-do-print`.

**Comment by jojojames** [comment]
Can you list your try/configuration?

**Comment by Silex** [comment]
Here you can try this to reproduce the problem (start with `emacs -Q` then eval-buffer):

``` elisp
(package-initialize)

(use-package pack
  :bind (:map dired-mode-map
              ("P" . pack-dired-dwim)))

(use-package evil
  :custom
  (evil-want-keybinding nil)
  (evil-want-C-d-scroll nil)
  (evil-want-C-i-scroll nil)
  (evil-want-Y-yank-to-eol t)
  (evil-default-cursor '(t "white"))
  (evil-magic 'very-magic)
  (evil-shift-width 2)
  (evil-want-fine-undo t)
  :config
  (evil-mode))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
```

**Comment by jojojames** [comment]
Where does that use this part from above?

```
(run-hook-with-args 'evil-collection-setup-hook
```

**Comment by Silex** [comment]
@jojojames: updated the snippet

**Comment by jojojames** [comment]
I see, you'll have to use the add-hook instead.

This snippet

```
(run-hook-with-args 'evil-collection-setup-hook)
```

was to say that evil-collection runs that hook. You should be able to add-hook 'evil-collection-setup-hook (I forget the exact params it returns to you) to catch on when dired sets up the keybindings.

**Comment by Silex** [comment]
> was to say that evil-collection runs that hook. You should be able to add-hook 'evil-collection-setup-hook (I forget the exact params it returns to you) to catch on when dired sets up the keybindings.

Ah, thank you for detailing. You mean that I have to write a little helper lambda/function that runs on `evil-collection-setup-hook` in order to overwrite `dired-mode-map` there?

This looks overly complicated when all I want is to replace a simple binding :sweat_smile:

**Comment by jojojames** [comment]
I'm open to suggestions but I think a hook is fairly simple already.

**Comment by Silex** [comment]
Okay, the only way I found to make it work is this:

``` elisp
(package-initialize)

(use-package pack
  :after evil
  :config
  (evil-define-key 'normal 'dired-mode-map (kbd "P") 'pack-dired-dwim))

(use-package evil
  :custom
  (evil-want-keybinding nil)
  (evil-want-C-d-scroll nil)
  (evil-want-C-i-scroll nil)
  (evil-want-Y-yank-to-eol t)
  (evil-default-cursor '(t "white"))
  (evil-magic 'very-magic)
  (evil-shift-width 2)
  (evil-want-fine-undo t)
  :config
  (evil-mode))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

;; (defun my-prefix-translations (mode mode-keymaps &rest _rest)
;;   (when (equal mode 'dired)
;;     (evil-define-key mode-keymaps 'dired-mode-map (kbd "P") 'pack-dired-dwim)))

;; (add-hook 'evil-collection-setup-hook #'my-prefix-translations)
```

You can see my attempt to use the hook at the bottom.

**Comment by Silex** [comment]
Given using `evil-define-key` works, I'll just use that. Thanks for the input.

**Comment by Silex** [comment]
Ah I finally understand why you insisted on using the hook and why my fix sometimes worked and sometimes not: evil-collection sets the binding using `with-eval-after-load`. That means when the mode are activated. That means if you define the key in a config section that is defined before `evil-collection-init` is called, it will be called first and then evil-collection will overwrite it.

Which means there are several solutions:
1. Make sure `evil-collection-init` is called before using `with-eval-after-load` or `:config` sections of use-package for other packages.
1. Use the hook `evil-collection-setup-hook` in order for evil-collection to tell you when its done with the key binding setup.

``` elisp
(use-package pack
  :after dired
  :hook (evil-collection-setup . (lambda (&rest a) (define-your-key-here))))
```
