### ISSUE TITLE
outline-mode bindings break standard evil motions

### ISSUE THREAD

**Issue by ajgrf** [emacs-evil/evil-collection#225]
`outline-previous-visible-heading` and `outline-next-visible-heading` are bound to `[` and `]`, so the spell-checking motions `[s` and `]s` can't be used. I think the obvious solution is to bind these functions to `[[` and `]]` instead.

Also `outline-up-heading` is bound to `^`, which shouldn't be a problem except that evil defines `z<ret>` in terms of the keyboard macro "zt^" (with similar macros for `z.` and `z-` too), so this needs to be worked around in evil-collection or changed in evil itself.

**Comment by Ambrevar** [comment]
Where are `[s` and `]s` defined?  I think this was discussed before, but I'm not sure we've reached a conclusion.

`[` and `]` are much more convenient in my opinion for keys that can be kept pressed.
But if we have `C-j` and `C-k` it's fine too I guess.

**Comment by ajgrf** [comment]
> Where are [s and ]s defined?

emacs-evil/evil#768

> [ and ] are much more convenient in my opinion for keys that can be kept pressed.
But if we have C-j and C-k it's fine too I guess.

They are more convenient. It would be cool if you only needed to press twice for the first movement (`]]` moves once, then a single `]` moves again).

**Comment by jojojames** [comment]
Thanks @ajgrf .

I think https://github.com/emacs-evil/evil-collection/issues/224 and https://github.com/emacs-evil/evil-collection/issues/64 are also related. 

I wonder what others think about adopting unimpaired's approach to evil-collection. @bling @noctuid  @Somelauw @hammerandtongs @Ambrevar

**Comment by bling** [comment]
i'm personally a fan of `[` and `]` for various reasons.  part of it is just history and muscle memory, and the other part is that it's a very natural way to add any type of "previous/next" in a generic fashion.  e.g. in my config i have `[e` and `]e` to navigate flycheck errors, as well as `[h` and `]h` to jump between git diffs for the current file.

fwiw i've already disabled anything from evil-collection that conflicts with a set of global keys that i use often with the following:

``` lisp
  (add-hook 'evil-collection-setup-hook
            (lambda (_mode mode-keymaps)
              ;; removes any bindings to SPC and , since they are global prefix keys
              ;; [ and ] are rebound to [[ and ]] respectively so global style vim-unimpaired mappings remain
              (evil-collection-translate-key 'normal mode-keymaps
                (kbd "SPC") nil
                "," nil
                "[" nil
                "]" nil
                "[[" "["
                "]]" "]"
                )))
```

**Comment by noctuid** [comment]
I don't use [ or ] at all personally. I think it would be preferable to not override vim/evil keybindings in any mode where they still make sense though.

**Comment by jojojames** [comment]
@bling I think there was an unimpaired package floating around. Do you think it'd have good synergy with evil-collection?

I haven't looked too deeply into the unimpaired stuff.

**Comment by bling** [comment]
i don't believe there's an unimpaired equivalent for emacs.  if you check the [source](https://github.com/tpope/vim-unimpaired/blob/master/plugin/unimpaired.vim), vim-unimpaired is just a bunch of miscellaneous stuff that's useful for vim.  however, like most things written by tpope, it's installed by a lot of vimmers.

**Comment by hammerandtongs** [comment]
Using unimpaired in evil-collection does seem like it could be broadly useful but it seems like it needs to be motivated by a larger list of concrete examples?

Here is the link to evil-unimpaired from spacemacs -

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-evil/local/evil-unimpaired/evil-unimpaired.el

TIm Pope's motivation for creating it is a good read as well https://github.com/tpope/vim-unimpaired

WIth emacs involved it seems like there should be a pretty rich set of useful pairings but that would require some exploration.

**Comment by jojojames** [comment]
I think we can first move all the ] -> ]] and [ -> [[ bindings to at least allow people like @bling to bind their [* keys without having to explicitly disable it in evil-collection (as well as fix @ajgrf 's issue).

2nd, it might be worth looking into each mode and see which modes might be wanting ]* type keys.

3rd it might be worth looking into evil-unimpaired which seems to be more global.

We should do the 1st, the 2nd is nice to have, the 3rd might not be necessary unless someone had a good idea on what it would look like in evil-collection. What do ya think @Ambrevar ?

**Comment by jojojames** [comment]
I've made some changes for 1.

@ajgrf Can you explain further and/or point me to where evil is doing this macro?

> Also outline-up-heading is bound to ^, which shouldn't be a problem except that evil defines z<ret> in terms of the keyboard macro "zt^" (with similar macros for z. and z- too), so this needs to be worked around in evil-collection or changed in evil itself.

@bling @hammerandtongs I'm definitely open to adopting some unimpaired-isms into evil-collection but since I didn't use the original, I don't have a strong feel for them. I'll shelve it personally for now until someone with more passion wants to add unimpaired-style bindings to evil-collection.

**Comment by ajgrf** [comment]
> I've made some changes for 1.

Great, thank you!

> @ajgrf Can you explain further and/or point me to where evil is doing this macro?
> > Also outline-up-heading is bound to ^, which shouldn't be a problem except that evil defines z in terms of the keyboard macro "zt^" (with similar macros for z. and z- too), so this needs to be worked around in evil-collection or changed in evil itself.

See [here](https://github.com/emacs-evil/evil/blob/3766a521a60e6fb0073220199425de478de759ad/evil-maps.el#L260). Defining the bindings `z<ret>`, `z.`, and `z-` as macros mean that all those key sequences have unexpected consequences when `^` is rebound.

Technically `^` is also a standard vim motion which you might want to avoid rebinding, although I don't think it gets used very often, and I didn't even know about until I looked up those macros.

**Comment by jojojames** [comment]
I dunno, that zRET stuff seems kinda hacky. (I admit I only took a quick look so I can definitely be wrong.)

Avoiding binding ^ because of that seems a tad unpalatable. :) Maybe others can chime in too. 

We could probably skip ^ and use - for backwards-up-motion (dired/outline-mode/etc) like netrw does if we want to avoid binding ^.

**Comment by hammerandtongs** [comment]
I would avoid rebinding ^ it's useful sometimes. - is also a motion key.

I'd also like to think that evil-collection should offer as little "why doesn't this work right?????" for vim users as possible?
 
Maybe an additional z-something?

**Comment by jojojames** [comment]
There's a balance, I think. If we avoided rebinding something because we think a vim user might be confused for the first time later on, I think we'd be settling for suboptimal bindings.

A vim user in special modes should know certain keys are replaced to do the special mode's action.

evil-magit also binds ^ by the way.

z* type binds I think are too many keys for probably simple functionality. I know I'd never press z(whatever letter) to go up a section for example..

**Comment by hammerandtongs** [comment]
The extra shift with the z^ would be a bit slow I agree.

zu however would be just fine I think? it works well within the context of normal vim folding.

I will point out that, unlike orgmode, magit and netrw are not text editing environments where we expect vim keys to be exactly the way they should be.

I get along with default evil and some light org-meta* org-shift* binds atm but I could using the outline keys more.

**Comment by jojojames** [comment]
I can agree if it's a mode in an text editing mode, we should probably take more care to avoid rebinding those types of keys. I don't really use outline mode much so I don't have a strong preference either way.

I'm not sure if zu is that great though. I think there are alot of commands people bind to "more than 1 letter" keys and end up never using it because they don't remember or it's too much of a bother. Whether the zu here is that case, I don't know.

**Comment by ajgrf** [comment]
> I don't really use outline mode much so I don't have a strong preference either way.

In case you didn't know, outline mode bindings affect org mode too.

**Comment by jojojames** [comment]
> In case you didn't know, outline mode bindings affect org mode too.

Yep. My point was about avoiding "^" in general.

**Comment by jojojames** [comment]
@Ambrevar What do you think about moving the ^ binding in outline mode? Like mentioned above, I don't really run into the issue much so I don't have a preference either way (on the new binding).

**Comment by Ambrevar** [comment]
I agree that rebinding "^" is problematic in non-special modes.
I personally bind it to Org-up-element anyways.  In the end, everyone is free to override the defaults, so I'm fine with removing "^" from outline mode.

**Comment by jojojames** [comment]
Sounds good, added.
