### ISSUE TITLE
Suggestion for evil-collection-mu4e.el

### ISSUE THREAD

**Issue by brabalan** [emacs-evil/evil-collection#226]
There is a bug in mu4e-compose mode where `G` and `gg` don't work in visual-line state. See here for more information: https://github.com/hlissner/doom-emacs/issues/975 and https://github.com/emacs-evil/evil/issues/1136.

To fix it, one needs to add
``` emacs-lisp
(evil-set-command-property 'mu4e-compose-goto-bottom :keep-visual t)
(evil-set-command-property 'mu4e-compose-goto-top :keep-visual t)
```

This has been added to doom, but it might be better to add it directly do evil-collection as it's an evil issue.

**Comment by Ambrevar** [comment]
Thank you very much for this, it has been annoying me for a while! :)

**Comment by brabalan** [comment]
That was fast, thanks!
