### ISSUE TITLE
Dired mappings violate guidelines

### ISSUE THREAD

**Issue by jackkamm** [emacs-evil/evil-collection#228]
I believe the `evil-collection-dired` mappings violate the Guidelines from the Readme:
> Keep the movement keys when possible and sensible.
> Keep the windowing keys when possible and sensible. 

Examples of keys that violate these guidelines are `H`, `L`, `M`, `T`, `W`, `t`. Personally, I find that I am frequently calling random functions when trying to navigate the dired buffer and have had to remove `dired` from `evil-collection-mode-list`.

However, it seems that `evil-collection-dired` has been pretty stable for some time now, and I am not sure whether you are open to making major changes to it. If I started a PR that deleted or remapped these keys, would you consider it?

If you are open to such a PR, would you be OK with simply deleting these keybinds, or would you require remapping them to something else? If the latter, I would like to start a discussion here about what would be good keys to rebind to.

**Comment by jojojames** [comment]
> Examples of keys that violate these guidelines are H, L, M, T, W, t. Personally, I find that I am frequently calling random functions when trying to navigate the dired buffer and have had to remove dired from evil-collection-mode-list.

I think the 'when possible and sensible' is the key point for me. Some modes are huge and it's not truly feasible to put movement keys in place of more useful functionality. (Not many people will want to press MKLJL to toggle marks for example. :)) A good example is evil-magit where most keys are bound to transients/magit-popups and a newcomer coming to the mode for the first time will run into what you're seeing with dired. I don't think pursuing movement keys is a priority when the mode is at the dired/magit/notmuch levels of huge.

> However, it seems that evil-collection-dired has been pretty stable for some time now, and I am not sure whether you are open to making major changes to it. If I started a PR that deleted or remapped these keys, would you consider it?

I am always open to tweaks to any mode disregarding 'stability' as long as the new changes seem to be superior to what was there before. (I don't think dired is very polished, for example.)

> If you are open to such a PR, would you be OK with simply deleting these keybinds, or would you require remapping them to something else? If the latter, I would like to start a discussion here about what would be good keys to rebind to.

Keep in mind, evil-magit binds all those keys you mention.

3 potential scenarios for me:

1. The current commands at the keys you mention are perfect where they are.
2. The movement keys are more appropriate and more ideal than the current commands.
3. There are *other* dired commands that would be more appropriate than the current commands.

I think we should tackle each keybind separately and consider which scenario plays out for each keybind (I also understand some of them are a "set" like H L M).

FWIW, I think 3 is what I'm thinking of when I think about polishing evil-collection-dired. 2 doesn't seem that desirable once the mode is huge. (If I ever get around to gnus for example, expect not many movement keys bound.)

As for the actual keys being mentioned, the only one I'd be attached to is 't'. I don't think you can get a better bind for toggle-marks than t but I'm open to changing my mind, of course.

Another thing you can look at is spacemacs' evilify macro which I believe priorities all movement keys and pushes other commands out in a systematic fashion.

**Comment by jackkamm** [comment]
Thanks for the considered response. I think my own preference is to keep more motion keys, and access extra dired functionality through `evil-execute-in-emacs-state` (bound to "\"), so I'll just disable `evil-collection-dired`. FWIW, I found the biggest pain point to be "W" (`browse-url-of-dired-file`), and believe "gx"(normally `browse-url-at-point`) would be a reasonable replacement.
