### ISSUE TITLE
elisp-refs <return> binding isn't working

### ISSUE THREAD

**Issue by sarg** [emacs-evil/evil-collection#230]
Consider replacing `<return>` binding to `'evil-ret` as `elisp-refs-visit-match` raises an exception.

**Comment by jojojames** [comment]
Does this seem like a bug on elisp-refs to you?

**Comment by jojojames** [comment]
How do you test without evil-collection in this case?

If I take elisp-refs out of the modes evil-collection loads for, I still see the bug (albeit evil is still loaded so I have to switch to emacs keymode.

evil-ret also doesn't seem to DTRT.

**Comment by sarg** [comment]
1. I have tested two ways:
- with clean emacs without evil and evil-collection
- emacs with evil disabled using `M-x evil-local-mode`

In both cases `RET` binding from `button-map` (`push-button`) takes precedence over minor mode map, which is `elisp-refs-visit-match`.

2. Yeah, `evil-ret` is not the solution, it works only on path button but not on code highlights provided by `elisp-refs`.

**Comment by sarg** [comment]
Solution from b17c48ca58ebf6f2963edaa277283c1ed7b0bed9 works fine.

**Comment by jojojames** [comment]
Should we have a generic function in evil-collection.el we can bind to? @Ambrevar

**Comment by Ambrevar** [comment]
Funny, I was wondering the same thing when I wrote the code for Notmuch.

Before anything else, which error are you talking about?  RET on the file names in the Refs buffer?  Note that this works in insert state but not normal state.

I also get an error if I press RET on "File:" or on an empty line in Emacs mode, so I guess that's an Elisp-refs bug.

The Notmuch approach is hackish, this is not how we should do things I believe.

Question: If Evil insert state uses the local property keymap, can't we tell normal mode to do the same?

**Comment by sarg** [comment]
@Ambrevar, yeah, you are right that `elisp-refs` has a bug. Filed it: https://github.com/Wilfred/elisp-refs/issues/25

And I am talking a bug when pressing `RET` on filename after `File:` would raise an error.

**Comment by jojojames** [comment]
Can you still reproduce with the latest HEAD?

I have evil-collection on and RET now routes to push-button.

Please reopen if you can still reproduce.

**Comment by sarg** [comment]
Works fine, thanks!
