### ISSUE TITLE
evil-collection-term: backward-kill-word does not work in insert(char mode), but does in line mode

### ISSUE THREAD

**Issue by nickstares** [emacs-evil/evil-collection#235]
When I run `backward-kill-word` within `terminal-mode` while in `evil-insert-state` (i.e.`term-char-mode`), I get
```
kill-region: Buffer is read-only: #<buffer *terminal<1>*>
```
However in `evil-normal-state` (i.e. `term-line-mode`), `backward-kill-word` will delete my prompt!

This is the opposite of the functionality I expect. Is there a way to change this or otherwise a  better function I can bind to <kbd>M-DEL</kbd> in `term-mode`?

**Comment by jojojames** [comment]
Thanks for the report. (Definitely took me a while to get to this. :))

I think it has something to do with multi-term loading. I don't get the repro if I use use M-x term (even with evil-collection on). After loading multi-term, the bug will appear. I've bound multi-term's functions to M-backspace. Let me know how it goes.

Not sure if we need M-DEL too, please PR if you need it, thanks!
