### ISSUE TITLE
Keybinding themes

### ISSUE THREAD

**Issue by clemera** [emacs-evil/evil-collection#241]
Changing keybindings consistently in Emacs is a hard task, mainly because the default bindings are hard coded in many places. With the traction and the broad scope of this project it could be useful outside of evil-mode, too. 

When the keybindings would be defined by variables which are set by a key theme, one could load sublime-text, vim or custom key themes. Some modes don't adhere to Emacs conventions so one could even load something like a strict-emacs theme, too. 

Any thoughts on this?

**Comment by noctuid** [comment]
I previously made the suggestion of having variables for specific types of actions (e.g. something like `evil-collection-quit-key`). I still think something like that could be a good idea. Right now, [key translation functionality](https://github.com/emacs-evil/evil-collection#key-translation) does exist and could hypothetically be used for creating different themes (but still using evil).

evil-collection is pretty tied to evil at this point. I think it would be a nice idea to make a more generic layer that just identifies the common functionality between packages. If this were to happen, it might make sense to have other themes in separate repos.

Doing this would require a ton of refactoring though. It could be done incrementally for one mode at a time but still would require a lot of effort from someone interested in allowing evil-collection to work without evil. Some of the keybindings evil-collection makes also wouldn't make sense outside of evil (e.g. if evil-collection makes keybindings in multiple evil states or when it rebinds evil ex commands), which could also complicate things for some modes. I do think it would be more ideal if non-evil users could also benefit from the package though.

**Comment by jojojames** [comment]
> With the traction and the broad scope of this project it could be useful outside of evil-mode, too.

Thanks yeah. I generally find the default emacs binding to be fairly consistent across emacs bindings with some caveats here and there.

> When the keybindings would be defined by variables which are set by a key theme, one could load sublime-text, vim or custom key themes.

I think it's doable, question is time, effort and total value-add. (I would be strictly using the evil-style themes so it'll be hard to write/test/maintain it unless someone else wants to do so for the other themes, which I'm perfectly fine with.)

> I previously made the suggestion of having variables for specific types of actions (e.g. something like evil-collection-quit-key). 

I think that's a good idea, I haven't thought too much about it in the practical sense though.

> Right now, key translation functionality does exist and could hypothetically be used for creating different themes (but still using evil).

Yeah, I think this is where having the key translation functionality can really shine. It shouldn't be too difficult to create a set of themes based off some sort of rotation. (Again, I'm probably not the person to do so but if someone wants to create a Sublime-style theme, I'd be open to it.)

> If this were to happen, it might make sense to have other themes in separate repos.

One thing I like about evil-collection is its easy "just install this one package and go" mentality so I'd hedge on keeping everything in one repo until it's close to imploding.

> Doing this would require a ton of refactoring though.

Yeah.. I'm open to it but I'm not too sure on the time/investment vs value-add for other users.

If it's splitting out the evil from evil-collection, that might be tricky but if it's keybinding themes/flavors off the evil framework, that might be a good first step.

**Comment by clemera** [comment]
> Right now, key translation functionality does exist and could hypothetically be used for creating different themes (but still using evil).

Thanks, that sounds useful. Personally I'm more interested in themes which wouldn't need evil-mode but this could probably be used for different key themes for people using evil.

> evil-collection is pretty tied to evil at this point. I think it would be a nice idea to make a more generic layer that just identifies the common functionality between packages. If this were to happen, it might make sense to have other themes in separate repos.

I just grepped through the repo using:

    grep -Eh "\".*?\" '" *.el  | sort

skimming through the results it seems to me that there are not that many keys which are really single purpose. Having a single resource which would define variables for those which are, would be great but probably this should be done by Emacs core, so that everyone could just use them and built in modes could slowly switch to define keys according to those variables, too. Not sure what Emacs devs think about this and probably it would take a long time for people/modes to adopt but hey Emacs is surely around for a few more years ;)

> I'm open to it but I'm not too sure on the time/investment vs value-add for other users.

Yes, probably not many evil-collection users would really benefit from this. Every now and then I just get frustrated that Emacs does not have something like key themes and search for solutions/ideas.   

Thank you both for sharing your thoughts!

**Comment by jojojames** [comment]
Closing but this is a good idea! If anyone has any more commentary, please reopen. :)
