### ISSUE TITLE
[emms] evil-collection functions can't modify playlist buffer

### ISSUE THREAD

**Issue by ajgrf** [emacs-evil/evil-collection#242]
When I try to use the keybindings for these functions I get `Buffer is read-only: #<buffer  *EMMS Playlist*>`:

- evil-collection-emms-playlist-mode-insert-newline-below
- evil-collection-emms-playlist-mode-insert-newline-above
- evil-collection-emms-playlist-mode-paste-before
- evil-collection-emms-playlist-mode-paste-after

These functions all use `emms-with-inhibit-read-only-t` to make the buffer temporarily writable, but for some reason it isn't working. Functions defined by emms itself all work fine, even the ones that make use of `emms-with-inhibit-read-only-t`.

I'm getting Emacs and packages from Guix, and I ran into this issue with even a very simple emms configuration:

    (use-package emms
      :config
      (require 'emms-info-libtag)
      (emms-all)
      (emms-history-load))

**Comment by jojojames** [comment]
@Ambrevar ?

Also @ajgrf emacs -Q fails too?

**Comment by Ambrevar** [comment]
Can't reproduce, sorry :(
The message might be misleading, maybe some other function is called
trying to modify the buffer.
Could you share a backtrace (run `M-x toggle-debug-on-error`).

**Comment by jojojames** [comment]
I'm guessing it's something to do with @ajgrf 's config (of course I might be wrong). 

Feel free to reopen if you come up with an emacs -Q recipe @ajgrf and/or backtrace. :D

Thanks for the report!
