### ISSUE TITLE
New tagged release

### ISSUE THREAD

**Issue by b3n** [emacs-evil/evil-collection#248]
When is the next tagged release expected? Is there anything holding it back? MELPA Stable is currently sitting at version 0.0.1 which is a year old, and the documentation around `evil-want-integration` is incorrect for anyone on this release. It would be great to see a new release.

**Comment by Ambrevar** [comment]
Agreed.

**Comment by jojojames** [comment]
Tagged a new stable release. Probably good to have before https://github.com/emacs-evil/evil-collection/pull/186 comes in.

>  Is there anything holding it back?

Nope, I don't have any regular cadence with it and most users seem to be on regular MELPA so it's kinda on the backburner until I get a helpful notification. 💃 

Thanks!
