### ISSUE TITLE
Cannot load modes after the move to subdirectories

### ISSUE THREAD

**Issue by simendsjo** [emacs-evil/evil-collection#257]
What is the correct way to load the modes now?

**Comment by jojojames** [comment]
Shouldn't be any change on your part.

Can you describe what you're seeing, what you've done, your config, etc?

Emacs -Q is probably your best bet.

**Comment by simendsjo** [comment]
I used

``` emacs-lisp
(with-eval-after-load 'some-mode
  (require 'evil-collection-some-mode)
  (evil-collection-some-mode-setup))
```

Seems like the `(require 'evil-collection-some-mode)` so longer works. I'm just trying to switch to a single `(evil-collection-init)`, although I seem to remember there was a good reason why I only used it for some explicit modes.

**Comment by jojojames** [comment]
https://github.com/emacs-evil/evil-collection/commit/107ed151e900cce76747d8c1135c874aff63050f#diff-6368190673f1bdd962cb26e3712b49ee ?

**Comment by simendsjo** [comment]
Ah, thanks!
