### ISSUE TITLE
evil-collection-init with a list of modes

### ISSUE THREAD

**Issue by ItsHoff** [emacs-evil/evil-collection#264]
Hey, I have a small gripe about `evil-collection-init`. Currently, if I want to give it a list of modes, I have to write
```
(evil-collection-init '((custom cus-edit) debug help (package-menu package) xref)))
```

I would prefer, if I didn't have to look up the proper form from `evil-collection-mode-list`, and could just write
```
(evil-collection-init '(custom debug help package-menu xref)))
```

**Comment by jojojames** [comment]
I'm thinking the value-add of this is may be to minor for me to justify the time commitment of writing the code for this, debugging/testing it and then dealing with any fallouts from potential bugs (e.g. bug reports, additional maintenance, etc).

Just my opinion though, and if @Ambrevar is open to it, I'm not against it (probably wouldn't do it myself but open to a PR in that case).

Thanks for opening the issue! These types of usability reports are important too, I think. If we get more +1s in the future, I think it'd be good to revisit.

**Comment by jojojames** [comment]
> I tend to agree with Olli that we are exposing an implementation detail
here.

I agree but that may not neccessarily justify the time it would take to "fix" this.

> By "key", I mean that if a mode is a list, then the key is its first element.

We'd probably have to go into more details about this. For example, what constitutes a key, is it the mode the user is expecting or is it the require that would load the package? If we try to support both, how do we do that? If we do that, what's the impact on startup? If we don't support both, is it  better than the current situation, etc etc.

On the other hand, and in a way, completely tangential, I'd prefer our users to be more like developers (e.g. someone that uses evil-collection is someone that also contributes to it) and less like users so issues like hiding implementation details are really low on my priority list.

It'd be nice to get to a point where users contribute back modes they're using that isn't already in evil-collection. My gut feeling is that implementing a binding from scratch is probably more complex and a bigger hurdle than we think, at this point.

**Comment by jojojames** [comment]
Closing but feel free to reopen.
