### ISSUE TITLE
Straight configuration

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#266]
@agsdot 

I think I remember you mentioning a straight configuration for evil-collection.

Was it straightforward (similar to a use-package setup) or did you have to do anything special?

If so, maybe we should add that configuration to the README.

**Comment by jojojames** [comment]
Going to close this but please reopen if you get back to this @agsdot . Thanks!

**Comment by michaelbogdan** [comment]
Not sure if this is what you asked for, but I run `straight.el` and `evil-collection` with absolutely no issues. Then again, I intentionally use `straight.el` because it integrates so well into `use-package` and serves as a drop-in replacement for `package.el`.

**Comment by jojojames** [comment]
@michaelbogdan Yeah, wasn't sure if there was some extra step required to use straight with evil-collection. My impression was there was from @agsdot but maybe that's not the case.

Thanks for commenting @michaelbogdan !

**Comment by dogayuksel** [comment]
Setup with straight.el is easy up until evil-collection@0.0.3. 

After migration into the nested directory structure (commits after 0.0.3 tag), nested files for modes are not copied into the build folder by straight.el.

I have tried the `:files` directive of straight.el but it doesn't preserve the structure, just symlinks into the root.

**Comment by jojojames** [comment]
@michaelbogdan Can you post your setup and @dogayuksel Can you post your setup?

Maybe we should see if there's some delta.

**Comment by dogayuksel** [comment]
Hey @jojojames, thank you for the quick response. Here is how I setup:

```
(use-package evil
  :after (undo-tree)
  :init
  (setq
   evil-want-integration t
   evil-want-keybinding nil)
  :config
  (progn
    (evil-mode 1)
    (setq evil-want-fine-undo t)))

(use-package evil-collection
  :after (evil)
  :straight
  (:type git :host github :repo "emacs-evil/evil-collection")
  :custom
  (evil-collection-setup-minibuffer t)
  :config
  (evil-collection-init))
```

I wasn't able to figure out how to configure straight.el to symlink (build) files under `straight/repos/evil-collection/modes/*/*.el` to `straight/build/evil-collection/modes/*/*.el`. @michaelbogdan Maybe you have a better understanding?

**Comment by dogayuksel** [comment]
I tried using develop branch of straight.el for something else, seems to fix the build issue mentioned above.
Just add `(setq straight-repository-branch "develop")` before bootstrap routine of straight.el.

**Comment by jojojames** [comment]
I see, so you think it's an issue between master branch of straight and develop?

**Comment by dogayuksel** [comment]
I checked the commits between master and develop today. evil-collection builds fine after this: https://github.com/raxod502/straight.el/commit/8c209c90c980af64db8c3a7528da2b89e751fad2. I believe this: https://github.com/raxod502/straight.el/commit/f8d9e81a8b64d978eaca569269f58132694e1bcf can also be related.

**Comment by michaelbogdan** [comment]
@dogayuksel Not sure whether I have a better understanding or I just didn't mess with my config enough to cause issues. :) Anyhow, here are the relevant lines of my `configuration.org`:

  (use-package evil
    :demand t
    :custom
    (evil-want-keybinding nil)
    :config
    (evil-mode 1))

  (use-package evil-collection
    :demand t
    :after evil
    :config
    (evil-collection-init))

I didn't let `straight.el` download the repository however, instead I manually pulled into `~/.emacs.d/straight/repos/evil-collection/` and do not have an entry for `evil-collection` in my `~/.emacs.d/straight/versions/*.el`. Instead I manually switch between `master` and whatever I am working on with `git checkout`.

So it seems the whole thing is some `straight.el` weirdness?
