### ISSUE TITLE
evil-collection-init overwrites bindings made with :general keyword in use-package declaration

### ISSUE THREAD

**Issue by michaelbogdan** [emacs-evil/evil-collection#267]
I like to put all my configuration into `use-package` statements, especially including key bindings. Since the `readme` for `evil-collection` explicitly mentions being a starting point, all usual manners of extending the key bindings should be supported.

`evil-collection-init` overwrites bindings declared with the `:general` key word in a `use-package` statement. I use `:general` and didn't test `:bind` or such, since `:general` integrates nicely with evil.

To reproduce, this should be a minimal example, made just for demonstration:

    (use-package dired
      :general
      (:keymaps 'dired-mode-map
       :states 'normal
       "j" 'quit-window))

The issue is that `evil-collection` initiates key bindings after packages are loaded, but `:general` evaluates together with `:bind` before package initialization. A trivial workaround is to use e.g. `general-bind-key` in `:config` which is evaluated after package initialization.

One way to solve this issue is to integrate with `use-key` and introduce a key word `:evil-collection` evaluated before `:general` and `:bind`, together with a custom variable `evil-collection-bindings-default`, replacing `evil-collection-init`. This allows turning `evil-collection` bindings on and off on a per-package basis, as well as users setting their key bindings with `:general`.

A `use-package` keyword would also be a more elegant way to exclude packages from `evil-collection-init` than removing the respective mode from the mode list, and to initiate `evil-collection` only for a select few modes. #264 is a related issue in that respect.

**Comment by jojojames** [comment]
@noctuid What do you think?

Barely knowing anything the use-package keywords (other than knowing they exist), I'd think either general can "work around" it or we can indeed try to play nice with general.

> A use-package keyword would also be a more elegant way to exclude packages from evil-collection-init than removing the respective mode from the mode list, and to initiate evil-collection only for a select few modes.

That seems pretty neat. If it works with the old evil-collection-init (e.g. for someone that doesn't use use-package) and someone else puts in the manpower to implement it, I think it's a good idea.

**Comment by michaelbogdan** [comment]
> Barely knowing anything the use-package keywords (other than knowing they exist), I'd think either general can "work around" it or we can indeed try to play nice with general.

I'm sorry if I was unclear: The issue is not with `general` itself, but the fact that `evil-collection` binds keys with `eval-after-load` where all `use-package` key words except `:config` evaluate before a package is loaded. `general` is just the only package I am aware of that is providing native  support for `evil` states.

> That seems pretty neat. If it works with the old evil-collection-init (e.g. for someone that doesn't use use-package) and someone else puts in the manpower to implement it, I think it's a good idea.

`evil-collection-init` would be unaffected, but couldn't be used together with the newer system, at least the way I imagine it should work. If @Ambrevar agrees and @noctuid doesn't recommend a better way, I am willing to put in the work.

**Comment by noctuid** [comment]
In the case that a package isn't loaded, general will use `after-load-functions` (not `eval-after-load`) to defer keybindings. If the package is already loaded, calling `evil-collection-init` first would work, but otherwise the evil collection keybindings will still happen last since evil-collection uses `eval-after-load`.

I think the best thing to do would be to just use `general-def` in `:config`. Personally, I only use `:general` for keybindings that are meant to load a package.

**Comment by jojojames** [comment]
> I'm sorry if I was unclear: The issue is not with general itself, but the fact that evil-collection binds keys with eval-after-load where all use-package key words except :config evaluate before a package is loaded. general is just the only package I am aware of that is providing native support for evil states.

Yeah, that's my point. There's some incompatibility so we either figure out if general can handle it (or vice versa evil-collection) and whether it's a good/feasible idea to do so.

> I think the best thing to do would be to just use general-def in :config. Personally, I only use :general for keybindings that are meant to load a package.

I'll defer to @noctuid for this.

Please reopen if you have any more thoughts though. :D

> evil-collection-init would be unaffected, but couldn't be used together with the newer system, at least the way I imagine it should work. 

I'm open to it but we'd need more crystalized ideas. Lets open a new topic for that once we have them. Thanks!
