### ISSUE TITLE
[QUESTION] In the spirit of evil-collection, does having a collection of evil equivalents to Vim plugins make sense?

### ISSUE THREAD

**Issue by michaelbogdan** [emacs-evil/evil-collection#269]
Unrelated to keybindings in particular, but I really like the collection aspect of `evil-collection`. To make `Evil` closer to `Vim` I think it can make sense to collect all equivalents to `Vim` plugins where they make sense, such as `evil-surround`, `evil-matchit` etc., at least in a simple list.

This would make transitioning for `Vim` users easier, as well as `Emacs` users trying out `vi` style keybindings, both without switching to `Doom` or `spacemacs`.

**Comment by jojojames** [comment]
You can see I added a small layer to support unimpaired style bindings (kinda empty at the moment :D) as well as default company to be more "ycmd-like", so there's definitely precedent already for it.

So, I'm all for it mostly, I use those two packages myself. For evil-surround and evil-matchit, it's just a question of if the original author/maintainer wants to merge it in.

**Comment by michaelbogdan** [comment]
> You can see I added a small layer to support unimpaired style bindings (kinda empty at the moment :D) as well as default company to be more "ycmd-like", so there's definitely precedent already for it.

I am not sure if you are aware, but there is [Zmaas' evil-unimpaired](https://github.com/zmaas/evil-unimpaired).

> So, I'm all for it mostly, I use those two packages myself. For evil-surround and evil-matchit, it's just a question of if the original author/maintainer wants to merge it in.

I think I'll start a mere list of popular `Vim` plugins, their `Emacs` equivalents and `evil` ports as a first step. This will be helpful both with a potential more complete `Vim` layer and for people mix and matching.

**Comment by jojojames** [comment]
> I am not sure if you are aware, but there is Zmaas' evil-unimpaired.

TBH, it's probably easier to port whatever additional binds that has to the current unimpaired than to port it over with evil-collection-isms. Quick look shows 6 pairs whereas evil-collection's has 2 pairs. I deliberately didn't add too many pairs because I wanted the community to PR them.

> I think I'll start a mere list of popular Vim plugins, their Emacs equivalents and evil ports as a first step. This will be helpful both with a potential more complete Vim layer and for people mix and matching.

Sure sounds good! I'll close this issue for now, lets create a new focused one once you do.

**Comment by michaelbogdan** [comment]
I found this list here [of Vim plugins](https://github.com/mhinz/vim-galore/blob/master/PLUGINS.md) and transformed part of it to `org` with tables [in this repo here](https://github.com/michaelbogdan/vim-to-evil). I'll add equivalents over time, feel free to contribute!

**Comment by jojojames** [comment]
Yeah that's a pretty sweet list.
