### ISSUE TITLE
Make the linter shut up about the requirement for Emacs 26.1 or higher

### ISSUE THREAD

**Issue by michaelbogdan** [emacs-evil/evil-collection#271]
Is there any way to stop `package-linter` from complaining about `if-let` and `when-let` since it is clear that they are only used if `Emacs` has the correct version? Seeing that 'build failing' message is a bit sad.

**Comment by jojojames** [comment]
Yeah I just added something for it, trying it out right now...

https://github.com/emacs-evil/evil-collection/commit/720a94cda6967b513a20b245b34cb1889004bb67

It's definitely a hammer, what I did though.

**Comment by michaelbogdan** [comment]
Whew, definitely a hammer. I think you can close this issue when you are done with tweaking the tests.

**Comment by jojojames** [comment]
Yeah, looks like it's passing now.
