### ISSUE TITLE
Disable <tab>-based bindings by default

### ISSUE THREAD

**Issue by magnetophon** [emacs-evil/evil-collection#274]
@Ambrevar [made these bindings optional](https://github.com/emacs-evil/evil-collection/commit/28eb46bd4439630bcb3ef4d65c2bff7d6fc7ffe4), which is great, but I'd go one step further and disable them by default.

The reasoning being:

- I'd estimate many more people use org-mode then pure outline-mode so it's more important to have good bindings in org.

- I'd say ``org-shifttab`` is more useful then  ``outline-show-all``, cause the former is a 3-way toggle and the latter is one-way-only.

I might be mistaken in my assertion of outline-mode cause maybe there's other much-used modes derived from it that are commonly used.

Ideally we'd have both bindings available in their respective modes, but [this thread](https://github.com/emacs-evil/evil-collection/issues/53) leads me to believe that's not so easy.

Note: I'm relatively new to emacs, so I might very well be missing a lot.

**Comment by Ambrevar** [comment]
I agree.
I actually got tripped by my own setting that I had completely forgotten :p

**Comment by magnetophon** [comment]
Cool!
Shall I do a PR, or will you just change it?

**Comment by magnetophon** [comment]
TBC: all we want is to toggle the default value of ``evil-collection-outline-bind-tab-p``, right?

**Comment by Ambrevar** [comment]
And update the documentation to highlight the change.
You can send a patch, I'll merge it.
Otherwise I'll do it when I get down to work on Evil Collection (not
before some while).
