### ISSUE TITLE
calling smartparen's function in evil-collection-lispy

### ISSUE THREAD

**Issue by yunhao94** [emacs-evil/evil-collection#278]
https://github.com/emacs-evil/evil-collection/blob/eb36c82a84d313e961777dc78fd4ff1d718efdf6/modes/lispy/evil-collection-lispy.el#L73

I found that `sp-next-sexp` here is a function defined in `smartparens`, but `smartparens` is not a dependency of `lispy` . Would it be better to replace the `sp-next-sexp` with `lispy-down` or other functions defined in `lispy`?

**Comment by jojojames** [comment]
Yeah that would probably be better than what we have now. I'm not sure if lispy-down is one to one with sp-next-sexp though.

**Comment by yunhao94** [comment]
IMHO, the purpose of calling sp-next-sexp is to make the cursor to a special state. Although lispy-down may not be one to one with sp-next-sexp, it just works for this case.

**Comment by jojojames** [comment]
Changed.
