### ISSUE TITLE
Join forces with evil-mode organization?

### ISSUE THREAD

**Issue by sondr3** [emacs-evil/evil-collection#28]
The evil-mode organization already has a few evil-mode compatibility packages, and personally I think it'd make sense to join forces with them. Not sure how feasible it'd be though.

**Comment by Ambrevar** [comment]
I've already open issues / discussed with all other maintainers:

- https://github.com/emacs-evil/evil-magit/issues/34
- https://github.com/Somelauw/evil-org-mode/pull/26
- https://github.com/GuiltyDolphin/org-evil/issues/14
- https://github.com/JorisE/evil-mu4e/issues/8

**Comment by sondr3** [comment]
Oh, I just looked in the main evil repository and not in the others.

**Comment by sondr3** [comment]
Regardless, what I wanted to get to was that you haven't considered becoming a repository in the evil-mode organization? Getting this effort officially recognized in a way. :)

**Comment by Ambrevar** [comment]
Of course! :)  But let's wait and see first.
If the project gets enough traction, we will submit the proposal.

**Comment by jojojames** [comment]
@justbur @Somelauw @GuiltyDolphin @JorisE @noctuid

We're already building on top of the work of these guys so working together is just a question of how (whether that's commit access/pull requests/being part of the main evil organization/etc). 

If there's interest, any of the above is doable.

**Comment by justbur** [comment]
I think it makes sense. To the extent that bindings can be made more consistent that's helpful. However, I don't think the projects need to merge right away.

I have loaded some of the bindings provided by this project but haven't done any extensive testing. 

Also, I have said this elsewhere, but I think the evil-integration.el bindings in the evil project is kind of a hack, and I'd be happy to see different major-mode bindings setup in a more transparent and configurable way. 

They should also be discoverable. The standard `C-h m` doesn't work with evil bindings, and this should be fixed somehow. I might try to take this on in which-key, but I don't have a lot of free time these days.

**Comment by Ambrevar** [comment]
> However, I don't think the projects need to merge right away.

Maybe not right away, and while there is absolutely no technical problem with having seperate packages for bindings, having one central package would make it easier for the user and somewhat help boosting Evil's popularity.

> Also, I have said this elsewhere, but I think the evil-integration.el bindings in the evil project is kind of a hack, and I'd be happy to see different major-mode bindings setup in a more transparent and configurable way.

Totally, I'd lean toward removing them entirely.  See #9.

> They should also be discoverable. The standard C-h m doesn't work with evil bindings, and this should be fixed somehow. I might try to take this on in which-key, but I don't have a lot of free time these days.

`C-h m` does work, actually, the bindings show up under the Emacs bindings.
The being said, it does not look pretty with all the "shadowed" lines.
I've opened issue #29 about this.

**Comment by jojojames** [comment]
> Maybe not right away, and while there is absolutely no technical problem with having seperate packages for bindings, having one central package would make it easier for the user and somewhat help boosting Evil's popularity.

For those packages, although we'd definitely welcome it with open arms, it'd probably suffice just to include them as a required package through melpa or something. I was thinking (in terms of joining force) more along the lines of commit access/pull requests/thoughts on the rationale/etc.

> Totally, I'd lean toward removing them entirely. See #9.

I believe he's talking about the actual evil-integration.el file in evil-core.

**Comment by justbur** [comment]
> I believe he's talking about the actual evil-integration.el file in evil-core.

That's right. I was. [This is the file](https://github.com/emacs-evil/evil/blob/master/evil-integration.el). It's an incomplete attempt to integrate existing Emacs modes and evil. 

> C-h m does work, actually, the bindings show up under the Emacs bindings.
The being said, it does not look pretty with all the "shadowed" lines.
I've opened issue #29 about this.

It kind of works. `C-h m` doesn't know about how evil auxiliary maps (and the other layers of evil maps) work. If you're in normal state and a binding from an auxiliary map shadows one of the standard major mode bindings, it's not that clear (to a novice at least) that that is what will happen based on the output of `C-h m`. The issue goes further than what you have identified in #29.

**Comment by justbur** [comment]
For those interested in major-mode discovery, try `which-key-show-major-mode` introduced in  https://github.com/justbur/emacs-which-key/commit/70d63a8babcc783cf0083b0094405d45303ec401

I'm not sure it's perfect so feel free to report bugs at which-key.

**Comment by Ambrevar** [comment]
Should we move this to the Evil organization at last?
@wasamasa?

**Comment by wasamasa** [comment]
@Ambrevar That's not really up to me to decide as it's @TheBB doing the Git organization stuff.  I don't see any reason not to, considering we already did move @justbur's evil-magit there for greater visibility.

**Comment by TheBB** [comment]
Hi @Ambrevar, @wasamasa 

Sorry for replying to this so late. I'd be happy to accept evil-collection into the evil org. The best way to do this is that I grant evil org membership to everyone who has write access to this repo, and then the owner (@jojojames) moves it. The MELPA recipe will have to be updated, and also your local remotes. Otherwise it's quite seamless. We did this with evil-surround.

I'll add @jojojames and if you ever want to pull that trigger, you can.

**Comment by Ambrevar** [comment]
I'd be very happy to have write access, thanks!

**Comment by jojojames** [comment]
Done.

Thanks @TheBB @wasamasa @Ambrevar.

And thanks @sondr3 for raising the issue.
