### ISSUE TITLE
[company-mode] Error on Emacs startup

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [emacs-evil/evil-collection#289]
I have a problem with the company-mode key bindings. When I start Emacs I get the below error: 

```Symbol's function definition is void: company-tng-configure-default```

My setup:

```
(add-to-list 'load-path "~/.emacs.d/evil-collection")
(setq evil-want-integration t)
(setq evil-want-keybinding nil)

(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)
(evil-mode 1)

(require 'evil-collection nil t)
(evil-collection-init)
```
When I change ```(evil-collection-init)``` by for example ```(evil-collection-init 'dired)``` everything works fine.

**Comment by jojojames** [comment]
That function has been there forever.

https://github.com/company-mode/company-mode/blob/b800fbd7e1402aa3c232041d519ee5dd4f3b2bf4/company-tng.el#L129

emacs -Q with company-mode and evil-collection if you're still seeing it.

**Comment by volodymyrprokopyuk** [comment]
The issue is still there. I just excluded the company-mode to be activated on startup.
