### ISSUE TITLE
Display Evil bindings cleanly in describe-mode

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil-collection#29]
`C-h m` (`describe-mode`) should only display the Evil bindings when the current state is an Evil state.
As of now, it display all the original Emacs bindings with a

>  (that binding is currently shadowed by another mode)

line and the Evil bindings underneath.  It's an overload of imformation.

Maybe we should look towards `which-key`.

**Comment by Ambrevar** [comment]
Fantastic!  Thanks for coming back to this long-standing issue!

Sadly I don't have much time to contribute at the moment... maybe in a few weeks?

**Comment by jojojames** [comment]
We can probably close this with annalist in (though it doesn't fix the "describe-mode" thing).
