### ISSUE TITLE
Avoid binding `zb` in outline mode.

### ISSUE THREAD

**Issue by crocket** [emacs-evil/evil-collection#292]
In other modes, `zb` is bound to `evil-scroll-line-to-bottom` which I'm accustomed to.

I suggest rebinding `zB` and `zb` somewhere else in outline mode.

Here's my current setting.

```
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init)
  (add-hook 'org-mode-hook
            (lambda ()
              (define-key evil-normal-state-local-map
                "zb" #'evil-scroll-line-to-bottom))))

```

**Comment by Ambrevar** [comment]
Any suggestion for good bindings?  Outline mode has so many of them, it's really tricky to get them right :p

**Comment by crocket** [comment]
`zd` and `zD` are vacant in outline mode and org mode.

**Comment by Ambrevar** [comment]
Sounds good!
