### ISSUE TITLE
evil in minibuffer has interaction with ivy-posframe

### ISSUE THREAD

**Issue by ambihelical** [emacs-evil/evil-collection#293]
When I enable evil in the minibuffer, there is an interaction with ivy-posframe.  Specifically, the minibuffer area shows a cursor which moves as input is typed in the posframe.  Nothing else appears in the minibuffer area and there doesn't seem to be any functional issue.  I have the following setup for evil-collection.  If I comment out the custom setting the cursor does not appear.

```
(use-package evil-collection
  :custom
  (evil-collection-setup-minibuffer t)
  :after evil
  :defer 1
  :config
  (evil-collection-init))

```

ivy-posframe is setup as follows:

```
(use-package ivy-posframe
  :hook (( ivy-mode ) . ivy-posframe-mode)
  :init
  (setq ivy-posframe-display-functions-alist
        '((swiper          . ivy-posframe-display-at-point)
          (counsel-M-x     . ivy-posframe-display-at-window-bottom-left)
          (t               . ivy-posframe-display-at-frame-center))))


```
I can work up a minimal init.el if necessary.

**Comment by ambihelical** [comment]
I also notice the following:  If I change to normal mode while using ivy-posframe and move the cursor back over any characters already typed, the character at the cursor (and only that character) is shown in the minibuffer area simultaneously.

**Comment by Ambrevar** [comment]
Do you have Helm installed?  If so, what's the value of helm-echo-input-in-header-line?  See the evil-collection-helm-hide-minibuffer-maybe docstring for an explanation.
If Helm is installed as a dependency and you don't really use it, you may eitehr customize helm-echo-input-in-header-line or disable the Evil bindings for Helm.

**Comment by ambihelical** [comment]
I don't use helm directly and there's no helm related packages in my elpa directory, at least nothing with "helm" in the name.

**Comment by ambihelical** [comment]
This isn't an evil-collection bug, I've isolated it to either ivy, ivy-posframe or evil.

**Comment by ambihelical** [comment]
Added an issue in ivy-posframe https://github.com/tumashu/ivy-posframe/issues/85
