### ISSUE TITLE
Compilation warning: reference to free variable `dashboard-mode-map`

### ISSUE THREAD

**Issue by JeremyDurnell** [emacs-evil/evil-collection#307]
The following compile warning is observed upon initial installation with following code in `~/.emacs`:
```
(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))
```
```
Compiling file /home/jkdurnell/.emacs.d/elpa/evil-collection-20200216.800/modes/deadgrep/evil-collection-deadgrep.el at Mon Feb 17 22:33:10 2020
...
Compiling no file at Mon Feb 17 22:33:12 2020
Warning (bytecomp): reference to free variable ‘dashboard-mode-map’
```
It seems like it might be due to the following in `evil-collection-dashboard.el`
https://github.com/emacs-evil/evil-collection/blob/e6a4ba695ea845fc25fb655c5965d999758adae1/modes/dashboard/evil-collection-dashboard.el#L33

**Comment by Ambrevar** [comment]
Fixed in a478a95a8a3665e40bdae3bab2a0519db6c1f29c.
Thanks for reporting!
