### ISSUE TITLE
Request - add Vim cntrl-x behavior to company module 

### ISSUE THREAD

**Issue by hammerandtongs** [emacs-evil/evil-collection#308]
Per https://www.reddit.com/r/emacs/comments/f6aemn/vims_x_mode_in_evil_mode/fi3l4ha/

Essentially this allows you to hit cntrl-x in insert mode then select a specific company-completion from a premade list ie say you are programming and you just temporarily want to complete from spelling or file paths only (or perhaps you keep your company modes slim when tab completing and want access to other modes).

https://github.com/hlissner/doom-emacs/blob/524985ed816d291e4fe9b01f4da6a2bf4f52006c/modules/editor/evil/config.el#L590-L599

Is the implementation in doom

**Comment by Ambrevar** [comment]
I'm not sure I understand the issue.  Actually the comment on Reddit is accurate it seems:

https://old.reddit.com/r/emacs/comments/f6aemn/vims_x_mode_in_evil_mode/fi6fyxf/

When in insert mode, I typically press `<tab>` or `M-<tab>` to enable completion.
I use company-mode and Helm.
Doesn't it work for you?

**Comment by hammerandtongs** [comment]
I was confused when I read it too.

Cntrl-x is not a normal tab completion.

Cntrl-x is followed by \<some key\> that selects a specific completion mode from a list.

Does the config list doom emacs help make sense of it?

```
;; Omni-completion
      (:when (featurep! :completion company)
        (:prefix "C-x"
          :i "C-l"    #'+company/whole-lines
          :i "C-k"    #'+company/dict-or-keywords
          :i "C-f"    #'company-files
          :i "C-]"    #'company-etags
          :i "s"      #'company-ispell
          :i "C-s"    #'company-yasnippet
          :i "C-o"    #'company-capf
          :i "C-n"    #'+company/dabbrev
          :i "C-p"    #'+company/dabbrev-code-previous)))
```

I was not familiar with this from Vim but it does look useful.

**Comment by jojojames** [comment]
This does look pretty cool. It looks like quite a few functions are probably implemented in doom itself (the company/ functions). 

I think it'd be pretty nice to add to evil-collection, if we could somehow pull or take some sort of inspiration from @hlissner . PR welcome!

**Comment by jojojames** [comment]
Looking at the referenced PR, the PR doesn't completely address the feature request, right? Think the PR doesn't have a ctrl-x prefix attached to it. (https://github.com/emacs-evil/evil-collection/pull/558) @pspiagicw @hammerandtongs  Please confirm.
