### ISSUE TITLE
Unable to execute Vim commands in terminal mode

### ISSUE THREAD

**Issue by hisnawi** [emacs-evil/evil-collection#311]
When trying to quit emacs in terminal mode using:
:q 
The Enter takes it to a new line in the minibuffer.
Also substitution:
s/x/y
With and enter takes it to a new line.

Is this expected? or am I missing something in the setup?

**Comment by Ambrevar** [comment]
Did you solve your issue?

**Comment by hisnawi** [comment]
@Ambrevar Yes, I had this in my init file which I dont even remember the reason for:

```
      (with-eval-after-load 'evil-maps
        (setcdr evil-ex-completion-map
                (--reject
                 (and (memq 'control (event-modifiers (car-safe it)))
                      ;; abort prompt
                      (/= (car-safe it) ?\C-c)
                      (/= (car-safe it) ?\C-g)
                      ;; previous/next input
                      (/= (car-safe it) ?\C-p)
                      (/= (car-safe it) ?\C-n))
                 (cdr evil-ex-completion-map))))
```

Which I now qualify with `(if (display-graphic-p)`

**Comment by Ambrevar** [comment]
OK, thanks!
