### ISSUE TITLE
vim command key binding

### ISSUE THREAD

**Issue by parisni** [emacs-evil/evil-collection#312]
In vim command "mode", it turns out most navigation expected key binding (based on readlines) works fine:
- `<C-p>` : history previous
- `<C-n>` : history next
- `<M-f>` : word forward
- `<M-b>`: word backward
- `<M-d>`: delete word forward
- `<M-SPC>`: delete word backward
- `<C-u>`: delete line backward

However several are missing are affected to other:
- `<C-b>`: move character backward
- `<C-f>`: move character forward
- `<C-k>`: delete line forward

That would be so great to get them consistent with readlines. 
Thanks

**Comment by jojojames** [comment]
Can you give a concrete example?

PR welcome, as always.

**Comment by parisni** [comment]
> Can you give a concrete example?

for example:

```
:s/bob/jim/g
```

If the cursor is on before the "i" of jim, and I want to move it before
the "j", my only option is to use the left arrow. Readlines shortkey
provides the <C-b> to do this thing.
And so on.

**Comment by Ambrevar** [comment]
I can press Esc and move the cursor with <hjkl>.

**Comment by parisni** [comment]
> I can press Esc and move the cursor with <hjkl>.

Good to know those shortkeys can be changed. What are the command names
for those moves ? I cannot figure out how to change the setup for this.

thanks

**Comment by Ambrevar** [comment]
I'm not sure what you are asking.  Are you looking for
minibuffer-related commands?
If so, have a look at the evil-collection-minibuffer.el file.

**Comment by jojojames** [comment]
I think @parisni is talking about when you press ':' in normal mode right?

I think the binds are from evil-mode, off the top of my head, I don't think we have an integration for it. It's probably most appropriate for evil-mode if so. (I might be wrong here, didn't look super closely.)

**Comment by parisni** [comment]
James N <notifications@github.com> writes:
> I think @parisni is talking about when you press ':' in normal mode right?

yes, it is. ':' in normal mode. for example :wq to save and quit. or
:s/jim/bob/ to replace text. I am talking about the shortkey in this context





-- 
nicolas paris

**Comment by Ambrevar** [comment]
Indeed, I think this issue should be reported to Evil itself.
