### ISSUE TITLE
Keymap is modified after writing something in custom-mode search box.

### ISSUE THREAD

**Issue by crocket** [emacs-evil/evil-collection#313]
After writing something in custom-mode search box, Tab key is mapped to evil-jump-forward.
Before doing so, it is mapped to widget-forward.

Why does keymap change?

**Comment by Ambrevar** [comment]
I can reproduce.

I have a similar issue with Org mode by the way: M-l is first bound to
evil-window-bottom.
If I switch to insert state then back to normal state, then M-l gets
bound to org-metaright.

**Comment by crocket** [comment]
But, evil org mode is not part of evil-collection.

**Comment by Ambrevar** [comment]
The issue could come from Evil.

**Comment by jojojames** [comment]
This is a real issue, I took a quick look a while back but it seems specific to evil&emacs itself. Closing but happy to take a PR from anyone on this.
