### ISSUE TITLE
Paste failed in helm under terminal

### ISSUE THREAD

**Issue by introom** [emacs-evil/evil-collection#316]
In terminal, paste will result in 
M-x 200 201~. stufff.

For example:
Paste the word **terminal** we get:
![image](https://user-images.githubusercontent.com/669045/77934500-c31f3880-72e2-11ea-85f4-21207d532b74.png)

**Comment by introom** [comment]
evil-collection-helm.el is enabled.   this behavior only happens under terminal (iterm2 and terminal.app since I am on amc)

**Comment by jojojames** [comment]
https://github.com/emacs-evil/evil-collection/blob/master/modes/helm/evil-collection-helm.el doesn't seem to even bind "p", maybe https://github.com/emacs-evil/evil-collection/blob/e6824e2ad2f2ee7ddccf6f54db655a4cd37a13dc/modes/helm/evil-collection-helm.el#L208 ?

This may not be an issue with evil-collection. Please update/reopen this thread with emacs -Q, and/or more descriptive steps, information about bug.
