### ISSUE TITLE
evil-collection-unimpaired-insert-space-above  works not as expected

### ISSUE THREAD

**Issue by anuvyklack** [emacs-evil/evil-collection#320]
Description :octocat:
The `evil-collection-unimpaired-insert-space-above` command seems to work not like expect when the line is empty, or when the cursor is at the first column.

Reproduction guide 🐞
Open a file with enabled Evil mode and navigate to a line with the text.
Execute the `evil-collection-unimpaired-insert-space-above` command (`[ SPC`).

Observed behavior: 👀 💔
When the cursor is in the middle of a line that has text, the cursor stays in its position in the text and the current line shifts downward, relatively, as blank lines appear above the current line. This is what we want.

But when the cursor is in a blank line, it seems to stay in place, but blank lines appear beneath the current line.

And when the cursor is in a line containing text and positioned at the first column, the new line appears above but the cursor moves into it.

Expected behavior: ❤️ 😄
The `evil-collection-unimpaired-insert-space-above` should always insert lines above the cursor, regardless of whether the current line has any text content.

I spent some time trying to figuring out why, and it seems that this behavior is due to the [save-excursion](https://github.com/emacs-evil/evil-collection/blob/493d523c9bcdeb2213f18cbf73c9e33de854dd34/modes/unimpaired/evil-collection-unimpaired.el#L81) function: it does not restore the point position (or do it wrong) if the cursor is at the beginning of the line.

**Comment by anuvyklack** [comment]
I am learning lisp third day, and sure there is a better solution but this function seems to solve the problem:

```lisp
(defun evil-collection-unimpaired-insert-space-above (count)
  "Insert space above current line"
  (interactive "p")
  (dotimes (_ count)
    ;; (defvar-local position (point))
    (setq position (point))
    (save-excursion (evil-insert-newline-above))
    (goto-char (+ position 1))
    (makunbound 'position)
  )
)
```

If use `defvar-local` instead of `setq` it doesn't work. I don't know why.

**Comment by jojojames** [comment]
If it's save-excursion that may be the problem, maybe save-mark-and-excursion?

**Comment by anuvyklack** [comment]
No `save-mark-and-excursion` also doesn't work.

**Comment by anuvyklack** [comment]
This is better soluion:

```lisp
(defun evil-collection-unimpaired-insert-space-above (count)
  "Insert space above current line"
  (interactive "p")
  (dotimes (_ count)
    (save-excursion (evil-insert-newline-above))
    (if (bolp) (forward-char 1))
  )
)
```
