### ISSUE TITLE
Visual state inconsistencies in Info mode

### ISSUE THREAD

**Issue by justcosmic** [emacs-evil/evil-collection#322]
So, I decided to pick up emacs with evil and evil-collection but I have some issues with visual state in info mode. In normal state, when I press `h` or `l` it moves a point by one character (as expected) but in visual state these mappings change. When in visual state I checked `C-h b` and found that:

```
h		Info-help
l		Info-history-back
```

So mappings seem to change upon changing a state.

Also, when trying to yank some text, I hardly get an expected result. For example, doing `yw` yanks nothing and `ya"` yanks ` "text between quotation marks."`.

As I'm new to emacs, I'm not sure if this is an issue with evil-collection or evil itself. I'd appreciate if you would point me in the right direction.

**Comment by Ambrevar** [comment]
Thanks for your report!

I've fixed the h/l issue in 0dfc9df390279beea8d0697d7f545a3cb913de85,
thanks for the catch!

`ya"` is indeed supposed to yank text between double quotes.  I'm not
sure I understand the problem.

`yw`, `vw`, `yl` etc. don't work as expected.  I don't understand why
though :(

**Comment by justcosmic** [comment]
Thanks! It works now.

Ah, sorry, what I meant is that when I try to yank **any** text between quotation marks (say `"expression"`) and then paste it, it always appears as `"text between quotation marks."`, not the original one I yanked. However, I've just tried reproducing it and it seems that the problem is gone (huh).

Yanking using `yw` doesn't work though. I've tried other motions and it turns out that `yW` does work. That's weird because when not yanking I can move using `w` and `W` as intended. Also, `yb` yanks to the beginning of the buffer, `ye` yanks to the end of it and `ygg` triggers `Info-goto-node` (as in visual mode, see the list below).

In the meantime I've been looking for more. Let me illustrate them in the following format (`<key>` `<normal state>` `<visual state>`):

- `gg`, `evil-goto-first-line`, `Info-goto-node`.
- `b`, `evil-backward-word-begin`, `beginning-of-buffer`
- `w`, `evil-forward-word-begin`, `Info-copy-current-node-name`
- `e`, `end-of-buffer` (both in normal and visual state)
- `0`, `evil-digit-argument-or-evil-beginning-of-line`, undefined
- `f`, `evil-find-char`, `Info-follow-reference`
- `t`, `evil-find-char-to`, `Info-top-node`
- `T`, `evil-find-char-to-backward`, `Info-toc`
- `^` triggers `Info-up` both in normal and visual state. I'm not sure if this is intended but I'd rather expect it to be `evil-first-non-blank`.

**Comment by Ambrevar** [comment]
Thanks for the list!  Would you like to send a pull request?  This is an easy fix ;)

About `^`: considering Info does not have much indentation like most source files, `^` is often equivalent to `0`.  With that in mind, we can consider `^` a free key.  `^` is used in magit and a few other special modes as way to "go up".

**Comment by jojojames** [comment]
Not sure if this is obsolete now, closing.
