### ISSUE TITLE
Info mode <mouse-1> problem

### ISSUE THREAD

**Issue by tgvaughan** [emacs-evil/evil-collection#332]
First, thanks for the amazing package!  My only gripe is that using <mouse-1> to open nodes in the info browser seems not to work, and instead results in a message

    insert-for-yank: Buffer is read-only: #<buffer *info*>

It's a strange issue, as the info mode mappings provided by evil-collection don't seem to explicitly map <mouse-1> to anything, but this behaviour it's definitely only present when evil-collection is loaded.

One thing I've noticed is that evil-collection sets the initial evil state to 'normal and adds its bindings to that state.  Changing this to 'motion (which is the default initial state for info-mode which evil uses) seems to solve the problem.

**Comment by Ambrevar** [comment]
I can reproduce.
Evil (not Evil Collection) does some strange things with Info-mode.
I tried rebinding <mouse-1> to no avail.
Any clue how to fix this issue?

**Comment by condy0919** [comment]
It have been fixed by https://github.com/emacs-evil/evil-collection/commit/b5ade1850da6b1a9499ce8e519f2639e5c4a19f3
