### ISSUE TITLE
keybind in pdf-tools's pdf-view-mode-map shadowing pdf-links-minor-mode-map

### ISSUE THREAD

**Issue by ymarco** [emacs-evil/evil-collection#333]
The `f` and `F` keybinds of `pdf-links-minor-mode` are inaccessible in `pdf-view-mode`, because in the latter they're bound in normal state ([here](https://github.com/emacs-evil/evil-collection/blob/e998952dfe73d296/modes/pdf/evil-collection-pdf.el#L140-L142)) which shadows the default no-state keymap of `pdf-links-minor-mode`.

As asked in the TODO: these keybinds aren't explicitly bound in pdf-tools, they are caused by [pdf-tools inheriting `image-mode-map`](https://github.com/politza/pdf-tools/blob/c510442ab89c8a9e9881230eeb364f4663f59e76/lisp/pdf-view.el#L271). 

The solution, I think, would be to either not bind these `image-*` commands, or provide a keymap for `pdf-links-minor-mode` as well.

**Comment by Ambrevar** [comment]
Good catch, should be fixed in 
1d42050d554590e978ec23f1e309d444f484d187.
