### ISSUE TITLE
`g r` in *Packages* (for Emacs 27)

### ISSUE THREAD

**Issue by ianpan870102** [emacs-evil/evil-collection#334]
The keybinding `g r` is widely used as buffer refresh in emacs evil. In the \*Packages\* buffer, hitting `g r` runs the command package-menu-refresh, but this function is obsolete since Emacs 27.1, and we are recommended to use the command revert-buffer instead.

**Comment by Ambrevar** [comment]
Good catch, should be fixed in 
734abad39ce4d212996f38a0052aa8179f854622.

**Comment by ianpan870102** [comment]
I can confirm that the latest update works! closing issue
