### ISSUE TITLE
Is there any way don't override ace-link setting or I should define-key by myself

### ISSUE THREAD

**Issue by tshu-w** [emacs-evil/evil-collection#340]
[ace-link](https://github.com/abo-abo/ace-link#setup) use `o` to open link in Info-mode, help-mode, woman-mode, org-mode, eww-mode, compilation-mode, goto-address-mode. I wonder if there is any way to make evil-collection not override this keybinding or I should define-key by myself.

**Comment by jojojames** [comment]
You can use https://github.com/emacs-evil/evil-collection/blob/2762b00c479ec7a34d5709e90fd1f2fa2ff07149/evil-collection.el#L291
