### ISSUE TITLE
Document general.el must load after evil/evil-collection

### ISSUE THREAD

**Issue by codygman** [emacs-evil/evil-collection#356]
For instance [this works](https://github.com/codygman/hci/actions/runs/156110056) after specifying general loads *after* evil:

```elisp
(use-package general
  :after evil
  :config
  (general-auto-unbind-keys) ;; NOTE not sure this works?
  (general-evil-setup t)
  (general-create-definer my-leader-def
    :prefix "C")
  (my-leader-def
    :states '(normal visual emacs motion)
    :prefix "SPC"
    :non-normal-prefix "M-SPC"
    "u"   '(universal-argument :which-key "Universal Argument")
    "hf" '(describe-function :which-key "Describe Function")
    "hk" '(describe-key :which-key "Describe Key")
    "ha" '(apropos-command :which-key "Apropos Command")
    )
  )

(use-package evil
  :init 
  (setq evil-want-keybinding nil
	evil-want-C-d-scroll t
	evil-want-C-u-scroll t
	evil-want-integration t
	)
  :config
  (evil-mode 1)
  :general
  (general-nmap
    :prefix "SPC"
    "wd"  delete-window
    )
  )

(use-package evil-collection
  :after evil
  :custom (evil-collection-setup-minibuffer t)
  :config
  (evil-collection-init))

```

This [does not work](https://github.com/codygman/hci/runs/832994059?check_suite_focus=true), not how `:after evil` isn't present:

```elisp
(use-package general
  :config
  (general-auto-unbind-keys) ;; NOTE not sure this works?
  (general-evil-setup t)
  (general-create-definer my-leader-def
    :prefix "C")
  (my-leader-def
    :states '(normal visual emacs motion)
    :prefix "SPC"
    :non-normal-prefix "M-SPC"
    "u"   '(universal-argument :which-key "Universal Argument")
    "hf" '(describe-function :which-key "Describe Function")
    "hk" '(describe-key :which-key "Describe Key")
    "ha" '(apropos-command :which-key "Apropos Command")
    )
  )

(use-package evil
  :init 
  (setq evil-want-keybinding nil
	evil-want-C-d-scroll t
	evil-want-C-u-scroll t
	evil-want-integration t
	)
  :config
  (evil-mode 1)
  :general
  (general-nmap
    :prefix "SPC"
    "wd"  delete-window
    )
  )

(use-package evil-collection
  :after evil
  :custom (evil-collection-setup-minibuffer t)
  :config
  (evil-collection-init))
```

**Comment by codygman** [comment]
Hm, this is slightly even more complicated. You need to set the evil-want-keybinding stuff before general initiialization because of `(general-evil-setup t)`.

Then once you get to the evil use-package block, general needs to have already been loaded.

Which means the actual solution is for general to ensure the `evil-want` functions are set that need to be set before both `evil` and `evil-collection`.

**Comment by codygman** [comment]
Nevermind... I'm still having issues I can't quite explain. Maybe I can work backwards from the solution working earlier to my full config and figure it out.

**Comment by codygman** [comment]
Okay. `use-package` doesn't support the `:general` keyword by default. The general package adds it. That means:

- general must be loaded before evil uses `:general`, ex. `(use-package evil :after general`
- `use-package general`'s block cannot use anything evil related that causes evil to load (I think)

**Comment by jojojames** [comment]
I'm not super sure how general interacts with use-package *and* evil but my guess is you'd definitely want general after evil and evil-want-keybinding to be set as early as possible.
