### ISSUE TITLE
evil-collection-setup-hook runs eagerly on lazy loaded maps

### ISSUE THREAD

**Issue by gagbo** [emacs-evil/evil-collection#368]
Hello,

## Issue

`evil-collection-setup-hook` is a great addition, it helps me a lot trying to make evil work with my french, [very non-standard layout](https://bepo.fr). Starting to use this hook, I noticed an increase in weird errors like `(void-variable dired-filter-mark-map)` and I think I found out why :

## Probable cause
Taking the `dired-filter-map` for example
`evil-collection-setup-hook` is called to run after loading `’dired` on all maps defined in the `evil-collection-dired-maps` variable  (https://github.com/emacs-evil/evil-collection/blob/master/modes/dired/evil-collection-dired.el#L37) . 

The issue is that technically, this file doesn’t `(require ’dired-filter)`, it only adds an `eval-after-load ’dired-filter` in the `evil-collection-dired-setup` function. Therefore the map is not actually loaded when `evil-collection-setup-hook` is run with `dired-filter-map` in the arguments

## Note

I think that the issue is more than "just" a `void-variable` error. Calling the hook too early like this (i.e. before `dired-filter` is loaded in this example) means that the map is actually not modified by `evil-collection-setup-hook` as expected. I think fixing this would need a slight rework either of `evil-collection-*-maps` variables or `evil-collection-setup-hook` interface (maybe both ?) and I don’t know which way to go if I ever try to patch this

**Comment by Ambrevar** [comment]
Sorry, I don't have much experience with `evil-collection-setup-hook`.  Maybe @jojojames can help you here?

**Comment by gagbo** [comment]
I was using `general-translate-key` to do the translation, but `evil-collection-translate-key` does the smart deferring to avoid this problem entirely.

Closing the issue.
