### ISSUE TITLE
Request: zmusic 

### ISSUE THREAD

**Issue by ccao001** [emacs-evil/evil-collection#376]
Hi, I would like to request [zmusic](https://hg.sr.ht/~zck/zmusic) evil keybindings.

I opened a pull request for code review.

Thank you!

**Comment by MorganJamesSmith** [comment]
@Ambrevar I think you can close this issue.

(Am I being helpful or annoying if I do stuff like this?)

**Comment by jojojames** [comment]
It's super helpful, thanks!
