### ISSUE TITLE
Request: Support xwidgets

### ISSUE THREAD

**Issue by A6GibKm** [emacs-evil/evil-collection#385]
Currently `xwidget-webkit-browse-url` on Doom Emacs starts on `evil-normal-state` (I don't know if this is the default otherwise). Making it unusable. Having support for minimal browsing would be Ok (`hjkl HJKL gg G zq ZQ q x`), for reference on sane bindings see the default keys for [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb):

![image](https://user-images.githubusercontent.com/11528996/95129565-b7f20d00-074a-11eb-8749-a355e25247f1.png)

**Comment by jojojames** [comment]
I think this would be nice. PR appreciated! (I don't yet use xwidgets.)

**Comment by A6GibKm** [comment]
I am closing this as there is already support, see https://github.com/emacs-evil/evil-collection/blob/master/modes/xwidget/evil-collection-xwidget.el. It just did not work on my setup for some reason.
