### ISSUE TITLE
image+ has been archived

### ISSUE THREAD

**Issue by tarsius** [emacs-evil/evil-collection#399]
@mhayashi1120 has archived [image+](https://github.com/mhayashi1120/Emacs-imagex). You probably should stop supporting it here. Or maybe you would like to take over as its maintainer?

Also see melpa/melpa#7225.

**Comment by jojojames** [comment]
What do you think @Ambrevar ? I'm open to removing support for it but I wouldn't be surprised if there's someone out there using a forked/copied/etc version of one.

**Comment by Ambrevar** [comment]
We are just offering bindings that get loaded for users that still use image+.
I do, so I'd like to keep the bindings :)

Maybe I misunderstood, but archiving the project only means it's no
longer maintained, does not mean it no longer works.  Or is it broken?

**Comment by tarsius** [comment]
> Or is it broken?

Not that I no off but eventually it will bit rot.
Anyways, simply keeping it, is of course another reasonable approach.
