### ISSUE TITLE
Evil Org Mode Agenda Keybindings are disabled by Evil Collection

### ISSUE THREAD

**Issue by sailikk** [emacs-evil/evil-collection#400]
Hello,
I am somewhat loosely following these dotfiles: https://github.com/hrs/dotfiles/blob/main/emacs/dot-emacs.d/configuration.org
and the configuration below seems to disable the `evil-org-mode` in org-agenda, even though they are explicitly set in the `:config` block for `evil-org-mode`. When I comment out the code for `evil-collection`, everything seems to be working fine.

For instance, with the evil-collection settings commented out, the keys `[` and `]`, which take you to the previous or next week, do work just like `evil-org-mode` defines them. With `evil-collection` enabled, however, it seems `[` and `]` are no longer defined? Not sure why this is happening. I am still a beginner in Emacs, so let me know if there is something that should be added.

```lisp
(use-package evil
  :init
  (setq evil-want-abbrev-expand-on-insert-exit nil
        evil-want-keybinding nil)

  :config
  (evil-mode 1))

;; Install evil-collection, which provides evil-friendly bindings for many modes.

(use-package evil-collection
  :after evil
  :config
  (setq evil-collection-mode-list
        '(ag dired magit mu4e which-key))
  (evil-collection-init))
;; Enable surround everywhere.

(use-package evil-surround
  :config
  (global-evil-surround-mode 1))
;; Use evil with Org agendas.

(use-package evil-org
  :after org
  :config
  (add-hook 'org-mode-hook 'evil-org-mode)
  (add-hook 'evil-org-mode-hook
            (lambda () (evil-org-set-key-theme)))
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))
```

**Comment by jojojames** [comment]
If you do C-h k, what does it say?

I believe evil-collection binds [ ] for unimpaired style bindings.

**Comment by sailikk** [comment]
![image](https://user-images.githubusercontent.com/46624965/99134673-c3a7dd80-25ec-11eb-95cb-f5c76f213b64.png)
Same thing happens for `[`..

Not sure what you mean by unimpaired style bindings, I've never used `vim-unimpaired` in Vim if that is what you are asking for. Would disabling these fix the problem? How would you disable them?

**Comment by jojojames** [comment]
Try disabling: https://github.com/emacs-evil/evil-collection/blob/8c256263ad100fecd6246c6c55cbb19dab717c39/evil-collection.el#L113

**Comment by sailikk** [comment]
I have absolutely zero experience in Emacs lisp at the moment, but this is what I have done:
```lisp
(use-package evil-collection
  :after evil
  :config
  (setq evil-collection-mode-list
        '(ag dired magit mu4e which-key)
        evil-collection-want-unimpaired-p nil)
  (evil-collection-init))
```
This seems to be working. Thank you for the help and feel free to close unless I'm doing something terribly wrong that would break other functionality.

**Comment by jojojames** [comment]
Nice.

**Comment by Ambrevar** [comment]
I was also bitten by this some time ago ;)
