### ISSUE TITLE
S-SPC / S-DEL keybindings in magit-mode-map shadow "S" binding

### ISSUE THREAD

**Issue by nmk** [emacs-evil/evil-collection#406]
Hello,

I was using evil-magit without any special mappings or customization. With it "S" (capital s) was bound to `magit-stage-modified`. After installing the new evil-collection from Melpa (and removing evil-magit), "S" seems to be a perfix key, with "S-SPC" (capital s, dash, capital s, capital p, capital c) and "S-DEL" (ditto) defined. Here is what `C-h k` tells me about "S-SPC":
```
S - S P C runs the command magit-diff-show-or-scroll-up, which is an interactive native
compiled Lisp function in ‘magit-diff.el’.

It is bound to S - S P C, <visual-state> S - S P C, <normal-state> S - S P C.

(magit-diff-show-or-scroll-up)
```
I think this is related to https://github.com/emacs-evil/evil-collection/blob/master/modes/magit/evil-collection-magit.el#L293-L294 with the two keymaps defined there being parsed not as intended.

Do you have an idea how I can debug this?

Best,
Nickolay

**Comment by jojojames** [comment]
Thanks for the detailed report as well as initial debugging. Always appreciated.

Does https://github.com/emacs-evil/evil-collection/commit/2cf81f91ea97097451bfd40dd6351338d190a64c work for you?

**Comment by nmk** [comment]
Yep, that commit fixes the problem I was seeing. Thanks for looking into this!
