### ISSUE TITLE
evil-collection-define-key: Symbol’s function definition is void: notmuch-tree-close-message-pane-and

### ISSUE THREAD

**Issue by firmart** [emacs-evil/evil-collection#415]
The function `notmuch-tree-close-message-pane-and` no longer exists in recent version of `notmuch`.
Tested under notmuch version: 0.29.3 and package of 2020.12.06

**Comment by firmart** [comment]
First occurrence here.

https://github.com/emacs-evil/evil-collection/blob/c9ccc3065f46c1654f1cc0d41cd2f5cff184d273/modes/notmuch/evil-collection-notmuch.el#L39

**Comment by jojojames** [comment]
Please PR.

**Comment by firmart** [comment]
Sure. I'll try to, but it will take some time.

**Comment by ZenTauro** [comment]
The issue has been solved in this PR: https://github.com/emacs-evil/evil-collection/pull/417

However, for some reason, it is not passing the CI, but in my setup it passes
