### ISSUE TITLE
evil-collection makes dired useless

### ISSUE THREAD

**Issue by pozzo-balbi** [emacs-evil/evil-collection#425]
Emacs comes with its own file manager built-in, Dired. Dired is just an Emacs major mode that displays files in a buffer in an ls -l like manner, and comes with its own set of functions with their key bindings made for manipulating files and directories in this buffer.

A few key bindings include d (dired-flag-file-deletion), C (dired-do-copy), and L (dired-do-load). However, evil-collection rebinds all these bindings to the default vim editing commands. And the problem is that Dired wasn't made for editing files, but for viewing and manipulating files and directories on the file system, and rebinding all Dired's default bindings to editing commands makes it unusable.

I use use-package to load evil-collection. 
``` elisp
(use-package evil-collection
  :load-path "~/path/to/evil-collection"
  :after evil
  :config
  (evil-collection-init))
```
And I did try a work-around, in which I customized the variable evil-collection-mode-list and DELeted every entry that had the word 'dired'. However that hardly changed anything.

I use Emacs 27.1.

**Comment by jojojames** [comment]
Do you have better examples? All of those keys you mentioned works for me as expected.

> A few key bindings include d (dired-flag-file-deletion), C (dired-do-copy), and L (dired-do-load).

Are all mapped by evil-collection. 
https://github.com/emacs-evil/evil-collection/blob/f410043aa773cea0bab6e4ae437877413550c93c/modes/dired/evil-collection-dired.el#L57
https://github.com/emacs-evil/evil-collection/blob/f410043aa773cea0bab6e4ae437877413550c93c/modes/dired/evil-collection-dired.el#L55
https://github.com/emacs-evil/evil-collection/blob/f410043aa773cea0bab6e4ae437877413550c93c/modes/dired/evil-collection-dired.el#L60

> And I did try a work-around, in which I customized the variable evil-collection-mode-list and DELeted every entry that had the word 'dired'. However that hardly changed anything.

I'm assuming you've made some mistakes somewhere in your config.

Here are steps you can take to resolve your issue.
1. Figure out why your workaround doesn't do what you want.
2. Post a repro from a clean init.el
3. Bisect your config and see where the configuration issue is.
