### ISSUE TITLE
Stepping down as maintainer

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil-collection#436]
Hello, dear Evil community :)

After co-maintaining Evil Collection for a few years, time has come for me to step down from my role! :)

I've been less involved in the project over the past few months and other contributors have proven to be more active than me, so maybe now is a good time to be looking for new comaintainers!

What do you think, @jojojames?

**Comment by jojojames** [comment]
Thanks @Ambrevar for your contributions over the years! Sad to see you go and always welcome back, of course.

> maybe now is a good time to be looking for new comaintainers!

That's a good idea to me, any interested volunteers (e.g. @condy0919 , etc), feel free to chime in. Otherwise I'll hold down the forte for the time being. :)

**Comment by Ambrevar** [comment]
Thank you back! :)

I'll unwatch this repo to relieve my mailbox a bit, but feel free to
contact me directly if you need anything (such as a question on code I
wrote :p).

Good luck!

**Comment by condy0919** [comment]
I'm in, glad to co-maintain evil-collection :-)

**Comment by jojojames** [comment]
@condy0919 

Off the top of my head I don't know if I can invite you to the org.

@TheBB may have to be the one to invite you.

**Comment by TheBB** [comment]
Yes, me or @wasamasa, but I think you can add collaborators to the repo without first adding them to the organization. But I just did that for you, @condy0919 so you should get an invite by mail shortly.

**Comment by jojojames** [comment]
> but I think you can add collaborators to the repo without first adding them to the organization. 

I think I lost that ability when moving it to the organization (at least the settings tab where I can invite collaborators is gone) for this repo.

> just did that for you, @condy0919 so you should get an invite by mail shortly.

Thanks!

**Comment by TheBB** [comment]
Ah yeah, I see you don't have admin level. I promoted you as well.

**Comment by jojojames** [comment]
Nice, thanks @TheBB !

**Comment by jojojames** [comment]
Thanks again @Ambrevar !! Closing this now, feel free to reach out if you're ever interested in coming back and helping. :)

**Comment by Ambrevar** [comment]
And thank you tons for keeping up with maintenance! :)
