### ISSUE TITLE
blacklist seems not to work with magit

### ISSUE THREAD

**Issue by Vonfry** [emacs-evil/evil-collection#438]
The blacklist can work with other mode, but in magit it has the same behavior when using without blacklist.

My blacklist contains two keys `SPC` and `S-SPC`. The magit only binded `S-SPC` in evil. But the `SPC` also cannot work and `S-SPC` is the same behavior defined in magit instead of undefined.

`describe-bindings` showed all keys with `SPC` prefix which is not listed in `describe-mode` in `magit-status`

I tried to run `evil-normalize-keymaps` in magit-status buffer, and it was no effect. 

***reproduciable code***

`emacs -q`:

```
(require 'general)
(general-evil-setup t t)

(setq-default evil-want-keybinding nil
	      evil-want-integration t
	      evil-collection-key-blacklist '("SPC" "S-SPC")
	      git-path "~/dotfiles")
(require 'evil)
(require 'evil-collection)
(require 'magit)

(evil-mode)
(evil-collection-init)

(nmap :prefix "SPC" "b" 'switch-to-buffer)

(magit-status git-path)

```

**Comment by jojojames** [comment]
You should provide code you've used to get to this state (either snippets or a reproducible emacs -q)

It shouldn't be too bad to debug this:

The part where it checks the blacklist is here:

https://github.com/emacs-evil/evil-collection/blob/e7be9f53a05c81ef9e89c2f053ba62048e6afd69/evil-collection.el#L337

The part where we're looping over the magit keys is here:

https://github.com/emacs-evil/evil-collection/blob/e7be9f53a05c81ef9e89c2f053ba62048e6afd69/modes/magit/evil-collection-magit.el#L372

and one of the SPC related keybindings is here:

https://github.com/emacs-evil/evil-collection/blob/e7be9f53a05c81ef9e89c2f053ba62048e6afd69/modes/magit/evil-collection-magit.el#L296

Having said that, there's a few spots where we should convert evil-define-key to evil-collection-define-key in that file.

**Comment by Vonfry** [comment]
A reproduciable code with `emacs -q`:

```
(require 'general)
(general-evil-setup t t)

(setq-default evil-want-keybinding nil
	      evil-want-integration t
	      evil-collection-key-blacklist '("SPC" "S-SPC")
	      git-path "~/dotfiles")
(require 'evil)
(require 'evil-collection)
(require 'magit)

(evil-mode)
(evil-collection-init)

(nmap :prefix "SPC" "b" 'switch-to-buffer)

(magit-status git-path)

```

**Comment by jojojames** [comment]
Why are you requiring magit?

```
(require 'magit)
```

**Comment by jojojames** [comment]
Scratch that^(deleted)

I think you'll have to check "SPC" against the definition in evil-magit, I think it's using either KBD or \.

**Comment by Vonfry** [comment]
I found the reason. It is caused by magit bind `SPC` in a major mode map, which has higher precedence than evil global mode map.

I add these to fix the problem.

```
(general-unbind 'normal magit-mode-map
    :with 'ignore
    [remap magit-diff-show-or-scroll-up]
    [remap magit-diff-show-or-scroll-down])
```

Sorry to disturb.

**Comment by Vonfry** [comment]
Furthormore, it is to code magit-mode-map with `evil-make-overriding-map` in evil-collection.

https://github.com/emacs-evil/evil-collection/blob/f53ef08224f709c732740d45b373ef3617f6d759/modes/magit/evil-collection-magit.el#L405-L419
