### ISSUE TITLE
Inhibiting company completions

### ISSUE THREAD

**Issue by Randy1Burrell** [emacs-evil/evil-collection#451]
I have a tiny problem while using this package. Whenever installed, it to inhibits company completions and I get the message `No completion found` whenever evil-mode is disabled. Once this package is deleted and I switch between evil-mode and normal emacs then company-mode works fine.

Here's my current configuration:

```emacs-lisp
(setq evil-want-keybinding nil)

(use-package evil
  :bind ("<C-tab>" . 'evil-mode))
  
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))


```

I know it is not a critical bug, but it's super annoying given the fact that I switch between evil and normal emacs quite often. Anyone have any idea where I am going wrong?

**Comment by condy0919** [comment]
What's your major mode and what's the version of evil-collection/company-mode?

Does upgrade solve it?

**Comment by jojojames** [comment]
Can you provide an emacs -Q recipe?

Alternatively, take a look at https://github.com/emacs-evil/evil-collection/blob/master/modes/company/evil-collection-company.el and see what's messing you up.

Alternatively, disable the company integration.

> whenever evil-mode is disabled. Once this package is deleted and I switch between evil-mode and normal emacs then company-mode works fine.

FWIW, I'm not sure how supported this use case is.

**Comment by Randy1Burrell** [comment]
Hey guys, thanks for your speedy response.

@condy0919 I am using the latest versions of the packages. 

@jojojames Thanks, I sent a PR.
