### ISSUE TITLE
Feature-proposal: github discussion

### ISSUE THREAD

**Issue by dalanicolai** [emacs-evil/evil-collection#457]
Could it be a good idea to enable [the new github discussions feature](https://docs.github.com/en/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository#enabling-or-disabling-discussions-for-your-repository)?

I came here because Spacemacs recently started using this package and I noticed that I can not (by default) page through the Info pages using `[` `]` anymore (and some more changes). Of course I could simply add these bindings back for me personally, but I like the idea of this project and I would be happy to help adding.discussing keybindings here.

I guess such discussions will be more frequent so that this new feature might come in handy.

Anyway, for now I will open an issue to report/discuss some Spacemacs Info mode keybinding issues.

**Comment by jojojames** [comment]
Turned it on, was not aware of that sort of feature. Thanks for raising the issue.
