### ISSUE TITLE
Compant-tng-mode with latest evil-collection

### ISSUE THREAD

**Issue by jotsif** [emacs-evil/evil-collection#459]
Hi guys!

With the Evil Collection release `20210209.629` I get the following error when starting Emacs.

```
Error (use-package): elpy/:init: Symbol’s function definition is void: company-tng-mode
Error (use-package): company/:catch: Symbol’s function definition is void: company-tng-mode
```

I think this is due to this change https://github.com/emacs-evil/evil-collection/commit/2cce30225bdfd5304e0368e99cfd83ea132269c8#diff-5eb071f47ad97b03a0c208fe55154995bbcd539ad70ccaaa5a0b9c38c51e8bd5R96

But I am not sure how to handle it. Any help is appreciated!

**Comment by jojojames** [comment]
You can upgrade your company-mode.

https://github.com/company-mode/company-mode/commit/c1e8972950c20c80d4818adcc44f8a91d8f9d82a#diff-2dbaa2d743204b74e90cdd9df2fde6fc8bc6f4364e127fe9ac0ae8aac8943439

**Comment by jotsif** [comment]
Great. Worked. Thanks for an amazingly fast answer 💯

**Comment by herbertjones** [comment]
The current pre-release version of company has changes that are breaking 3rd party packages like helm-company and company-box.  You'll have to use an older version of evil-collection before [2cce302](https://github.com/emacs-evil/evil-collection/commit/2cce30225bdfd5304e0368e99cfd83ea132269c8#diff-5eb071f47ad97b03a0c208fe55154995bbcd539ad70ccaaa5a0b9c38c51e8bd5R96) if you don't want to use a pre-release of company and potentially break your emacs if you are using 3rd party company packages also.
