### ISSUE TITLE
C programming tag solution (gtags ? cscope ?) compatible with evil-jumps C-o C-i

### ISSUE THREAD

**Issue by Rehan-MALAK** [emacs-evil/evil-collection#460]
Hi, 

Is there currently a working configuration for C source files (gtags ? cscope ? xcscope ? helm ?) compatible with evil-jumps ``C-o``  ``evil-jump-backward`` and ``C-i`` ``evil-jump-forward``

I had some success with other languages with the ``(evil-set-command-property #'my-lang-specific-go-to-definition-function :jump t)`` technique but not with C source files

Thanks !

**Comment by jojojames** [comment]
> Is there currently a working configuration for C source files (gtags ? cscope ? xcscope ? helm ?) compatible with evil-jumps C-o evil-jump-backward and C-i evil-jump-forward

I believe you'll want to PR any missing support. Not sure which ones we're missing out of that list. It may be as simple as setting that command property as you said.

**Comment by Rehan-MALAK** [comment]
No, I mean I have not been able to make it work with

``(evil-set-command-property #'helm-gtags-dwim :jump t)``
nor with
``(evil-set-command-property #'cscope-find-global-definition-no-prompt :jump t)``
nor with
``(evil-set-command-property #'helm-cscope-find-global-definition-no-prompt :jump t)``

with a emacs 27 fresh install and minimal configuration for evil-collection + one of these tag engine
