### ISSUE TITLE
More explanation about the effect of setting `evil-want-keybinding` to nil

### ISSUE THREAD

**Issue by blahgeek** [emacs-evil/evil-collection#462]
According to the readme, I need to set `evil-want-integration` to `t` and `evil-want-keybinding` to `nil` to use evil-collection. However, I find it unclear what's the effect of doing it.

Does it change something that evil already provides? Does it completely remove evil keybindings? Does it means that evil-collection replaces evil in some modes (which modes?)? Do I need to set them if I'm only going to enable evil-collection for some of the modes (using evil-collection-mode-list)?

Neither the document of these variables or the linked issue have any direct answer. I think this is the one reason that always kept me from trying evil-collection: I don't like surprises and I just don't want it to mess up with my currently satisfying evil setup. I think it would be better to provide a more details explanation in the README about this.

**Comment by jojojames** [comment]
> Neither the document of these variables or the linked issue have any direct answer. 

I do agree these settings are a little sparsely documented but I don't agree about your conclusion that the combined documentation of the variables and linked issues aren't enough to answer your questions. 

Just ignoring the linked issues (which provides more context, etc on the reason for removal), we can just look at the documentation of the variables themselves.

```
(defcustom evil-want-integration t
  "Whether to load evil-integration.el.
This variable must be set before Evil is loaded."
  :type 'boolean
  :group 'evil)

(defcustom evil-want-keybinding t
  "Whether to load evil-keybindings.el.

This loads a set of keybindings for evil in other modes as well as
setting the initial evil state in those modes.

This variable must be set before evil is loaded."
  :type 'boolean
  :group 'evil)

```

You can then follow the crumbtrails and figure out what evil-keybindings and evil-integrations are doing and what the implications of removing them are.

Having said that, open to better documentation here, but won't do it myself.
