### ISSUE TITLE
Magit error transient-suffix-put is void

### ISSUE THREAD

**Issue by iuvenis** [emacs-evil/evil-collection#467]
Running `M-x magit-version` gives me the error message

`Symbol's function definition is void: transient-suffix-put`.

When using magit via `magit-status` it doesn't use the evil-collection bindings, running in Emacs-mode (`<E>`) instead. If I try to commit something, I get the above error message again as soon as magit attempts to open a buffer to enter the commit message.
All of this works fine if I do not initialize evil-collection (calling evil-collection-init).

I am running magit 2.90.1, evil 1.14.0, evil-collection 0.0.5. I installed all of them via MELPA.

Here's my minimal emacs initialization file:
```
(setq evil-want-keybinding nil)
(setq evil-want-integration t)
(evil-collection-init)
(evil-mode 1)
```

I noticed that the instructions on the magit.vc homepage say that the transient package is required when installing from the git repository, yet MELPA did not install it as a dependency for me. Manually installing transient from MELPA and adding `(require 'transient)` before `(evil-collection-init)` gives me the error message `magit-branch is not a transient command` instead when running `magit-version`.

Am I doing something wrong?

**Comment by jojojames** [comment]
Can you provide a minimal emacs -Q recipe? e.g.

```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

;; Your repro here..
```

I am guessing there're some mixups between MELPA and MELPA-stable on your end.

**Comment by iuvenis** [comment]
I appended my minimal initialization file to your recipe, loaded the file after starting `emacs -Q` and got the same error that I described above.
Here is the full initialization file I loaded:

```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(setq evil-want-keybinding nil)
(setq evil-want-integration t)
(evil-collection-init)
(evil-mode 1)

;; now provoke the error message
(magit-version)
```
I indeed installed my packages from MELPA-stable rather than MELPA I believe. Could that somehow be causing the problem? Should I try reinstalling from MELPA instead?

**Comment by iuvenis** [comment]
I looked up the usage of `use-package`, which I haven't used so far, and now everything works with an init file like this:

```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package evil-collection
  :init
  (setq evil-want-keybinding nil)
  (setq evil-want-integration t)
  (setq evil-collection-company-use-tng nil)
  :config
  (evil-collection-init))

(use-package evil
  :config
  (evil-mode 1))

(use-package magit)
```

use-package installed a different version of magit. `magit-version` now returns `Magit 20210406.454` rather than `Magit 2.90.1`. I still don't understand why my setup without use-package didn't work but I guess my problem is solved, thank you!

I'll just keep the issue open for a little while longer in case you would like to add some explanation of what was going wrong to round the issue off.
