### ISSUE TITLE
evil-magit rebase instructions are improperly formated with `%` commentChar

### ISSUE THREAD

**Issue by nacl** [emacs-evil/evil-collection#468]
When rebasing with git `core.commentChar` set to `%`, the magit rebase buffer command descriptions will look something like this:

```
% Commands:
%-8s p
%-8s r
%-8s e
%-8s s
...
```

Whereas with a different comment character (e.g. `@`), they look like this (as expected):

```
@ Commands:
@ p        pick = use commit
@ r        reword = use commit, but edit the commit message
@ e        edit = use commit, but stop for amending
@ s        squash = use commit, but meld into previous commit
...
```

The culprit looks to be [here](https://github.com/emacs-evil/evil-collection/blob/master/modes/magit/evil-collection-magit.el#L511).

A potential solution would be to have `comment-start` be an argument to `format`, rather than be prepended to the format string directly.

**Comment by jojojames** [comment]
Sounds reasonable, since you went through the trouble already, a PR would be much appreciated!

**Comment by nacl** [comment]
I'd be happy to submit a PR, but I will need to get some approvals from my employer first.  Hopefully they'll be done by Friday.
