### ISSUE TITLE
Testing org-preset bindings

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#469]
Hi,

Can someone test out the org-present bindings? 

They do not work for me when I turn on all evil-collection modes. 

Do they work for you?

Thanks!

**Comment by condy0919** [comment]
@jgarte test it again.

**Comment by jgarte** [comment]
@condy0919 It looks like [1fb8a2ab2ec](https://github.com/emacs-evil/evil-collection/commit/1fb8a2ab2ec22c1c943c40250462bc8718bd6c78) fixed it. Thank you!
