### ISSUE TITLE
Add pacmacs

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#472]
https://github.com/codingteam/pacmacs.el

# Controls in the `*Pacman*` buffer.

1. `k` — move Pacman up;
2. `j` — move Pacman down;
3. `h` — move Pacman left;
4. `l` — move Pacman right;
5. `q` — quit the game;
6. `SPC` — pause the game.

**Comment by condy0919** [comment]
Sorry I don't play pacman in Emacs. Could you submit a patch for it ?

**Comment by jgarte** [comment]
Hi @condy0919,

Give me a few days and I'll submit a patch.

Till soon.

**Comment by pspiagicw** [comment]
@jgarte can I take this one ?

**Comment by jojojames** [comment]
@pspiagicw Please do.
