### ISSUE TITLE
How to make SPC behave as global leader key in help-mode?

### ISSUE THREAD

**Issue by ezchi** [emacs-evil/evil-collection#478]
`SPC` is mapped to `scroll-up-command` in help-mode. Is there any way to unbind it and make it behave as global leader key?

**Comment by jojojames** [comment]
Yes, I recommend reading the README to get your answer.

**Comment by tonijarjour** [comment]
For anyone reading this in the future:
`(setq evil-collection-key-blacklist '("SPC"))`
