### ISSUE TITLE
Possible error in `evil-collection-translate-key`

### ISSUE THREAD

**Issue by lebensterben** [emacs-evil/evil-collection#481]
`evil-delay` takes 3 required args and 3 optional args:
```elisp
(evil-delay CONDITION FORM HOOK &optional APPEND LOCAL NAME)
```

But here 7 arguments are supplied to `evil-delay` https://github.com/emacs-evil/evil-collection/blob/d6107b2c8ee063fa6252853385e617cac37f4ee5/evil-collection.el#L613-L619

It seems to me that `LOCAL` is supplied twice (`t` and `nil`).

**Comment by condy0919** [comment]
The fourth is `t`, the fifth is `nil` and the sixth is `(symbol-name ...)`. What's wrong?

**Comment by lebensterben** [comment]
my bad. I worked too many hour yesterday.
