### ISSUE TITLE
Cannot disable keys for outline-minor-mode

### ISSUE THREAD

**Issue by nettoyoussef** [emacs-evil/evil-collection#485]
Dear all, 

First, thanks for the awesome package. I use it at all times and is paramount for a nice vim experience on emacs.

In the documentation, motivated by #426, it is described that particular keys from the outline-minor-mode can be disabled using:

```lisp
  (evil-define-minor-mode-key 'normal 'outline-mode-map "gj" nil)
```

Well, I tried altering the "gj" and "gk" behavior in several ways but I was not successful:

```lisp

(use-package evil-collection
  :after evil
  :custom (evil-collection-setup-minibuffer t)
  :bind
  (
  ;; preserve normal functioning of gj and gk on org buffers (evil-collection alters it)
 ;; tried using straight - didn't work
  :map  outline-minor-mode
  ("g-j," . 'evil-next-visual-line)
  ("g-k," . 'evil-previous-visual-line)
  :map evil-visual-state-map
  ("g-j," . 'evil-next-visual-line)
  ("g-k," . 'evil-previous-visual-line)
  )
  :config
  (evil-collection-init)
 
  ;; tried using the official documentation - didn't work
  ;; altering the order to before the init command did not have any impact
  ;; adding an hyphen "-" between keys also did not work
  (evil-define-minor-mode-key 'normal 'outline-mode-map "gj" nil)
  (evil-define-minor-mode-key 'normal 'outline-minor-mode "gk" 'evil-previous-visual-line)
  (evil-define-minor-mode-key 'visual 'outline-minor-mode "gj" 'evil-next-visual-line)
  (evil-define-minor-mode-key 'visual 'outline-minor-mode "gk" 'evil-previous-visual-line)

  ;; tried altering the global mode - didn't work
  (evil-define-key 'normal 'global "gj" 'evil-next-visual-line)
)
```

The only thing that works is commenting the lines on the file `evil-collection-outline.el`:
```lisp
    ;;"gk" 'outline-backward-same-level
    ;;"gj" 'outline-forward-same-level
```

Honestly, in my opinion, I feel that `gj`, `gk` should not be altered from normal vim usage. 

The evil package already define those keys with `evil-next-line` and `evil-previous-line`, and third packages such as evil-org have `C-j` and `C-k` for moving between objects in the same level (`org-forward-heading-same-level` etc).
The keymap configuration on the outline mode seems redundant, and a bit intrusive in this case.

**Comment by jojojames** [comment]
Have you tried disabling it through the blacklist?

**Comment by nettoyoussef** [comment]
Not sure how I would do that. Would you provide some examples?

**Comment by jojojames** [comment]
Should be here: https://github.com/emacs-evil/evil-collection/blob/b1c37b8ad06eeec21d05e7201fa56f946bc361bf/evil-collection.el#L321
