### ISSUE TITLE
use xref functionality in go-mode

### ISSUE THREAD

**Issue by fgeller** [emacs-evil/evil-collection#489]
Hi, thanks for this extensive collection!

I'd like to use xref- functionality rather than godef bindings as provided by default for go-mode.
What's the recommended way of doing this?

Thank you for your time!

**Comment by jojojames** [comment]
You should be able to rebind the key to your preferred function after evil-collection loads. Or remove go-mode from the list of supported evil-collection mode and bind keys that way.

**Comment by fgeller** [comment]
Added the `evil-collection-define-key` to a hook I run when opening Go files, that seems to do it. Would prefer to do this just once, but it works for me -- so closing the issue. Thanks!
