### ISSUE TITLE
Can't repeat searches using n/N in magit-blame

### ISSUE THREAD

**Issue by Deewiant** [emacs-evil/evil-collection#502]
In `magit-blame`, `n` and `N` don't work for searching but rather are bound to `magit-blame-next-chunk` and `magit-blame-next-chunk-same-commit` respectively.

Should be easy to reproduce using `magit-blame` but just to confirm here are from-scratch reproduction instructions anyway, starting in a terminal:

```sh
$ mkdir test
$ cd test
$ git init
$ cat > file
(package-initialize)
(setq evil-want-keybinding nil)
(require 'evil)
(evil-mode 1)
(require 'evil-collection)
(evil-collection-magit-setup)
(require 'magit)
$ git add file && git commit -m example
$ emacs -Q -l file file
```

And then in emacs:

```elisp
M-x magit-blame-addition
/evil<RET>
n
N
```

Observe that `n` doesn't repeat the search, and similarly for `N`.

For now I have this kind of workaround in my `init.el`, which seems to do the trick:

```elisp
(evil-collection-define-key 'normal 'magit-blame-read-only-mode-map "n" 'evil-search-next)
(evil-collection-define-key 'normal 'magit-blame-read-only-mode-map "N" 'evil-search-previous)
```

But this seems like something that `evil-collection` itself should handle. There are already alternate bindings for the original `n` and `N` behaviours — `gj` and `gJ` respectively — so perhaps this is just an oversight. (On the other hand, the readme doesn't mention either `n` or `N` in the guidelines section.)

**Comment by condy0919** [comment]
Yes, you're right..

**Comment by condy0919** [comment]
Fixed, try it again.

**Comment by Deewiant** [comment]
Thanks, it works!
