### ISSUE TITLE
Evil-collection bindings for magit-repolist-mode don't work until magit is fully loaded

### ISSUE THREAD

**Issue by fredericgiquel** [emacs-evil/evil-collection#510]
## What happened?

In my Emacs configuration, I defer the loading of `magit` with `use-package` (very common practice). If I open the magit repositories buffer (with `magit-list-repositorities` command) just after the launch of Emacs, here is the situation :
- the evil state of the buffer is `normal` (instead of `motion`)
- `<RET>` is bound to `evil-ret` (and not to `magit-repolist-status`)

I must first use `magit-status` with a git repo to have the intended bindings for `magit-repolist-mode`.

## Steps to reproduce

I tried to make a minimal init.el to reproduce the problem :
```emacs-lisp
;; Initialize package sources
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

;; Evil + evil-collection
(use-package evil
  :init
  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

;; Deferred load of magit
(use-package magit
  :init
  (setq magit-repository-directories '(("~/.emacs.d" 0)))
  :bind ("C-x g" . magit-status))
```
2 important things to note :
- the `magit-repository-directories` must be initialized with a correct value. I used "~/.emacs.d" just for the example (and because it's a git repo for many Emacs users).
- the `:bind ("C-x g" . magit-status)` line is very important. Without it, the package load is not deferred and the problem does not occur.

Action to do : Launch Emacs with this init file and do `M-x magit-list-repositorities` (before anything else)

## Other informations

The problem can be reproduced either with melpa packages or with last versions from git repositories (using straight.el).

**Comment by fredericgiquel** [comment]
I solved the problem in my configuration by adding `(with-eval-after-load 'magit-repos (evil-collection-magit-setup))` or `(add-to-list 'evil-collection-mode-list '(magit magit-repos))` before `(evil-collection-init)`.

Maybe something similar can be integrated directly into the package to solve the problem for everyone.

**Comment by jojojames** [comment]
Thanks for the report and the solution, updated.
