### ISSUE TITLE
Smerge bindings

### ISSUE THREAD

**Issue by dieggsy** [emacs-evil/evil-collection#519]
It'd be nice to have smerge bindings.

Maybe this would be useful for inspiration? https://github.com/syl20bnr/spacemacs/issues/7378

**Comment by condy0919** [comment]
Welcome to PR :-)

**Comment by dieggsy** [comment]
Sure thing, I've made one before. Just have to find the time, like anyone. No worries.

**Comment by pspiagicw** [comment]
Has this been done ? Can I take it ?

**Comment by jojojames** [comment]
Don't think so and feel free.

**Comment by pspiagicw** [comment]
Should be closed now.
