### ISSUE TITLE
Accessing arguments in magit revert

### ISSUE THREAD

**Issue by siddharthshekar** [emacs-evil/evil-collection#524]
The actions under Magit's revert menu (bound to `_`) are `_` for reverting the commit and `-` for reverting changes. However, the `-` also seems to clash with the modifier that's needed to access the arguments (see screenshot below for details). Is there some alternative way to access the arguments in the menu?

<img width="464" alt="image" src="https://user-images.githubusercontent.com/1447996/131029235-aa8272a6-44c3-4869-b99b-f592d4117a72.png">

**Comment by jojojames** [comment]
Think we may want to move - to another key to avoid this conflict, any suggestions? @siddharthshekar @condy0919

**Comment by siddharthshekar** [comment]
`R` doesn't seem to be bound at the top level, so perhaps we could use that?

**Comment by jojojames** [comment]
Might be a little weird since one will be _ and another will be R but that might be ok... PR welcome and we can discuss further.
