### ISSUE TITLE
`\` and `gg` not mapped during magit interactive rebase

### ISSUE THREAD

**Issue by BlueDrink9** [emacs-evil/evil-collection#525]
When in magit-rebase, gg is undefined, and `\` does not enter text mode. That's a real nuisance, since I'd love to be able to delete a commit at the top of a long list and quickly move it to the bottom, without pressing `10gj` and hoping I counted correctly.

Is this expected behaviour or has my config got a bug? (If expected, then please treat this as a humble feature request)

**Comment by jojojames** [comment]
Please provide an emacs -Q recipe.

**Comment by BlueDrink9** [comment]
I'm not experienced enough with emacs to know what that means or how to do it. I see from searching that you want a reproduction without any customisation? But I am using doom emacs, so I don't have any packages under `emacs -Q`. I can't find any explanation about the "recipe" part of your request. If you're willing to help explain a little more, I'd appreciate it.

Before I go through that effort (and I am happy to put in effort, don't mistake me for a help vampire) I would like an answer to my first question: is evil-collection expected to work when editing an interactive rebase list?

**Comment by jojojames** [comment]
You start up emacs with -Q so everything is blank from the start. Then you reproduce the list of steps it takes to produce the behavior you're seeing.

```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

```

Will probably get you to the point where your emacs starts up and installs use-package.

**Comment by BlueDrink9** [comment]
Thank you. Are you able to answer my question about whether this behaviour is expected?

**Comment by BlueDrink9** [comment]
I see the issue was not that evil-collection wasn't active, just that these two maps don't do what I would expect.
The rebase is already a text-mode (insert-state is possible), so I can understand why `\` doesn't do what I would expect it to. However it would be desirable to have a way to temporarily override magit mappings to edit the buffer as if it were normal evil text.

I am still unsure about whether `gg` not jumping to the top is expected behavior.

**Comment by BlueDrink9** [comment]
My `emacs -Q` reproduction failed to reproduce the issue. I will have a closer look at my packages/submit a doom issue.

```elisp
(load-file "~/.emacs.d/straight/repos/straight.el/bootstrap.el")
(straight-use-package 'evil)
(straight-use-package 'evil-collection)
(straight-use-package 'magit)
(setq evil-want-integration t)
(setq evil-want-keybinding nil)
(evil-mode)
(evil-collection-init)
```

I will also open a feature request for `\` to do the expected thing
