### ISSUE TITLE
mu4e: mu4e-maildir-shortcuts not accessible, because they start with j, which is bound to next-line

### ISSUE THREAD

**Issue by japhir** [emacs-evil/evil-collection#528]
I've set some maildir-shortcuts in my [mu4e config](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#mu4e) but cannot access them, as by default the keys are appended to the <kbd>j</kbd> key (for jump?) and this is bound to next-line.

To reproduce: set some keybinds to maildirs with
``` emacs-lisp
 (setq mu4e-maildir-shortcuts
          '(("/inbox" . ?i))
```
M-x mu4e
hit j i to try to go to the inbox maildir
it just moves to the next line.

**Comment by condy0919** [comment]
`J` is used for jump, although evil-collection hasn't updated the menu for some reason.

**Comment by japhir** [comment]
Yes, <kbd>J</kbd> is jump, but if I go to the mu4e-main view, there is a list of Maildirs with the shortcuts from mu4e-maildir-shortcuts, that all have e.g. <kbd>j</kbd><kbd>i</kbd> listed as shortcuts for the above inbox.

**Comment by PRESFIL** [comment]
I'll add my couple of cents: the shortcut-list does not visually update on context switch,
although if you re-login to `mu4e` it does.

Even though it is possible to add new region for this, it is not clear how to call this on a context switch.

**Comment by PRESFIL** [comment]
#668 reopens this issue
