### ISSUE TITLE
evil-collection-consult is over-eager when loading Org

### ISSUE THREAD

**Issue by tecosaur** [emacs-evil/evil-collection#539]
Currently, loading `evil-collection-consult` eagerly loads `consult-org`, which of course loads `org`. This isn't necessary, and adds a few-second pause before I can open recent files. It also seems to eagerly load `consult-imenu`, which isn't necessarily needed at this point either. If it would be possible to defer loading of these features until they are actually needed, (from a quick test) that would virtually eliminate the delay before I can open a recent file.

**Comment by condy0919** [comment]
Seems like

```
consult-outline
consult-mark
consult-imenu
consult-org-heading
consult-line
```

are all `autoload`ed.

**Comment by tecosaur** [comment]
Could have fooled me.
https://github.com/emacs-evil/evil-collection/blob/14f175397928f7c82d2035ce95a31163907637c6/modes/consult/evil-collection-consult.el#L32-L33
