### ISSUE TITLE
eshell don't move back

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#545]
Hi, is it possible to set [evil-move-cursor-back](https://github.com/emacs-evil/evil/blob/215c39d1c4312ce5a3a66c19bbba61374d029c86/evil-common.el#L1099) to `nil` in eshell?

I think this alone would get me to switch to eshell as my daily driver...

**Comment by jgarte** [comment]
@condy0919 

Actually, I added it to my emacs config and tested but I still get the same behaviour. 

Does it work for you?

**Comment by condy0919** [comment]
https://github.com/emacs-evil/evil-collection/commit/a81b6c8f5537b3646e6a66a6e60ec634848d1926

It's installed in evil-collection.
