### ISSUE TITLE
Feature Request: scheme-mode

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#546]
For those not using geiser and just the built in [scheme mode](https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/progmodes/xscheme.el#L146)

https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/progmodes/scheme.el

The ["gz"](https://github.com/emacs-evil/evil-collection/blob/master/modes/python/evil-collection-python.el#L45) shortcut would be nice to have like python-mode does currently.

**Comment by condy0919** [comment]
Test please, it works well on my machine.

**Comment by jgarte** [comment]
> Test please, it works well on my machine.
@condy0919 
I tested it. Works great! Thanks so much 😃

**Comment by condy0919** [comment]
OK
