### ISSUE TITLE
Feature-Request: eldoc

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#551]
https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/emacs-lisp/eldoc.el

**Comment by condy0919** [comment]
But eldoc has no keymap, what integration in your mind?

**Comment by condy0919** [comment]
Do you mean that `q` to quit the buffer created by `eldoc-doc-buffer`?

**Comment by jgarte** [comment]
> Do you mean that `q` to quit the buffer created by `eldoc-doc-buffer`?

I'm not sure if it was created by `eldoc-doc-buffer` but that sounds right.

Should it just be closed like a regular buffer instead? `Ctrl+x k` or `Ctrl+w c` (evil mode)?

**Comment by condy0919** [comment]
> Should it just be closed like a regular buffer instead? `Ctrl+x k` or `Ctrl+w c` (evil mode)?

Yes, it could.

**Comment by jojojames** [comment]
There are a couple modes like that where the buffer created by -insert package- is in fundamental mode displaying some read-only text. It'd be nice to round them up and apply some common minor-mode to them (e.g. evil-collection-quit-minor-mode) so we can get consistent behavior.

I added a new minor mode for eldoc (similar to restclient integration) which can serve as a template if we ever create a generic mode.
