### ISSUE TITLE
Feature-Request: Support corfu

### ISSUE THREAD

**Issue by minad** [emacs-evil/evil-collection#552]
In principle Corfu should work with Evil, but there seem to be issues with the priorities of the keymaps. Furthermore support for Vim-style keybindings would be neat. I am not an Evil-user myself, so I am leaving this here as a feature request.

* https://github.com/minad/corfu
* https://github.com/minad/corfu/issues/73

**Comment by jojojames** [comment]
Corfu looks pretty cool, I don't use it but I may try and install it and see if I can set something up.

**Comment by jgarte** [comment]
I would definitely like to have evil bindings for corfu.

The relevant target maps in the corfu code:

https://github.com/minad/corfu/blob/main/corfu.el#L219

**Comment by jojojames** [comment]
I added a quick integration for corfu but there are a lot of keys in that map, so just bounded the up/down/scroll commands. If users want to bind more keys, they should be able to bind similarly to how it's being done now.

**Comment by ssfrr** [comment]
This seems to be causing problems for me. I've been using evil and evil-collection, with `(evil-collection-init)` in my config. I just installed corfu.

The behavior I'm seeing is that when I first open a buffer, my evil keybindings work fine. Then (from insert mode) I press TAB to invoke completion, and then after I select something I'm stuck in insert mode. It's like the ESC keybinding from insert mode got overwritten or something.

Disabling evil-collection seems to resolve the issue.
