### ISSUE TITLE
evil-visual-block and magit-copy-section-value don't work well together

### ISSUE THREAD

**Issue by Bost** [emacs-evil/evil-collection#554]
```
M-x evil-visual-block
M-x magit-copy-section-value
```
puts a gibber like `(nil (868 11) (879 57))` to the kill-ring instead of selected text.
This works fine:
```
M-x evil-visual-line
M-x magit-copy-section-value
```

**Comment by BostX** [comment]
Bug exists on Ubuntu and also on GuixOS:
- Steps to reproduce: [init.el](https://github.com/Bost/dotfiles/blob/ffbcd91e36452e3b95d7f91ed477df47933a337a/guix/guix-home/.emacs.d/init.el)
- Guix & Emacs environment with pinned package versions: [debug-emacs-evil-configuration.scm](https://github.com/Bost/dotfiles/blob/ffbcd91e36452e3b95d7f91ed477df47933a337a/guix/guix-home/debug-emacs-evil-configuration.scm)
- It's the `(nil (0 0) (1))` in the bottom-left corner:
![image](https://user-images.githubusercontent.com/189486/171686614-445aa407-0475-4245-80f4-0fea1d33b2f6.png)

Please reopen the bug, thanks!

**Comment by jojojames** [comment]
Can you try 0.0.8?

**Comment by BostX** [comment]
The problem exists also in the 0.0.8
(The emacs-evil-collection@0.0.8 is not in the guix package repository yet. I just created and sent them a [patch](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=55772).)
