### ISSUE TITLE
fixup/squash commits in history

### ISSUE THREAD

**Issue by Silex** [emacs-evil/evil-collection#562]
Not sure if you are aware, but there are `!fixup` etc commits in the history, e.g https://github.com/emacs-evil/evil-collection/commit/a798f639839ea98487d4aa873ec25306f471defb

**Comment by condy0919** [comment]
force push on master branch is prohibited. Sorry, I have no idea how to fix that.

**Comment by Silex** [comment]
Well you can enable force push on master, fix it, then disable it again.

That will break all forks, but with the right annoncement I think it's ok.

Forks just have to fetch and `git reset --hard origin/master`.

Some people think it's really bad tho so I let you judge.

**Comment by Silex** [comment]
You can use https://github.com/emacs-evil/evil-collection/network to decide wether this is a good idea or not.

**Comment by condy0919** [comment]
Could @jojojames help with that?

**Comment by jojojames** [comment]
Is there an issue with leaving the fixup commits in history?

**Comment by Silex** [comment]
> Is there an issue with leaving the fixup commits in history?

Except that it looks weird, no.

It's a balance between "it looks weird" and "we have to disrupt forks".

I just wanted to raise the issue but if you are fine with it just close it :wink:

**Comment by jojojames** [comment]
Sounds good, yeah not ideal but leaving it seems harmless.
