### ISSUE TITLE
Return not working in ztree (bad setup?)

### ISSUE THREAD

**Issue by GiovanH** [emacs-evil/evil-collection#570]
Unexpected behavior: in `ztree-dir` mode, pressing return over a `[+]` directory while Evil is in normal mode moves the cursor to the next line instead of expanding the entry.

Manually running `M-x ztree-perform-action` expands the entry as expected.

Switching to emacs mode and pressing enter expands the entry as expected.

According to `C-h c RET`, enter is bound to `evil-ret`. Based on https://github.com/emacs-evil/evil-collection/blob/f31162b2536d14bf97fe96d6e54be0d091ba9493/modes/ztree/evil-collection-ztree.el#L43 I would expect this to map to `ztree-perform-action`, but it does not seem to.

There are no evil/evil-collection related messages in `*Messages*`.

I think it's entirely possible I have something set up wrong, as this is the first time I've installed `evil-collection`.

My .emacs for evil mode looks like

```lisp
(add-to-list 'load-path "~/.emacs.d/evil/")

(setq evil-want-integration t)
(setq evil-want-keybinding nil)
(setq evil-overriding-maps nil)

(require 'evil)

(require 'evil-collection)
(evil-collection-init)

(evil-mode 1)
```

Any help is greatly appreciated

**Comment by condy0919** [comment]
Does <kbd>M-:</kbd> `(evil-collection-ztree-setup)` help?

PS: <kbd>RET</kbd> is bound to `ztree-perform-action` on my machine.

**Comment by GiovanH** [comment]
> Does M-: `(evil-collection-ztree-setup)` help?
> 
> PS: RET is bound to `ztree-perform-action` on my machine.

![image](https://user-images.githubusercontent.com/6759280/146728016-4a72e638-b344-4812-96ff-7091edf8f4cb.png)

`M-x evil-collection-z [No match]`

I have a lot of evil-collection symbols, but not `evil-collection-ztree`-anything.

**Comment by condy0919** [comment]
`evil-collection-ztree-setup` is non interactive, it can't be invoked via `M-x`.

**Comment by GiovanH** [comment]
> `evil-collection-ztree-setup` is non interactive, it can't be invoked via `M-x`.

Whoops. But no, not there either.

`Eval: evil-collection-ztree [No match]`

**Comment by condy0919** [comment]
A `(` is missing.. If it starts with a `(`, TAB will search for functions

**Comment by GiovanH** [comment]
`Eval: (evil-collection-ztree-setup)` returns nil but makes `ret` behave correctly. 

According to `customize`, `evil-collection-mode-list` is set to the default and includes `(ztree ztree-diff)`.

**Comment by condy0919** [comment]
```elisp
(with-eval-after-load req
  (evil-collection-require m)
  (funcall (intern (concat "evil-collection-" (symbol-name m)
                           "-setup")))
  (let ((mode-keymaps
         (ignore-errors
           (symbol-value
            (intern (format "evil-collection-%s-maps" m))))))
    (run-hook-with-args 'evil-collection-setup-hook
                        m mode-keymaps)))
```

It only happens if the `ztree` file is not been loaded.

It may be caused by lazy loading. `M-x ztree-dir` loads `ztree-dir.el` only, the
file `ztree.el` is skipped.

I suggest using `use-package`:

``` emacs-lisp
;; Assume you used to bind `C-c z d' to `ztree-dir'.
;;
;; It's also lazy-loaded due to `:bind`.
(use-package ztree
  :ensure t
  :bind ("C-c z d" . ztree-dir))

;; Expanded with
;; M-x pp-macroexpand-last-sexp
(progn
  (use-package-ensure-elpa 'ztree
                           '(t)
                           'nil)
  (defvar use-package--warning137
    #'(lambda
        (keyword err)
        (let
            ((msg
              (format "%s/%s: %s" 'ztree keyword
                      (error-message-string err))))
          (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
        (unless
            (fboundp 'ztree-dir)
          (autoload #'ztree-dir "ztree" nil t))
        (bind-keys :package ztree
                   ("C-c z d" . ztree-dir)))
    (error
     (funcall use-package--warning137 :catch err))))
```

When <kbd>C-c z d</kbd> is pressed, it first loads the file `ztree.el` since
`ztree-dir` is autoloaded symbol defined within ztree package. See the 22th line above.

``` emacs-lisp
(autoload #'ztree-dir "ztree" nil t)
```

In `ztree.el`, it explicitly requires

- `ztree-dir`
- `ztree-diff`

So it will work finally.

If you don't use `use-package`,

``` emacs-lisp
(autoload #'ztree-dir "ztree" nil t)
```

is your friend.

**Comment by GiovanH** [comment]
Makes sense. 

Currently not using use-package, but `(autoload #'ztree-dir "ztree" nil t)` takes care of it. Thanks!

**Comment by condy0919** [comment]
https://github.com/emacs-evil/evil-collection/commit/f78156db21b907c28448bc1316e58b0ba1eef4f8

It should work without `autoload` now.
