### ISSUE TITLE
Bug: can't set flags on magit revert action

### ISSUE THREAD

**Issue by micahbf** [emacs-evil/evil-collection#571]
For magit, the revert action is mapped to `_`/`-`.

However, `-` is how you set flags. The result is that you are unable to set flags on the `revert` action because pressing `-` triggers the action instead of setting a flag.

<img width="476" alt="Screen Shot 2021-12-21 at 11 07 04 AM" src="https://user-images.githubusercontent.com/4381820/146974632-45972c98-1871-4244-9112-0ac997d7c175.png">

**Comment by condy0919** [comment]
cc @jojojames

**Comment by jojojames** [comment]
https://github.com/emacs-evil/evil-collection/issues/524 Suggestions on new bind?

**Comment by micahbf** [comment]
The magit default of `v`/`V` is unused and seems reasonable to me.

**Comment by condy0919** [comment]
LGTM
