### ISSUE TITLE
Unable to open eshell and cannot use pyvenv

### ISSUE THREAD

**Issue by KulkarniKaustubh** [emacs-evil/evil-collection#585]
I have installed evil collection through use-package like so:

```
;; Install evil-collection
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
```

Now, when I try to open my eshell or try to run pyvenv-activate, it gives me this error:

`evil-collection-require: Cannot open load file: No such file or directory, /home/user/.emacs.d/elpa/evil-collection-20220124.225/modes/eshell/evil-collection-eshell`

Please do let me know a fix for this :sweat_smile:

**Comment by jojojames** [comment]
recipe?

**Comment by condy0919** [comment]
> If recipe means doom or spacemacs, it is neither. This is in my vanilla emacs config.

The recipe to reduce.

Does restart help? It seems like you updated `evil-collection` and the old version was removed.

**Comment by KulkarniKaustubh** [comment]
I removed my elpa folder and then restarted emacs and this worked

**Comment by condy0919** [comment]
OK.
