### ISSUE TITLE
Unimpaired gets initialized when using evil-collections-ivy

### ISSUE THREAD

**Issue by Ghosty141** [emacs-evil/evil-collection#587]
I have the following section in my config file and after checking unimpaired always gets initialized after calling "(evil-collection-init 'ivy)" 

```
(use-package evil-collection
  :after evil
  :init
  (evil-collection-init 'ivy)
  )
```

I also couldn't just hide it with delight. Any idea how to fix this?

**Comment by condy0919** [comment]
Since the default value of `evil-collection-want-unimpaired-p` is `t`, it's expected. 

```elisp
(setq evil-collection-want-unimpaired-p nil)
```

in `use-package` `:init` block to disable it.

**Comment by Ghosty141** [comment]
Thank you! Just one more question in case you know the solution: do you know what to pass to delight which mode to hide? Evil-Collection-Unimpaired-Mode did not work.

**Comment by condy0919** [comment]
https://github.com/emacs-evil/evil-collection/blob/magit-revert/modes/unimpaired/evil-collection-unimpaired.el#L50-L53

 `evil-collection-unimpaired-mode`

**Comment by Ghosty141** [comment]
I'll try that again. Thanks.

PS: the link returns 404.
