### ISSUE TITLE
Update evil-collection-mu4e to use new mu4e function names

### ISSUE THREAD

**Issue by tjtrabue** [emacs-evil/evil-collection#593]
## Summary

The `mu4e` package introduced a breaking change where they renamed `mu4e--main-action-str` to `mu4e~main-action-str` (with a tilde instead of a double-dash). Please rename all of your references to that function in `evil-collection-mu4e.el` accordingly, since `mu4e` integration is currently broken.

**Comment by condy0919** [comment]
`mu4e` use `mu4e--main-action-str`.

https://github.com/djcb/mu/blob/master/mu4e/mu4e-main.el#L128
