### ISSUE TITLE
[Help] [evil-collection-company] Ensure C-w bound to evil-delete-backward-word

### ISSUE THREAD

**Issue by josephmturner** [emacs-evil/evil-collection#597]
When using [`company-mode`](https://company-mode.github.io/) with evil-collection, the `C-w` binding is shadowed by `company-show-location`. I tried adding `(kbd "C-w") 'evil-delete-backward-word)` to this list: https://github.com/emacs-evil/evil-collection/blob/b6d46d3fd298cf49584936632ec6f3cebff56e1a/modes/company/evil-collection-company.el#L84
This solved the problem for me, but it's not a very elegant solution. If you have a better suggest, I would appreciate help.

Thank you!

**Comment by condy0919** [comment]
Unbind <kbd>C-w</kbd> from `company-active-map`.

``` emacs-lisp
(define-key company-active-map (kbd "C-w") nil)
```

Or if you prefer `evil-collection-define-key`:

``` emacs-lisp
(evil-collection-define-key 'company-active-map (kbd "C-w") nil)
```

Then, pressing <kbd>C-w</kbd> will invoke a function from the keymap of lower precedence, e.g., `evil-delete-backward-char` in `evil-insert-state-map`.

**Comment by josephmturner** [comment]
Thank you for your clear response!
