### ISSUE TITLE
slime: Wrong type argument: commandp, slime-switch-to-output-buffer

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#600]
When pressing [gz](https://github.com/emacs-evil/evil-collection/blob/master/modes/slime/evil-collection-slime.el) in slime-mode with evil-collection bindings enabled I get the following error:

`Wrong type argument: commandp, slime-switch-to-output-buffer`

**Comment by condy0919** [comment]
How to reproduce it? I'm not a common lisp user.

**Comment by jgarte** [comment]
> How to reproduce it? I'm not a common lisp user.

Try pressing `gz` with evil-collection enabled for slime in a file called `foo.lisp`. 

Make sure to have `sbcl installed. 

`sudo apt install sbcl` to install sbcl if on debian/ubuntu.

**Comment by jojojames** [comment]
Do you think there's something to be done here @condy0919 @jgarte ?

**Comment by condy0919** [comment]
> Do you think there's something to be done here @condy0919 @jgarte ?

Nothing.
