### ISSUE TITLE
Request: org-noter  (https://github.com/weirdNox/org-noter)

### ISSUE THREAD

**Issue by chrischambers** [emacs-evil/evil-collection#609]
https://github.com/weirdNox/org-noter

Relevant mode maps:

- https://github.com/weirdNox/org-noter/blob/9ead81d42dd4dd5074782d239b2efddf9b8b7b3d/org-noter.el#L2052
- https://github.com/weirdNox/org-noter/blob/9ead81d42dd4dd5074782d239b2efddf9b8b7b3d/org-noter.el#L2072

c.f. #443

**Comment by chrischambers** [comment]
For some additional context: something about the way this is implemented makes it very hard for me to override the bindings, be it using the evil-collection definers, noctuid's general or even a local keymap via hooks. These bindings should take precedence over pdf-view-mode, nov-mode, org-mode and evil-mode.

**Comment by condy0919** [comment]
Welcome to PR :-)

**Comment by jojojames** [comment]
@chrischambers Could you provide some examples of what you've tried? I'm not too familiar with org-noter but I may want to tackle it in the future if I have time.
