### ISSUE TITLE
ebib-entry-mode: "y" should be remapped to ebib-copy-current-field-contents

### ISSUE THREAD

**Issue by ahnafalrafi** [emacs-evil/evil-collection#610]
Currently in `ebib-entry-mode`, pressing "y" to copy the contents of a given field produces the following error message: "Wrong type argument: commandp, ebib-copy-field-contents". This is because `ebib-copy-field-contents` is not actually a command. On the other hand, pressing "c" gets the desired result because it is mapped to `ebib-copy-current-field-contents` which is indeed a command.  The "c" mapping is an ebib default that is unchanged by evil-collection. I think that "y" should be mapped to `ebib-copy-current-field-contents` instead by evil-collection.

**Comment by jojojames** [comment]
PR please!

**Comment by ahnafalrafi** [comment]
Submitted PR [#613](https://github.com/emacs-evil/evil-collection/pull/613) proposing this change.

**Comment by ahnafalrafi** [comment]
Closing this issue now since the [PR #613](https://github.com/emacs-evil/evil-collection/pull/613) fixed this.
