### ISSUE TITLE
Bug: Evil change inserts new line in minibuffer.

### ISSUE THREAD

**Issue by jack-faller** [emacs-evil/evil-collection#616]
With evil keys enabled in the minibuffer through ```evil-collection-setup-minibuffer```, evil change (cc) may insert a new line into the minibuffer that prevents entering the command correctly.
This occurs because evil-change deletes up to and including a new line and then opens a line above to re-insert it.
Doing it this way inserts a new line if none was present before the change.
I have the code below in my init file to fix this.
```elisp
(evil-define-operator evil-change-minibuffer-fix
  (beg end type register yank-handler delete-func)
  "A version of `evil-change' that won't insert a new line on buffers without one."
  (interactive "<R><x><y>")
  ;; If there was no new line before the change, there should be none after.
  ;; Delete any new line that might have been inserted and ignore an error if
  ;; one wasn't.
  (let ((new-inserted (and (eq type 'line) (/= ?\n (char-before end)))))
    (evil-change beg end type register yank-handler delete-func)
    (when new-inserted (ignore-errors (delete-char 1)))))

(dolist (i evil-collection-minibuffer-maps)
  (evil-define-key 'normal (symbol-value i)
    "c" #'evil-change-minibuffer-fix))
```

To reproduce:
Open minibuffer, in normal mode do cc, and a new line is inserted.

**Comment by jojojames** [comment]
Can you explain how you get into minibuffer -> use evil-collection-minibuffer, I'm not too familiar with that mode.

**Comment by jack-faller** [comment]
You set the ```evil-collection-setup-minibuffer``` flag before the call to ```evil-collection-init```, then it activates evil bindings in the minibuffer.
I think it says something about it in the readme.

**Comment by jojojames** [comment]
How are you interacting with the minibuffer? Any modes like ivy/ido etc?

**Comment by jack-faller** [comment]
I use selectrum, but I've tried and it still seems to happen with emacs -q then loading only evil and evil-collection.

**Comment by condy0919** [comment]
Confirmed.

Another workaround it bind `cc` to move point to `(point-min)` then call `C`.
