### ISSUE TITLE
evil-append after link jump to next line

### ISSUE THREAD

**Issue by wztdream** [emacs-evil/evil-collection#624]
Hi,
I just noticed that evil-append after a link will jump to next line instead of "append after the link".
For example:
1. you type [[123]] then get a link 123
2. change to normal mode
3. move cursor to the end of 123, now the cursor is right after 123, i.e. 123x, and "x" represent the cursor
4. then you type "a" to append a letter, but the cursor will jump to next line.

So I think maybe there is some bug here.
Btw, I am using spacemacs.

**Comment by jojojames** [comment]
Which mode?

**Comment by wztdream** [comment]
> Which mode?

evil-append is in evil-commands.el, so I think I made a mistake here, this feature should be from spacemacs, so I will close it here and open on in spacemacs repo.
