### ISSUE TITLE
Corfu and evil-repeat

### ISSUE THREAD

**Issue by aaronjensen** [emacs-evil/evil-collection#628]
I've noticed that evil-repeat (the `.` key) does not work with corfu auto completion (I use a tab'n'go style).

Specifically, if I do something like this:

```
foo
foo
foo
```

Point on first foo, `cw`, `ba` tab to select bar, go down to `foo` and hit `.`, only `ba` will be included. 

In company, this was first reported here: https://github.com/company-mode/company-mode/issues/15
And addressed with: https://github.com/emacs-evil/evil/blob/master/evil-integration.el#L212-L230

I can't make it work with corfu with any combination of evil repeat specifications.

Thanks all.

![CleanShot 2022-05-14 at 00 08 11](https://user-images.githubusercontent.com/8588/168410176-ad4485cc-2366-4968-85c1-07991d3de831.gif)

**Comment by jojojames** [comment]
I tried to follow the crumbtrail and it looks like there's some update somewhere else right and nothing from evil? (not super sure)

**Comment by aaronjensen** [comment]
I have it working. It requires a change in corfu. Whether or not that change will be made is tbd. If it isn’t, overriding advice will be required to make it work.

**Comment by aaronjensen** [comment]
https://github.com/minad/corfu/pull/169

**Comment by jojojames** [comment]
I see, feel free to PR the advice/change while you wait for minad's decision (NO PR and waiting is fine too). Will close this as there's nothing to do on evil's side it seems.
