### ISSUE TITLE
realgud misses `realgud:cmd-until-here`

### ISSUE THREAD

**Issue by Dickby** [emacs-evil/evil-collection#629]
the initial key for `realgud:cmd-until-here` is `h` which is of course an evil movement but has no replacement in evil-collection

**Comment by Dickby** [comment]
I guess it should been bound to `H` because now bot `U` and `H` is `realgud:cmd-until`

**Comment by jojojames** [comment]
Please PR, I haven't used realgud in years. :)

**Comment by condy0919** [comment]
Fixed by #630
