### ISSUE TITLE
Best effort for helm

### ISSUE THREAD

**Issue by quicknir** [emacs-evil/evil-collection#63]
Hello, trying this out. The `evil-minibuffer` stuff is really fantastic, I love being able to use modes when issuing compile commands.  The only downside is that helm (which I use in the minibuffer, this is the default in spacemacs), ends up looking funny. I attached a screenshot. Basically the cursor both appears at the top of the helm buffer (where I normally type), but also at the very bottom. Some of the faces applied by spacemacs (changing the color and cursor style between normal and insert) appear at the top, some at the bottom. When you are in visual mode, the highlighted text appears at the bottom. Etc.

My understanding is that much of this is probably not fixable, due to fundamental minibuffer limitations. Related link: https://emacs.stackexchange.com/questions/17058/change-cursor-type-in-helm-header-line#17097.

I open this issue as a place where we can try to determine what the best possible behavior is for helm, and then restrict things to maximize benefit. For example, if visual mode can't be made to display properly, let's block access to it. Etc.

If it helps, I'm using spacemacs and thus the default helm setup in spacemacs.
![screenshot from 2017-12-23 22-32-34](https://user-images.githubusercontent.com/10457096/34324131-003d1f70-e834-11e7-8cfd-86e8c6ec1c78.png)

**Comment by Ambrevar** [comment]
Indeed, what you are seeing here is a conflict of face settings.

I had a look at this issue a while back and it seemed like an unrecoverable limitation.
I could have been wrong though.  I'll have a second look into it.

Should it be impossible to solve properly, I'll add some customization option to evil-helm.

**Comment by quicknir** [comment]
Cool, thanks for the response. I think assuming nothing can be improved further, the main two things that have to happen are hiding the bottom cursor and text, and disabling visual mode. I'm not sure how much of this is caused by spacemacs trying to customize the cursor. In particular spacemacs color customization seems successful, but not the cursor type, so that may need to be disabled.

If these details can be worked out I plan to PR this into spacemacs; unsure whether the code will be copied or a dependency on evil-collection will be introduced, up to the maintainer.

Thanks again for all your hard work.

**Comment by Ambrevar** [comment]
I just gave this another shot in 951df9586d5a4ec4876c6fa0a6cfd79da1f26a8a.
Now the insert-state cursor will change to `'underline` since it seems to be the only possible workaround.
Visual selections will also display correctly in the header line.

Now the only tweaks left are:
- Hide the cursor in the minibuffer.
- Hide the visual selection in the minibuffer.

**Comment by Ambrevar** [comment]
Unrelated to cosmetics, we can also implement #111: make `i` turn off read-only mode in saved Helm buffers.

**Comment by deviantfero** [comment]
I'm having this exact same issue too, only happens on certain ocassions though, more specifically, when there's a projectile project open.

**Comment by jojojames** [comment]
Is there something more here @Ambrevar or can we close this?

**Comment by Ambrevar** [comment]
Beside the above two cosmetic nits, not really, I've used Evil + Helm for a year now.

**Comment by taquangtrung** [comment]
@Ambrevar: I fixed that issue in https://github.com/emacs-evil/evil-collection/pull/732.

Can you try if my PR works for you?
