### ISSUE TITLE
evil-collection overrides default evil state for Buffer-menu-mode

### ISSUE THREAD

**Issue by JoshMcguigan** [emacs-evil/evil-collection#631]
Hi! Thanks for your work on this project.

I've noticed that I wasn't able to quit `Buffer-menu-mode` with `q`,and I think I tracked it down to an interaction between the mappings in evil-collection and the default evil bindings for `Buffer-menu-mode`. 

The default bindings use `motion` state for `Buffer-menu-mode`, which I think would allow quitting with `q`.

https://github.com/emacs-evil/evil/blob/157af04d2cf466e301e82b0e667c5e7203fd96a2/evil-vars.el#L915

But evil-collection sets `Buffer-mode-menu` to startup in `normal` state, where `q` is bound to recording a macro.

https://github.com/emacs-evil/evil-collection/blob/11cfad9b3c01feb7848f13d5c3f5cc1787ab6eb6/modes/buff-menu/evil-collection-buff-menu.el#L73

I'm not sure how evil-collection typically works, does there need to be a mapping for `Buffer-menu-mode` in evil collection if that mapping exists by default? If not, I can submit a PR to remove this mapping from evil-collection.

**Comment by JoshMcguigan** [comment]
In case anyone else is running into this issue, in the short term I am working around it by adding a line to my config.

```
  (with-eval-after-load 'evil-collection-buff-menu (defun evil-collection-buff-menu-setup() ()))
```

**Comment by jojojames** [comment]
You're using M-x buffer-menu to open the buffer menu? It works for me with q for quit-window.

**Comment by JoshMcguigan** [comment]
I am, yes. That is interesting that it works for you. Can you confirm that you are in evil normal state (since q should be mapped to something else there)? And also can you describe-bindings and see where that q binding is coming from?

**Comment by jojojames** [comment]
Yes, 

```
`t' Minor Mode Bindings:
key             binding
---             -------

C-d             Buffer-menu-delete-backwards
C-k             Buffer-menu-delete
RET             Buffer-menu-this-window
ESC             Prefix Command
%               Buffer-menu-toggle-read-only
1               Buffer-menu-1-window
2               Buffer-menu-2-window
S               tabulated-list-sort
T               Buffer-menu-toggle-files-only
U               Buffer-menu-unmark-all
X               Buffer-menu-bury
Z               Prefix Command
d               Buffer-menu-delete
g               Prefix Command
m               Buffer-menu-mark
o               tabulated-list-sort
q               quit-window
```

Can you emacs -Q and see what's up (produce a repro)?

**Comment by JoshMcguigan** [comment]
Can you `describe-variable` on `evil-normal-state-minor-mode`? From what I'm seeing in the code I'd expect you to be in normal state, which I think would override that `q` mapping (it did for me).

**Comment by jojojames** [comment]
Could you produce a reproducible emacs -Q recipe? I think that'd get us there faster than us playing debug tag on why my setup works. :D

**Comment by JoshMcguigan** [comment]
I'm actually very new to emacs and not really sure how to do that. I'm using spacemacs so I haven't messed with package management stuff at all. 

From my initial testing I saw both the normal state and motion states active for buffer-menu, so it wouldn't surprise me if some subtle changes to the order of code setup could make this work. But does it seem reasonable to you based on what I've described that evil-collection puts the buffer-menu buffer into evil normal state, and when it is in evil normal state that `q` will be bound to recording a macro, which would override the binding you show above?

**Comment by JoshMcguigan** [comment]
Alright, I have a minimal setup which does _not_ reproduce this issue.

```
;; min.el

(add-to-list 'load-path (expand-file-name "~/workspace/goto-chg/"))
(add-to-list 'load-path (expand-file-name "~/workspace/annalist.el/"))
(add-to-list 'load-path (expand-file-name "~/workspace/evil/"))
(add-to-list 'load-path (expand-file-name "~/workspace/evil-collection/"))
(setq evil-want-integration t) ;; This is optional since it's already set to t by default.
(setq evil-want-keybinding nil)
(require 'evil)
(when (require 'evil-collection nil t) (evil-collection-init))
(evil-mode 1)
```

`emacs -q --load min.el`

I'll keep poking around at this to try to understand what is going on with my actual configuration.

**Comment by JoshMcguigan** [comment]
I'm a bit stumped here on creating a minimal repro, but I was able to recreate this with a fresh spacemacs configuration, so I went ahead and filed https://github.com/syl20bnr/spacemacs/issues/15534.

**Comment by jojojames** [comment]
Sure, feel free to loop back/open this bug again if there's more needed from evil-collection.

As for emacs-q, there's a couple ways to do it, (I bet there are recipes on google)

I use this snippet and then add the rest.

```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package evil :ensure t :init ETC ETC)
(use-package evil-collection :ensure t :init ETC ETC)
```
