### ISSUE TITLE
Wants to create macro instead of closing window in magit

### ISSUE THREAD

**Issue by PortStone** [emacs-evil/evil-collection#634]
If I go to `magit-status` and hit enter on a commit to see it and after that hit enter on a file I modified to see the state of the file I can't easily quit the window by pressing `q` instead it wants to create a new macro which is annoying.

**Comment by jojojames** [comment]
Isn't q bound?

```
q runs the command magit-kill-this-buffer (found in magit-blob-mode-map), which
is an interactive native compiled Lisp function in ‘magit-base.el’.

It is bound to q.

(magit-kill-this-buffer)

Kill the current buffer.
```

As for my own setup, quit-window seems better but leaving it at the default seems reasonable.

**Comment by PortStone** [comment]
> Isn't q bound?
> 
> ```
> q runs the command magit-kill-this-buffer (found in magit-blob-mode-map), which
> is an interactive native compiled Lisp function in ‘magit-base.el’.
> 
> It is bound to q.
> 
> (magit-kill-this-buffer)
> 
> Kill the current buffer.
> ```
> 
> As for my own setup, quit-window seems better but leaving it at the default seems reasonable.

If I am in `magit-status` and do a `CTRL + h + k` q is set to `magit-mode-bury-buffer` but if I go to a file from a recent commit it is bound to `evil-record-macro`. I mean it does work since discarding a hunk is bound to x instead of k. Thats the reason I thought the problem is evil-collection. Did I maybe have a wrong setup? This is how I configured it:

Evil
``` elisp
(use-package undo-fu
  :bind (:map evil-normal-state-map
              ("u" . undo-fu-only-undo)
              ("C-r" . undo-fu-only-redo)))

(use-package evil
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  :custom
  (evil-undo-system 'undo-fu)
  :config
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
```

Magit:
``` elisp
(use-package magit
  :commands magit-status
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
  (magit-diff-refine-hunk 'all)
  (magit-diff-refine-ignore-whitespace nil))
```

**Comment by jojojames** [comment]
Can you provide a minimal config I can try that reproduces the issue?

Something like this is a good starting point;

```
(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)
```

**Comment by PortStone** [comment]
> Can you provide a minimal config I can try that reproduces the issue?
> 
> Something like this is a good starting point;
> 
> ```
> (setq package-enable-at-startup nil
>       package-archives
>       '(("melpa" . "https://melpa.org/packages/")
>         ("gnu" . "http://elpa.gnu.org/packages/")))
> 
> (require 'package)
> (package-initialize)
> (unless (package-installed-p 'use-package)
>   (package-refresh-contents)
>   (package-install 'use-package))
> (require 'use-package)
> (setq use-package-always-ensure t)
> ```

I tested it out with a minimal config and it does work. Therefore the issue is on my side.

Config I used:
``` elisp
(setq user-emacs-directory "~/.emacs.1.d")

(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)


(use-package evil
  :ensure t
  :init
  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))

(use-package magit)
```

**Comment by PortStone** [comment]
I cleaned up my `.emacs.d` directory and reinstalled all packages. It is now working correctly out of the box.
