### ISSUE TITLE
help menu in magit is not displayed properly

### ISSUE THREAD

**Issue by cs50Mu** [emacs-evil/evil-collection#637]
Press ? in `magit-status` gives the following in which some keybindings are wrong:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/4456781/170499675-a1e7e365-9ec8-4b48-8474-104ac59e5504.png">

for example, Discard should be `x` instead of `k`; Reset should be `O` instead of `X`

`magit-version` gives:  

<img width="757" alt="image" src="https://user-images.githubusercontent.com/4456781/170500467-d111aea3-39a8-44ad-8943-f7da4ad70652.png">

**Comment by jojojames** [comment]
I see 'x' for discard and 'O' for Reset. Can you provide an emacs-q recipe?

**Comment by cs50Mu** [comment]
> I see 'x' for discard and 'O' for Reset. Can you provide an emacs-q recipe?

I'm an emacs noob, did you mean run emacs with `emacs -Q` in terminal?

**Comment by jojojames** [comment]
Yeah, I added a section here:

https://github.com/emacs-evil/evil-collection#submitting-issues

emacs -Q in terminal, then you can probably eval that snippet and test from there.

**Comment by cs50Mu** [comment]
> Yeah, I added a section here:
> 
> https://github.com/emacs-evil/evil-collection#submitting-issues
> 
> emacs -Q in terminal, then you can probably eval that snippet and test from there.

I've reproduced the issue with the following steps:

- start emacs with `emacs -Q`
- in the scratch buffer, paste the code snippet you just provided: [submitting-issues](https://github.com/emacs-evil/evil-collection#submitting-issues)
- add this line in the buffer: `(use-package magit)`
- M-x and run the command: eval-buffer
- open a file in a git project
- press `C-x g` to show the magit-status panel
- press `?` to show the help menu
- and it still show the wrong keybindings

<img width="657" alt="image" src="https://user-images.githubusercontent.com/4456781/170832470-090a3dd2-1b52-489d-85cc-bfcc2747b14e.png">

emacs version: I installed emacs from [emacsformacosx](https://emacsformacosx.com/)  
operating system: macOS Monterey 12.2.1

**Comment by jojojames** [comment]
Can you paste the exact emacs -Q recipe you used?

e.g. what you eval'ed

**Comment by cs50Mu** [comment]
> Can you paste the exact emacs -Q recipe you used?
> 
> e.g. what you eval'ed

```
(setq user-emacs-directory "~/.emacs.1.d")

(setq package-enable-at-startup nil
      package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "http://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package evil
  :ensure t
  :init
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))

(use-package magit)
```

**Comment by jojojames** [comment]
This one is very strange for me. The initial emacs-q doesn't work but sometimes, subsequent ones seem to 'resolve' itself.. Not sure what's going on.

Also, I messed up the snippet I gave you (but fixed it in my own while repro-ing). It should look like this instead.

It should include setting the package dir too.

```
(setq package-user-dir
      (format "%selpa/%s/" user-emacs-directory emacs-major-version))
```

Will update the snippet soon.

As for me, I'm suspecting maybe a new commit on magit and/or transient may be the issue, definitely not sure though. I'm a few commits behind on both. The other possibility is something with magit-section.

Magit: 6d66ab34 master magit-refresh-get-relative-position: Fix regression
Transient: 2e4426f origin/master Quote single quote in docstring

I may update soon and try to see if I'm seeing the same issue.

**Comment by cs50Mu** [comment]
> 

@jojojames sorry, can you tell me how to do this..?

> the next emacs -Q (but pointed at the same elpa directory) 

I don't know how to load the previous elpa

**Comment by jojojames** [comment]
Delete the emacs -Q directory (.emacs.1.d)
emacs -Q with recipe -> creates a new .emacs.1.d
quit emacs
emacs -Q with same recipe -> should be pointed at .emacs.1.d

**Comment by cs50Mu** [comment]
After `emacs -Q` with the same recipe, I still get the same result...

`k` for Discard, and X for Reset

**Comment by cs50Mu** [comment]
I still have another emacs instance running when I'm doing the `emacs -Q` testing, does it matter?

**Comment by jojojames** [comment]
It shouldn't because your main emacs instance should be pointed at .emacs.d and your emacs -Q recipe should be pointed at .emacs.1.d. So you wiped .emacs.1.d, emacs -Q -> restarted and then -> emacs -Q again?

**Comment by cs50Mu** [comment]
I did the follows:

**first time**

- `emacs -Q` to start emacs
- paste the recipe you just provided
- `M-x` eval-buffer to run the recipe
- open a file in a git project
- press C-x g to show the magit-status panel
- press ? to show the help menu
- and it show the wrong keybindings
- `:q` to exit emacs

**second time**

- `emacs -Q` to start emacs again
- paste the recipe you just provided
- `M-x` eval-buffer to run the recipe (emacs reuses the previous `.emacs.1.d` folder)
- open a file in a git project
- in the `magit-status` panel, still sees wrong keybindings in help menu

@jojojames

**Comment by jojojames** [comment]
@condy0919 Can you give it a shot?

**Comment by condy0919** [comment]
same issue. let me use the recipe again.

**Comment by progfolio** [comment]
Just an FYI. I wrote [yodel](https://www.github.com/progfolio/yodel) with these kinds of tests in mind. Here's a demo with your current test case:

[Yodel](https://github.com/progfolio/yodel) Report (2022-06-08 15:05:14):

```emacs-lisp
(yodel
  :save "yodel-magit"
  :interactive nil
  :packages* use-package
  :post*
  (setq straight-use-package-by-default t)
  (use-package evil
    :init
    (setq evil-want-keybinding nil)
    :config (evil-mode 1))
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
  (use-package magit)
  (let ((default-directory (straight--repos-dir "magit")))
    (magit-status)
    (magit-dispatch)
    (with-current-buffer transient--buffer-name
      (print (buffer-substring-no-properties (point-min) (point-max))))))
```

<details><summary>STDOUT:</summary>

```emacs-lisp
Loading /tmp/yodel-magit/straight-bootstrap-snippet.el (source)...


"Transient and dwim commands
 A Apply            i Ignore             r Rebase
 b Branch           I Init               t Tag
 B Bisect           j Jump to section    T Note
 c Commit           J Display buffer     V Revert
 C Clone            l Log                w Apply patches
 d Diff             L Log (change)       W Format patches
 D Diff (change)    m Merge              X Reset
 e Ediff (dwim)     M Remote             y Show Refs
 E Ediff            o Submodule          Y Cherries
 f Fetch            O Subtree            z Stash
 F Pull             P Push               Z Worktree
 h Help             Q Command            ! Run
 H Section info                         

Applying changes
 a Apply      s Stage      S Stage all
 v Reverse    u Unstage    U Unstage all
 k Discard                

Essential commands
 g        refresh current buffer     C-x m show all key bindings
 q        bury current buffer        C-x i show Info manual
 <tab>    toggle section at point   
 <return> visit thing at point      
"
```

</details>
<details><summary>Environment</summary>

- **emacs version**: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-06-04
- **system type**: gnu/linux

<details open><summary>Packages</summary>

| Name                                                             | Branch | Commit                                                                                        | Date       | Source          |
|------------------------------------------------------------------|--------|-----------------------------------------------------------------------------------------------|------------|-----------------|
| [use-package](https://github.com/jwiegley/use-package)           | master | https://github.com/jwiegley/use-package/commit/a7422fb8ab1baee19adb2717b5b47b9c3812a84c       | 2021-02-10 | melpa           |
| [bind-key](https://github.com/jwiegley/use-package)              | master | https://github.com/jwiegley/use-package/commit/a7422fb8ab1baee19adb2717b5b47b9c3812a84c       | 2021-02-10 | melpa           |
| [evil](https://github.com/emacs-evil/evil)                       | master | https://github.com/emacs-evil/evil/commit/157af04d2cf466e301e82b0e667c5e7203fd96a2            | 2022-05-18 | melpa           |
| [goto-chg](https://github.com/emacs-evil/goto-chg)               | master | https://github.com/emacs-evil/goto-chg/commit/278cd3e6d5107693aa2bb33189ca503f22f227d0        | 2022-01-07 | melpa           |
| [evil-collection](https://github.com/emacs-evil/evil-collection) | master | https://github.com/emacs-evil/evil-collection/commit/79fc09b0140311377726551ee31622f61d28c571 | 2022-06-06 | melpa           |
| [annalist](https://github.com/noctuid/annalist.el)               | master | https://github.com/noctuid/annalist.el/commit/134fa3f0fb91a636a1c005c483516d4b64905a6d        | 2019-10-20 | melpa           |
| [magit](https://github.com/magit/magit)                          | master | https://github.com/magit/magit/commit/2dfeaa6839c643a54d96c9f855bae11d5cba2453                | 2022-06-07 | melpa           |
| [compat](https://github.com/emacs-straight/compat)               | master | https://github.com/emacs-straight/compat/commit/884d47ef896cff2fa6910c359f1aa0e0ff8c7acd      | 2022-06-07 | gnu-elpa-mirror |
| [dash](https://github.com/magnars/dash.el)                       | master | https://github.com/magnars/dash.el/commit/0c49a33a61c739eb12e4c3680138c1659926202d            | 2022-06-07 | melpa           |
| [git-commit](https://github.com/magit/magit)                     | master | https://github.com/magit/magit/commit/2dfeaa6839c643a54d96c9f855bae11d5cba2453                | 2022-06-07 | melpa           |
| [transient](https://github.com/magit/transient)                  | master | https://github.com/magit/transient/commit/2e4426fe8161893382f09b3f4635e152ee02488e            | 2022-05-28 | melpa           |
| [with-editor](https://github.com/magit/with-editor)              | master | https://github.com/magit/with-editor/commit/cfcbc2731e402b9169c0dc03e89b5b57aa988502          | 2022-06-08 | melpa           |
| [magit-section](https://github.com/magit/magit)                  | master | https://github.com/magit/magit/commit/2dfeaa6839c643a54d96c9f855bae11d5cba2453                | 2022-06-07 | melpa           |

</details>

</details>

**Comment by jojojames** [comment]
What about the second run?

**Comment by progfolio** [comment]
> What about the second run?

That was the second run. `:save path` preserves the environment between runs.
On your first run you would see much more output from straight bootstrapping and installing the packages.

**Comment by jojojames** [comment]
Not really sure :D, maybe @tarsius can help. We're not (hopefully not) doing anything special with the popups other than swapping them here: https://github.com/emacs-evil/evil-collection/blob/e049bc4777cae21d937e08ad2d3960f3e1432dd5/modes/magit/evil-collection-magit.el#L621

**Comment by tarsius** [comment]
Try if doing this manually works:

```emacs-lisp
(transient-suffix-put 'magit-dispatch "O" :key "\"")
(transient-suffix-put 'magit-dispatch "X" :key "O")
(transient-suffix-put 'magit-dispatch "k" :key "x")
```

The only potential problem that I see is `(require 'magit nil t)`. Like a keymap, a transient command cannot be modified until it is defined. But if it is not, then you should get errors like `transient--layout-member: foobar is not a transient command`. Still, my guess is that an `with-eval-after-load` is missing somewhere.

I would add debug statements to see whether the relevant code is being called, and when. Start by adding `(message "-- %s: %s => %s (%s)" popup from to (featurep 'magit))` to `evil-collection-magit-change-popup-key`.

**Comment by condy0919** [comment]
> Try if doing this manually works:
> 
> ```emacs-lisp
> (transient-suffix-put 'magit-dispatch "O" :key "\"")
> (transient-suffix-put 'magit-dispatch "X" :key "O")
> (transient-suffix-put 'magit-dispatch "k" :key "x")
> ```
> 
> The only potential problem that I see is `(require 'magit nil t)`. Like a keymap, a transient command cannot be modified until it is defined. But if it is not, then you should get errors like `transient--layout-member: foobar is not a transient command`. Still, my guess is that an `with-eval-after-load` is missing somewhere.

It's here. https://github.com/emacs-evil/evil-collection/blob/master/evil-collection.el#L884

**Comment by ThorpeJosh** [comment]
Hey, Just wanted to list a few more keybindings in the menu that are not evil compliant:

Discard should be `x` instead of `k`
Reset should be `O` instead of `X`
Reverse should be `-` instead of `v`
Revert should be `_` instead of `V`
Display status should be `g` (I think) instead of `j`

**Comment by adamliter** [comment]
I'm having this same issue with a relatively vanilla installation of Doom Emacs, for what it's worth.

**Comment by ZacheryPD** [comment]
I am seeing the same issue running Emacs 28.2 on Fedora. Specifically, I am seeing the help menu tell me that `o` is bound to "submodule" but it isn't (submodule is bound to `'`). `o` is actually bound to `magit-reset-quickly`, even when running emacs -q with the recipe posted above.

**Comment by randomizedthinking** [comment]
I got the same issue with evil-collection, and my screenshot is the same as @cs50Mu has posted.

What I observed is that these key-mappings are correct in some sense. For instance, when I pressed `h`, the help window is shown. When the help window is present, `X` is indeed mapped to `magit-reset`. Yet, when just inside the magit buffer without the help window, `X` is mapped to `magit-file-untrack`.

All the incorrectly mapped keys are the same: their mappings are different with or without the help window.

**Comment by sg-qwt** [comment]
I'm having this same issue. After I put magit to load after evil-collection, issues seems go away.
```
(use-package evil-collection
  :after (evil magit)
  .....
  )
```

**Comment by tshu-w** [comment]
I tried to `(require 'magit)` in `evil-collection-magit-setup`, but it doesn't seem to work. It seems that I need to put `(require 'magit)` before `(evil-collection-init)` for it to work.
```emacs-lisp
  (defun evil-collection-magit-setup@override ()
    "Set up `evil' bindings for `magit'."
    (require 'magit)
    (evil-collection-define-key 'normal 'magit-blame-mode-map
      "q" 'magit-blame-quit)
    (evil-collection-define-key 'normal 'magit-blame-read-only-mode-map
      "q" 'magit-blame-quit)

    (evil-collection-magit-init))
  (advice-add 'evil-collection-magit-setup@override :override 'evil-collection-magit-setup)
```

**Comment by ZacheryPD** [comment]
> I'm having this same issue. After I put magit to load after evil-collection, issue seems to go away.
> 
> ```
> (use-package evil-collection
>   :after (evil magit)
>   .....
>   )
> ```

I can't believe I never thought of this. I [did this in my config](https://github.com/ZacheryPD/Emacs-From-Scratch/commit/1f242f139a7e328e100bc5b4bf95970a3a8b725a) and it works flawlessly now. Thank you!

**Comment by sooriravindra** [comment]
```
(use-package evil-collection
  :after (evil magit)
  :config (evil-collection-init))
```
The above snippet solves it. But it has the side effect that dired doesn't behabe as expected. Eg:  hitting enter on  a file name doesn't open the file in normal mode (you need to go into insert mode to be able to do so).  Removing magit from the :after restores the behavior of dired but the magit help menu is wrong.

**Comment by 1player** [comment]
> But it has the side effect that dired doesn't behave as expected. Eg: hitting enter on a file name doesn't open the file in normal mode (you need to go into insert mode to be able to do so). Removing magit from the :after restores the behavior of dired but the magit help menu is wrong.

Can't reproduce here. `:after (evil magit)` solves this issue, and does not affect dired.

**Comment by sooriravindra** [comment]
I tracked down the issue to this minimal config:
```
(setq-default use-package-always-ensure t)
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			 ("elpa-devel" . "https://elpa.gnu.org/devel/")))
(package-initialize)

(package-refresh-contents)

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)

(use-package evil
  :init
  (setq evil-want-integration t
        evil-want-keybinding nil)
  :config
  (evil-mode 1))

(use-package magit
  :config
  :bind ("C-x g" . magit-status)
  )

(use-package evil-collection
  :after evil magit
  :config
  (evil-collection-init))

```
The issue is seen with the above init.el but goes away when I remove the :bind for Magit. I can't figure out why! But my issue is resolved.

**Comment by 1player** [comment]
I would hazard a guess: The `:bind` incantation in use-package makes it so the package is loaded *only* when required, i.e. you press `C-x g`.

https://github.com/jwiegley/use-package#key-binding

If you configure evil-collection to wait until magit and dired are loaded, it means that it won't be loaded until you open magit at least once. Until then, dired won't have all the evil-compatible keybinds.

The workaround is to tell use-package not to defer loading magit. You can do so by adding the `:demand t` option:

```
(use-package magit
  :demand t
  :config
  :bind ("C-x g" . magit-status)
  )
```

https://github.com/jwiegley/use-package#notes-about-lazy-loading

This should fix it.

**Comment by sooriravindra** [comment]
@1player Thanks a bunch for demystifying it for me.

**Comment by swinkels** [comment]
It took some time to find out what causes this issue, but I think I found it:

1. When you load the upstream magit module for the first time, it starts by loading its dependencies, one of them being the upstream magit-repos module.
2. The load of magit-repos is setup to trigger the load and setup of evil-collection-magit - this happens in lines 921-925 of evil-collection.el. So the load of magit is interrupted to do that load and setup.
3. The load of evil-collection-magit also loads upstream magit, and because the load of magit at step 1 was interrupted, this actual loads it. This sets up the original keybindings for the magit dispatch popup menu. The subsequent call to evil-collection-magit-setup overwrites them with the evil ones.
4. Now the bug shows up: the load of magit at step 1 was interrupted but continues after the evil-collection-magit work is done. When it continues, it again sets up the keybindings of the dispatch menu, thereby "resetting" the evil ones.

**Comment by swinkels** [comment]
I think you can workaround the issue by removing `magit-repos` as a dependency from `magit` in `evil-collection--supported-modes` at https://github.com/emacs-evil/evil-collection/blob/12fd87b631eea6b9b9be96456f39a03f0864dd3c/evil-collection.el#L253 This should be safe to do as magit requires magit-repos, "famous last words" anyone?

Disclaimer: I use evil-collection via Doom Emacs and Doom does things somewhat different with regard to evil-collection. For example, it initializes `evil-collection-mode-list` to a list that is very similar to the list of `evil-collection--supported-modes`. If I apply the workaround to `evil-collection-mode-list` in Doom Emacs, the bindings of transient menu magit-dispatch are set correctly.

**Comment by tshu-w** [comment]
> I think you can workaround the issue by removing `magit-repos` as a dependency from `magit` in `evil-collection--supported-modes` at

I confirm removing `magit-repos` from `evil-collection--supported-modes` fix this issue.

**Comment by condy0919** [comment]
Installed. Thanks for the excellent work @swinkels :rocket:
