### ISSUE TITLE
help with corofu bindings

### ISSUE THREAD

**Issue by JonatanSahar** [emacs-evil/evil-collection#641]
Hi! I was referred here by @minad, he though maybe you could help :)

I have ` C-j `and `C-k` bound in `corfu-map` to move up and down the candidate list. I also have the same binding in insert mode to move between lines. When I try to move between candidates in the completion popup I get the wrong functionality… I expected the binding in the popup to override the one in the buffer.

I have this in my config, but it doesn’t seem to do the job:

```
(advice-add 'corfu--setup :after 'evil-normalize-keymaps)
(advice-add 'corfu--teardown :after 'evil-normalize-keymaps)
(evil-make-overriding-map corfu-map)
```

Any ideas would be appreciated :)

**Comment by jojojames** [comment]
Are you using evil-collection? That works for me already.

**Comment by jojojames** [comment]
Bound here: https://github.com/emacs-evil/evil-collection/blob/e1bbf13194e06c435cd3328b2b431c9c46fbbf40/modes/corfu/evil-collection-corfu.el#L81

**Comment by jojojames** [comment]
If you do start using it, I recommend removing the overriding maps in your config, e.g. remove this:

```
(advice-add 'corfu--setup :after 'evil-normalize-keymaps)
(advice-add 'corfu--teardown :after 'evil-normalize-keymaps)
(evil-make-overriding-map corfu-map)
```

**Comment by JonatanSahar** [comment]
I haven't updated my packages in a little while, so I don't have that function in evil-collection.
I'm on Doom emacs, and I gather evil-collection is preconfigured to some extent. I'll upgrade and try it. 
Is it supposed to behave like I expect it to with regards to my own bindings in insert mode?
