### ISSUE TITLE
hide cursor in vundo

### ISSUE THREAD

**Issue by Dickby** [emacs-evil/evil-collection#648]
vundo by default hides the cursor in the vundo-tree buffer. 
evil-mode prevents that somehow. Is there a way to avoid this?
Thanks

**Comment by condy0919** [comment]
Agreed.

The red dot has already indicated the cursor position.

**Comment by jojojames** [comment]
Added feature request here https://github.com/emacs-evil/evil-collection/issues/642

Feel free to PR.
