### ISSUE TITLE
Feature Request: Website 

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#658]
Hi,

What do you think of having an html website that renders all the keybindings in tables [README.org](https://github.com/emacs-evil/evil-collection/pull/657) nicely?

I was thinking like what spacemacs has for their layers:

https://develop.spacemacs.org/doc/QUICK_START.html#describe-functions

https://develop.spacemacs.org/layers/+lang/python/README.html

**Comment by condy0919** [comment]
`M-x evil-collection-describe-bindings`

**Comment by jgarte** [comment]
Thanks for sharing that command. I'll definitely be using it. I still think it would be cool to have a website though the way spacemacs does for their layers. I imagine we could do this with org-mode? Is the main reason to not have a website extra maintenance costs?

**Comment by jgarte** [comment]
I tried `evil-collection-describe-bindings` but it doesn't show `smerge` bindings for me and I'm in smerge mode currently.

**Comment by jojojames** [comment]
It's not a bad idea but maintenance seems tricky unless we can get auto-generation of keybindings going.

**Comment by jgarte** [comment]
> unless we can get auto-generation of keybindings going.

Let's think about how to do that.

Do any other emacs libraries auto-generate keybinding into tables via org-mode or something else?

**Comment by jojojames** [comment]
There seems to not be enough interest here, think we can close this for now. If you have other ideas, feel free to reopen.
