### ISSUE TITLE
evil-collection-vterm.elc failed to provide feature ‘evil-collection-vterm’

### ISSUE THREAD

**Issue by XushanLu** [emacs-evil/evil-collection#674]
I am running into this problem after I updated all the packages in Spacemacs when trying to open a vterm buffer.:

`evil-collection-require: Loading file /home/xsl/.emacs.d/elpa/28.1/develop/evil-collection-20220810.1901/modes/vterm/evil-collection-vterm.elc failed to provide feature ‘evil-collection-vterm’`

This is the only message I could find. I don't really know whether the problem is caused by evil-collection or other packages. I simply do not have the knowledge to figure this out. I'd still like to be able to use vterm.

I will post any other information that might be useful. Please comment.

**Comment by condy0919** [comment]
<kbd>C-x C-f</kbd> the .elc file, the last line of that file should be

``` emacs-lisp
(provide 'evil-collection-vterm)
```

If not, `(byte-compile-file "/path/to/evil-collection-vterm.el")` in `*scratch*` buffer.

PS: you can delete the .elc file to get around the issue temporarily.

**Comment by Technius** [comment]
I ran into the same issue. The `.elc` file on my computer was missing all of the function definitions. I deleted the `.elc` file and ran `byte-compile-file` as suggested above to recreate the `.elc` file, and then that fixed it for me.

**Comment by alexshagov** [comment]
The same issue here,
Had to remove `.elc` file

**Comment by jojojames** [comment]
Not really sure here, I think we need a minimal reproduction before we can move further. If it's worth anything, I tried vterm on my setup and it works for meTM.

Feel free to reopen with a repro.
