### ISSUE TITLE
error setting key in magit-status-mode-map: gpu, gpp

### ISSUE THREAD

**Issue by webframp** [emacs-evil/evil-collection#680]
Anyone else encountered this?

```
evil-collection: error setting key in magit-status-mode-map (error "Key sequence g p u starts with non-prefix key g p")
evil-collection: error setting key in magit-status-mode-map (error "Key sequence g p p starts with non-prefix key g p")
```

Using emacs 28.2, doom emacs configuration. Can ask over there it's more doom config specific

**Comment by condy0919** [comment]
A minimal reproducible recipe? See the FAQ section of the README.

**Comment by jojojames** [comment]
Think it means you have keys already bound to gp which magit tries to set.
