### ISSUE TITLE
Improve pdf-selection behavior

### ISSUE THREAD

**Issue by dalanicolai** [emacs-evil/evil-collection#683]
I would like to notify you about some small improvement regarding selection in pdf-tools (see here https://github.com/vedang/pdf-tools/issues/137).

In summary: please add the 'mouse bindings' for the 'pdf-view-mode-map' 'normal-state' also to its 'visual-state' map (see https://github.com/syl20bnr/spacemacs/pull/15762/files).

Thanks!

**Comment by condy0919** [comment]
Thanks

**Comment by condy0919** [comment]
repost link https://github.com/syl20bnr/spacemacs/pull/15762

**Comment by jojojames** [comment]
@dalanicolai Looking at the links in this thread, it seems you would be the most appropriate person to add those bindings. I am not sure exactly which bindings you'd prefer on which keys. 

PR will definitely be appreciated here, thanks for the investigation.
