### ISSUE TITLE
Make overwriting of image-dired commands easier

### ISSUE THREAD

**Issue by ghosty141** [emacs-evil/evil-collection#684]
https://github.com/emacs-evil/evil-collection/blob/master/modes/dired/evil-collection-dired.el#L175

Is there a reason why this doesn't use a keymap with prefix C-t ? The current implementation really gets in the way if you want to rebind C-t to something else since you have to unbind all of the other C-t bindings.

**Comment by jojojames** [comment]
PR welcome.
