### ISSUE TITLE
Julia-mode & MATLAB support

### ISSUE THREAD

**Issue by aminevsaziz** [emacs-evil/evil-collection#688]
Is there any support for [julia-mode](https://github.com/JuliaEditorSupport/julia-emacs) or  [matlab-mode](https://sourceforge.net/projects/matlab-emacs/)? These two modes are recommended in academia especially Julia. If there any intention to support it or even port some of python binding to them as they are close enough.

**Comment by condy0919** [comment]
Welcome to raise a PR!

**Comment by aminevsaziz** [comment]
> Welcome to raise a PR!

That's good news. I will start working on it tomorrow. Any help would be great.

**Comment by jojojames** [comment]
Sounds good, as @condy0919 mentioned, feel free to PR.

In the future, can also add requests here: https://github.com/emacs-evil/evil-collection/issues/642

Thanks!
