### ISSUE TITLE
evil-collection-vterm-delete-char does not delete a character

### ISSUE THREAD

**Issue by ChoppinBlockParty** [emacs-evil/evil-collection#700]
For some reasons `evil-collection-vterm-delete-char` is not working for me in vterm-mode. Does anyone else have the same problem? I can see that the key is bound correctly but a character does not get deleted. Interestingly, `evil-collection-vterm-delete-backward-char` does work correctly. Yeah, all other modifiers work correctly, only this is flawed.

**Comment by jojojames** [comment]
Those keys work for me. Please feel free to re-open if you have an emacs -Q repro.
