### ISSUE TITLE
Upload to melpa stable

### ISSUE THREAD

**Issue by pmiddend** [emacs-evil/evil-collection#71]
Is it possible to upload evil-collection to melpa stable?

**Comment by jojojames** [comment]
I'm open to this but I'm unfamiliar with the melpa-stable process [1].

I'm also not sure how the dependencies will track (given I don't know [1]), which evil is evil-collection going to point at as a dependency, etc.

The other thing is evil-collection will expect a certain version of evil to be used at this point (the one where you can disable evil-integration). See https://github.com/jojojames/evil-collection/pull/66

If anyone has more info, feel free to chime in. I'll do some research on this at some point and get back to you.

**Comment by dieggsy** [comment]
AFAIK, melpa-stable just requires you creating a "release" in the form of a github tag. Stable releases then track github tags, not whatever the latest commit is. So to be extra redundant, you'd only create github tags when you consider that particular ref stable.

Er, not sure what this means in terms of which versions of dependencies to require, but if the melpa stable versions of its dependencies are sufficient for evil-collection, it might be a good idea to declare those instead anyway (or you might _need_ to to get on melpa stable, or melpa stable might take care of this itself? unsure) - then everything would just fall into place.

On the other hand, if the stable dependencies are _not_ sufficient, I'm really not sure what happens then. Sorta thinking aloud here, I suppose.

**Comment by jojojames** [comment]
We could probably do this at some point but the integration -> other packages will be spotty. I think we're mostly tracking the latest packages with some minor compatibility code.

**Comment by Ambrevar** [comment]
I'm not following `stable`, so do you have examples of problematic packages?

**Comment by jojojames** [comment]
Are you asking what 'stable' means in this case?

evil-collection has to track either the head (e.g. melpa) of a package or the 'stable' (e.g. melpa-stable) of that same package. There can be compatibility differences.

**Comment by Ambrevar** [comment]
I meant do you have examples of specific packages with compatibility differences?
Maybe we should just go ahead and wait for user feedback, if any.

**Comment by jojojames** [comment]
> I meant do you have examples of specific packages with compatibility differences?

I don't use stable- packages so don't really want to spend time looking for specific examples. But we can just think of a simple use case of binding a command to a new function in [insert 3rd party package] that is part of that package's upstream but [not yet melpa-stable]. Would it be reasonable to release this [evil-collection] as a 'stable' release? *Dunno*, the experience can be kind of shoddy..

> Maybe we should just go ahead and wait for user feedback, if any.

I'm not against doing it but there has to be some value in the word 'stable' if we're going to do it.

At this point, the only feasible route seems to be evil-collection binding to 3rd party upstream packages and releasing that as a stable release which doesn't seem to be much value-add to just plain-old melpa other than for package vendoring purposes.

**Comment by Ambrevar** [comment]
I think you are right: unless someone wants to dedicate some time to
guarantee the "stable" value of the package, there is no point in doing it.

I suggest we leave this open in case someone would like to volunteer! :)

**Comment by jojojames** [comment]
https://stable.melpa.org/#/evil-collection

I will periodically update the stable branch (not too often!) as we go or if there are any breaking changes.

**Comment by Ambrevar** [comment]
Also note that I'm maintaining this package for Guix, which I update once every few month.  This makes it somewhat "stable" I suppose.

Should we agree on specific versions?  Otherwise I'll refer to MELPA stable to update the Guix package from now on.

**Comment by jojojames** [comment]
Did you have a process in mind? I don't know much about guix so I'm ok with whatever is most convenient for ya.

**Comment by Ambrevar** [comment]
No, I can't think of anything that'd suit evil collection except declaring a release stable once in a while if there has not been any drastic changes in a while.
