### ISSUE TITLE
geiser: lispy bug (evil-collection-lispy, special-lispy-eval)

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#712]
When trying to evaluate chez code with `e` in insert mode I get the following error:

```
lispy--eval-scheme: Symbol’s function definition is void: geiser-racket--language [4 times]
```

This is a very long standing bug for me that I am finally trying to report here.

I'm not sure why it is saying that that function is `void`. I'm not using racket at all.

See discussion here as well:

https://github.com/abo-abo/lispy/issues/640

and here:

https://github.com/abo-abo/lispy/issues/542

Notes on my Setup:

I have the evil-collection lispy and geiser modules enabled.

I'm using Emacs `30.0.50`.

Emacs related config:

```lisp
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init
   (list 'corfu 'dired 'dired-sidebar 'ediff 'eglot 'eldoc 'elisp-mode
         'flymake 'geiser 'xref 'vc-dir 'sly 'grep 'help 'info 'lispy 'eshell 'man
         'minibuffer 'org 'guix 'realgud 'scheme 'tetris 'vterm)))

;;
(require 'geiser-guile)
(require 'geiser-chez)
(add-to-list 'geiser-guile-load-path "~/code/guix")

;;;###autoload (defvar geiser-active-implementations ())
;;;###autoload (defvar geiser-implementations-alist ())
;;;###autoload
(defsubst geiser-impl--add-to-alist (kind what impl &optional append)
  (add-to-list 'geiser-implementations-alist (list (list kind what) impl) append))

```

**Comment by jgarte** [comment]
Two interesting observations I just made:



This works:

[(lispy-define-key map "E" 'lispy-eval-and-insert)](https://github.com/emacs-evil/evil-collection/blob/master/modes/lispy/evil-collection-lispy.el#L517)

This does not:

[(lispy-define-key map "e" 'lispy-eval)](https://github.com/emacs-evil/evil-collection/blob/master/modes/lispy/evil-collection-lispy.el#L516)

**Comment by jojojames** [comment]
Probably too late but might be better to toggle-debug-on-error to see where it's coming from.
