### ISSUE TITLE
elpaca: notes

### ISSUE THREAD

**Issue by progfolio** [emacs-evil/evil-collection#715]
Thanks again for adding this.
This was on my TODO list, but I didn't have time to get around to it.
A couple notes I have after using it:

```emacs-lisp
  (let ((elpaca-visit-fn (if (fboundp 'elpaca-ui-visit)
                             'elpaca-ui-visit
                           'elpaca-visit)))
    (if evil-collection-elpaca-want-v
        (evil-collection-define-key 'normal 'elpaca-ui-mode-map
          (kbd "gv") elpaca-visit-fn
          (kbd "gd") elpaca-visit-fn)
      (evil-collection-define-key 'normal 'elpaca-ui-mode-map
        (kbd "v") elpaca-visit-fn)))
```

I think it's safe to drop the compatibility code, stick with elpaca-ui-visit, and encourage users to update Elpaca (which is still advertising a version of 0.0.0, so some changes like this can be expected).

In addition to "gv" and "gd", it might be nice to have a mnemonic binding which visits the build directory for a package ("gb"?) without applying a prefix-arg to the other visit bindings. e.g.

```emacs-lisp
(defun evil-collection-elpaca-ui-visit-build-dir ()
  "Visit package's build-dir"
  (interactive)
  (elpaca-ui-visit 'build))
```

As of https://github.com/progfolio/elpaca/commit/b837e2103fb274b44d2187eac68aca0b72387a27 elpaca-defsearch is a macro. The current definitions will still work (it will just generate commands with quotes in the names. e.g. elpaca-ui-search-\'installed)

https://github.com/progfolio/elpaca/commit/cfa7ea4d81465c7c62e67a17ebbaa3a16da71e67 adds a feature which limits row display for large elpaca-ui-mode tables. By default, the command to show hidden rows is bound to "+". 

```emacs-lisp
        ;; The original is on t but T is also a movement key as well as a
        ;; key bound to a filter. S is still an open key though and
        ;; matches [S]tatus.
        ;; t -> S
        (kbd "S") 'elpaca-status)
````

I avoided "S" because it is bound to `tabulated-list-sort` by default. It will sort by the current column.
Up to you, but it may be worth moving the status binding to another key.

**Comment by jojojames** [comment]
> I think it's safe to drop the compatibility code, stick with elpaca-ui-visit, and encourage users to update Elpaca (which is still advertising a version of 0.0.0, so some changes like this can be expected).

Sounds good, done.

>  In addition to "gv" and "gd", it might be nice to have a mnemonic binding which visits the build directory for a package ("gb"?) without applying a prefix-arg to the other visit bindings. e.g.

That seems good too. Do you think this will only be bound in evil-collection?

> As of https://github.com/progfolio/elpaca/commit/b837e2103fb274b44d2187eac68aca0b72387a27 elpaca-defsearch is a macro. The current definitions will still work (it will just generate commands with quotes in the names. e.g. elpaca-ui-search-'installed)

> https://github.com/progfolio/elpaca/commit/cfa7ea4d81465c7c62e67a17ebbaa3a16da71e67 adds a feature which limits row display for large elpaca-ui-mode tables. By default, the command to show hidden rows is bound to "+".

Suggestions?

> I avoided "S" because it is bound to tabulated-list-sort by default. It will sort by the current column.
Up to you, but it may be worth moving the status binding to another key.

Same, any suggestion? Don't mind it going to something like 'gs' even.

**Comment by progfolio** [comment]
> That seems good too. Do you think this will only be bound in evil-collection?

I think so. I'd say most people using Emacs bindings are comfortable with a `C-u v` to get the same behavior.
For vim bindings "gb" feels better to me than adding a prefix arg (e.g. 9 gd which will do the same now).


> Suggestions?

For elpaca-defsearch, you can unquote the args:

```emacs-lisp
(elpaca-defsearch 'name "query") ;;old
(elpaca-defsearch name "query") ;;new
```

That will require updating to the version of Elpaca listed above, but it'll work after that.

For the `elpaca-ui-show-hidden-rows` binding, I'm not sure. I know "+" is usually a movement key in vim.
I don't think it's a particularly useful movement in tabulated-list-mode buffers, though. The lines tend to be formatted so everything is aligned, making "+" about as useful as "j". If not "+", maybe binding somewhere on the "z" prefix (One could loosely think of showing more rows as opening a fold, though it's not a perfect analogy).

**Comment by jojojames** [comment]
> For vim bindings "gb" feels better to me than adding a prefix arg (e.g. 9 gd which will do the same now).

Cool, done.

> For elpaca-defsearch, you can unquote the args:

I believe we need to copy the macro to evil-collection too since these are compile time requirements now. Like below:

```(defmacro evil-collection-elpaca-defsearch (name query)
  "Return search command with NAME for QUERY."
  (declare (indent 1) (debug t))
  `(defun ,(intern (format "elpaca-ui-search-%s" name)) ()
     ,(format "Search for %S" query)
     (interactive)
     (elpaca-ui-search ,query)))
```

> For the elpaca-ui-show-hidden-rows binding, I'm not sure. I know "+" is usually a movement key in vim.

Added to + & =.

> For elpaca-status, "gs", "gS" (to keep consistent with the other search views) or both bindings sounds good to me.

Changed.

**Comment by progfolio** [comment]
Just tried it out. Works great. Thanks again.
