### ISSUE TITLE
Update `evil-collection-consult--mark-candidates`

### ISSUE THREAD

**Issue by Aankhen** [emacs-evil/evil-collection#739]
`consult--line-with-cursor` was recently replaced with `consult--line-with-mark`: minad/consult@8f1bea3e3634abc92d98084afb5cc98d2a8dc9ee

Changing this:

https://github.com/emacs-evil/evil-collection/blob/1f34f5ec4ee8e7945ecd1f885f18789526a905ee/modes/consult/evil-collection-consult.el#L90

To use `consult--line-with-mark` instead seems to make it work.

**Comment by condy0919** [comment]
It should be fixed with https://github.com/emacs-evil/evil-collection/commit/286d69de179cf70c00963a998a4beb826b51414a
