### ISSUE TITLE
Weird behavior with eglot

### ISSUE THREAD

**Issue by Mango0x45** [emacs-evil/evil-collection#744]
When using `evil-collection` in conjunction with `eglot`, if I try to view all references with `gr` (which should call `xref-find-references`) I get:

    g r is undefined

That is especially weird because when I do `describe-variable` on `eglot-mode-map` I see:

```
Value
…
<normal-state> g r xref-find-references
…
```

And yes, I am in normal mode.

Turns out after some playing around that `g r` only works if I first press `ESC` to “go into normal-mode” (despite _already being in normal-mode_).

I am totally lost as to why this is happening. Anyone have any ideas?

**EDIT**: Same thing happens with `g 5`

**Comment by sevillaarvin** [comment]
> Turns out after some playing around that `g r` only works if I first press `ESC` to “go into normal-mode” (despite _already being in normal-mode_).

Very nice, thanks for the tip.

**Comment by jojojames** [comment]
Might have something to do with normalizing the keymaps, I added something for this. Not sure if it'll fix it though.
