### ISSUE TITLE
[Request] sqlite-mode (Emacs 29)

### ISSUE THREAD

**Issue by garrett-hopper** [emacs-evil/evil-collection#749]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Database.html

```
    sqlite-mode-delete
    sqlite-mode-list-columns
    sqlite-mode-list-tables
    sqlite-mode-list-data
```

Also see [xenodium/sqlite-mode-extras.el](https://github.com/xenodium/dotsies/blob/main/emacs/ar/sqlite-mode-extras.el)

**Comment by jojojames** [comment]
https://github.com/emacs-evil/evil-collection/issues/642
