### ISSUE TITLE
Evil Collection triggers loading of `pdf-tools` twice

### ISSUE THREAD

**Issue by SPFabGerman** [emacs-evil/evil-collection#752]
I noticed a small bug when using [`pdf-tools`](https://github.com/vedang/pdf-tools) in combination with `evil-collection`.
Using the following code in my init file (with `pdf-tools` already installed):
```emacs-lisp
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

(pdf-loader-install)
(with-eval-after-load 'pdf-view
    (message "LOADED pdf-view!"))
(with-eval-after-load 'pdf-tools
    (message "LOADED pdf-tools!")
    ;; (debug)
    )
```

I can see in the message buffer, that the `pdf-tools` code is loaded twice:
```
LOADED pdf-tools!
LOADED pdf-view!
LOADED pdf-tools!
```

Using the debugger I figured out that the first (unintended) load happens when loading `pdf-view` and seems to be caused by `evil-collection-require`:
![Screenshot-2023-09-03-20:29:03](https://github.com/emacs-evil/evil-collection/assets/42518661/0fb1ff6f-c160-4408-b3ae-1b4ffabd110d)

Here is also the debugger of the second (intended) load:
![Screenshot-2023-09-03-20:29:24](https://github.com/emacs-evil/evil-collection/assets/42518661/2bc7793e-6bb9-4577-b5fa-e72ea656059b)

Removing the `evil-collection` code from my init file fixes this bug and the `pdf-tools` code is only loaded once, after `pdf-view`:
```
LOADED pdf-view!
LOADED pdf-tools!
```

**Comment by jojojames** [comment]
Seems right but not much I will do here since I don't use this tool, PR appreciated if there's a reasonable fix.
