### ISSUE TITLE
[Q] How do I add a new hotkey?

### ISSUE THREAD

**Issue by NightMachinery** [emacs-evil/evil-collection#754]
I want to add this hotkey:
```
(after! magit
    (map!
     :map magit-mode-map
     :nvo
     "g y" #'night/avy-copy-from-char-to-char)
    )
```

but it seems to get overridden (sometimes?). Evaling it again after opening the first magit buffer works.

Is there some best practice for adding hotkeys?

**Comment by jojojames** [comment]
Might be something in your setting overwriting it in this case. Emacs Q recipe if you can reproduce.

Doc should be sufficient for how to set up keys!
