### ISSUE TITLE
evil-collection-corfu-quit-and-escape not working as expected

### ISSUE THREAD

**Issue by NAHTAIV3L** [emacs-evil/evil-collection#761]
When using C-g with corfu completion it deletes whatever was previewed in the buffer, but this does not happen when using evil-collection-corfu-quit-and-escape. 

evil-collection-corfu-quit-and-escape works when you dont try to scroll through the results, but if you scroll through the results then it doesn't remove the preview.

**Comment by jojojames** [comment]
The behavior you describe is as expected. You can rebind ESC to match C-g as desired.
