### ISSUE TITLE
`evil-collection-calendar` not woking in `org-roam-dailies-goto-date`

### ISSUE THREAD

**Issue by archcst** [emacs-evil/evil-collection#772]
Hi there,

Thanks for providing very handy keybingings in `calendar` with `evil-collection-calendar`! But when it comes to calender with `org-roam-dailies-goto-date` it seems not working, is there a way to enable it in org-roam dailies' calendar?

**Comment by condy0919** [comment]
What would you expected? And what's the current situation. Please elaborate more
