### ISSUE TITLE
preserve gg and G motion commands in dired

### ISSUE THREAD

**Issue by timcharper** [emacs-evil/evil-collection#773]
I found it rather surprising that 'gg' and 'G' don't work to navigate a dired buffer in normal mode, while other motion keys do work.

I think perhaps the change-mode commands should be behind a prefix key?

https://github.com/emacs-evil/evil-collection/blob/8c84f9bc89fe56e71b56519f886085ddcbc671cf/modes/dired/evil-collection-dired.el#L58

**Comment by jojojames** [comment]
For some reason, it works for me. Will take a PR to swap that binding.

**Comment by timcharper** [comment]
Interesting! I'll try and reproduce with more vanilla configuration. Could be an interaction with something else I have installed.

**Comment by jsntn** [comment]
> Interesting! I'll try and reproduce with more vanilla configuration. Could be an interaction with something else I have installed.

Hello, I encountered the same that - both 'gg' and 'G' don't work to navigate a dired buffer in normal mode, while other motion keys do work.

Could you please kindly share how you fixed this finally?
