### ISSUE TITLE
elpaca bindings changed

### ISSUE THREAD

**Issue by progfolio** [emacs-evil/evil-collection#774]
Just an FYI that I've changed quite a few of Elpaca's UI mode bindings. This actually makes evil compatibility a little easier (I've just switched over to using make-intercept-map for elpaca-ui-mode-map and it works how I like it) and should necessitate less work on evil-collection's side.

See: progfolio/elpaca@33cbe81fde

**Comment by jojojames** [comment]
Thanks, tweaked evil-collection accordingly!
