### ISSUE TITLE
CIDER: Use conditionaly use `xref-find-definitions` in the goto definitions keybind 

### ISSUE THREAD

**Issue by toniz4** [emacs-evil/evil-collection#776]
Starting in at version 1.2.0, CIDER's main method of finding definitions is using the builtin emacs `xref-find-definitions`, unless the variable `cider-use-xref` is nil, the default being `t`.

It would be nice if we could mirror this functionality in evil collection.  

https://github.com/emacs-evil/evil-collection/blob/29212d123f1d2622332c02ca55b3a81faee1af76/modes/cider/evil-collection-cider.el#L135

If it's something you wish to add, I will be happy to make a PR.

**Comment by condy0919** [comment]
PR welcome.
