### ISSUE TITLE
vterm does not start with evil colection

### ISSUE THREAD

**Issue by attamhb** [emacs-evil/evil-collection#779]
I am unable to start vterm, while using evil-mode in emacs. 

I get the following message! 

`evil-collection-require: Loading file /home/atta/.config/emacs/elpa/evil-collection-20240205.144/modes/vterm/evil-collection-vterm.elc failed to provide feature ‘evil-collection-vterm’
`
Any help would be greatly appreciated!

**Comment by Stebalien** [comment]
Try running `M-x package-recompile RET evil-collection RET`.

**Comment by attamhb** [comment]
Thanks for the reply! A couple of day ago, I switched from package.el to straight.el for all the packages in my emacs configuration. vterm is working now.
