### ISSUE TITLE
`mu4e-compose-goto-top` and `mu4e-compose-goto-bottom` have been removed from `mu4e`

### ISSUE THREAD

**Issue by LemonBreezes** [emacs-evil/evil-collection#781]
Hello. These commands `mu4e-compose-goto-top` and `mu4e-compose-goto-bottom` have been removed in the latest release of `mu4e` but are still referenced by the package.

Also referencing a Doom Emacs PR re-adding these functions: https://github.com/doomemacs/doomemacs/pull/7696.

**Comment by condy0919** [comment]
PR welcome.. I'm not using mu4e for a long time.
