### ISSUE TITLE
Create new tag.

### ISSUE THREAD

**Issue by apoorv569** [emacs-evil/evil-collection#786]
Please create a new `release/tag` as the last tag `0.0.9` is from a year ago.

Distributions like `GNU Guix` use `tag/version` for updating packages and because its now outdated on `GNU Guix`, `corfu` is starting to cause problems with `evil-mode`,

```
Error running timer ‘corfu--auto-complete-deferred’: (wrong-number-of-arguments #<subr evil-normalize-keymaps> 4)
```

As far as I can tell, these lines have been updated,
https://github.com/emacs-evil/evil-collection/blob/d0518fc1626f09a341d4b5a98c857087abfb1b0c/modes/corfu/evil-collection-corfu.el#L131

But because of the tag, `GNU Guix` still doesn't have this update.

**Comment by condy0919** [comment]
Ya, see the 0.0.10 version

**Comment by apoorv569** [comment]
> Ya, see the 0.0.10 version

Nice. I sent a patch to Guix as well.
