### ISSUE TITLE
mu4e: Wrong type argument: commandp, 'mu4e-compose-goto-bottom with visual mode

### ISSUE THREAD

**Issue by larrasket** [emacs-evil/evil-collection#788]
When hitting G with visual mode, I get Wrong type argument: commandp, 'mu4e-compose-goto-bottom

although it works fine in normal mode. Same case with mu4e-compose-goto-top

My version is on the latest commit of evil-collection: https://github.com/emacs-evil/evil-collection/commit/fe96b412f437f263f99492fe293499016b816a78

**Comment by larrasket** [comment]
mu4e version: 1.12.1

**Comment by condy0919** [comment]
@LemonBreezes thoughts?

**Comment by LemonBreezes** [comment]
> @LemonBreezes thoughts?

Caused by https://github.com/LemonBreezes/evil-collection/commit/3983b6b520f7066bf5c3c6787ec4609024edf33a. I have opened a PR fix in #790.
