### ISSUE TITLE
Keep visual selection when using evil-collection-unimpaired-move-text-*

### ISSUE THREAD

**Issue by jabuxas** [emacs-evil/evil-collection#809]
Wonder if there is a way to keep the visual selection when using evil-collection-unimpaired-move-text-{up,down}, a really handy vim shortcut I had was `:m '>+1<CR>gv=gv` which is kind of mimicked by this function except it only moves the text and it doesnt really keep the selection, I could throw in a number of times to repeat before the function but I feel it would be easier to do it repeatedly.

Thanks

**Comment by jojojames** [comment]
Selection is kept for me so I'm assuming there's an issue elsewhere.
