### ISSUE TITLE
`d` in diff-mode + visual selection does not kill text

### ISSUE THREAD

**Issue by Hi-Angel** [emacs-evil/evil-collection#810]
Before trying to send a PR to fix that I decided to create this issue to discuss.

The problem case: I was editing a diff file. I have selected a large part of the diff that covers multiple files and pressed <kbd>d</kbd> to remove it. Then I saved and applied it. Now, can you imaging my surprise when I found that literally nothing has changed. The files I removed were still there, in git. Upon closer inspection turns out that `evil-collection` [has bound this key to some mode-specific action `diff-hunk-kill`](https://github.com/emacs-evil/evil-collection/blob/5886bab852dc9e31959e70384d535473e44504ad/modes/diff-mode/evil-collection-diff-mode.el#L125)

I see 2 problems with that:

1.That seems to kind of beat the purpose of the plugin because from my understanding the plugin is trying to help with various annoying modes that override common Evil keybindings. But in this case it is the plugin that overrides it.
2. Even setting `1` aside, why <kbd>d</kbd> in visual mode? It is more confusing than it is helpful, because visual mode implies you've selected some region and so `diff-hunk-kill` should do the action over the region. Which `diff-hunk-kill` does not support.

Should the hotkey perhaps be removed?

**Comment by Hi-Angel** [comment]
CC: @Ambrevar the commit author

**Comment by jojojames** [comment]
Feel free to submit a PR to discuss better keybindings. What you're suggesting doesn't seem like a bad idea at an initial glance.

**Comment by Hi-Angel** [comment]
@jojojames I am confused. There was a PR that is closing this issue that has undergone multiple changes and was stuck on discussion. You closed it because it's currently not ready to merge, okay. But then, the only thing I can do here is to open a PR that simply removes the `d` keybinding from the code, because the better way which is  "only remove it for visual state but leave it for normal" just doesn't work for whatever reason. So what do I need to do here?

**Comment by jojojames** [comment]
> So what do I need to do here?

You can reopen the issue in the PR. I closed this issue because the topic of this issue is no longer relevant (e.g. can be handled in the PR)

The PR being closed can be reopened as long as there's further interest.

(I also added a change here https://github.com/emacs-evil/evil-collection/commit/22e45c6939c96b4da4cc2aba628efdfedfa887e9 that might fix (or worsen) some things for you.)

Hope you can try it out and we can go from there.

**Comment by Hi-Angel** [comment]
> (I also added a change here 22e45c6 that might fix (or worsen) some things for you.)

Thank you, in my testing it does seems to fix!

**Comment by jojojames** [comment]
got it thx
