### ISSUE TITLE
Smerge-mode bindings not being activated

### ISSUE THREAD

**Issue by Stewmath** [emacs-evil/evil-collection#818]
Smerge-mode bindings were added [several years ago](https://github.com/emacs-evil/evil-collection/pull/556) but were never added to ``evil-collection--supported-modes``, so they never get loaded. Is there a reason for this?

**Comment by cobac** [comment]
I tried just adding `smerge` (and `smerge-mode`) to `evil-collection--supported-modes`, but I couldn't get it to activate properly. I've hit the ceiling of my elisp debugging skills trying to get this to work.

It'd be nice if someone more knowledgeable can have a look 😌
