### ISSUE TITLE
Magit help menu fails to open with recent versions of transient

### ISSUE THREAD

**Issue by ItsHoff** [emacs-evil/evil-collection#831]
Steps:
1. Enable evil-collection Magit integration
2. Open magit-status
3. Press `?` to open the help menu

Result:
Transient fails with
`transient-setup: Wrong type argument: command, (keymap (76 . magit-log) (74 . magit-display-repository-buffer) (106 . magit-status-jump) (73 . magit-init) (105 . magit-gitignore) (72 . magit-describe-section) (104 . magit-info) (70 . magit-pull) (102 . magit-fetch) ...), command`

The issue does not reproduce when evil-collection integration is disabled. 
I bisected the issue and it seems to have started with https://github.com/magit/transient/commit/c356d1bca13ef1dd78ec7e83a89936cc58553f75.

**Comment by condy0919** [comment]
I'm using Emacs master (transient 0.7.4 is bundled), can't reproduce this issue.

**Comment by YasserKa** [comment]
I have it as well with `transient 0.7.4` `magit 4.0.0`

**Comment by jojojames** [comment]
I am guessing the new change doesn't like this format (\C-l) very much. e.g.

```
;; (transient-suffix-put 'magit-dispatch "L" :key "\C-l") ;; doesn't work anymore
;; (transient-suffix-put 'magit-dispatch "L" :key "^L") ;; works
```

Added a fix, seems to work for me. Thanks for isolating the issue @YasserKa and @ItsHoff 

@tarsius Heads up in case I misunderstood what the right solution is.

**Comment by tarsius** [comment]
Each key is passed through `kbd`. I.e., the key has to have the format (a "key description") accepted by `keymap-set`, not the less convenient format `define-key` used.

I don't think Transient got any more restrictive about that in recent times.

**Comment by jojojames** [comment]
Gotcha, so ^L works currently but is expected to fail in the future.

```
(key-valid-p "^L") ;; nil
(key-valid-p "\C-l") ;; nil
(key-valid-p "C-l") ;; t
(key-valid-p (kbd "C-l")) ;; nil
```

I'm not sure why the original integration uses this backslash format (e.g. \C-l) so there may be a possibility of a backwards incompatible change since this file has quite a few of these \C-* bindings.

I'll go ahead and make the singular change for now though.
