### ISSUE TITLE
vterm mode: Key sequence C-c C-z starts with non-prefix key C-c

### ISSUE THREAD

**Issue by muralikodali** [emacs-evil/evil-collection#836]
message buffer showing the following error with the key mapping related to vterm-mode binding to a function **evil-collection-vterm-toggle-send-escape**

```
evil-collection: error setting key in vterm-mode-map (error "Key sequence C-c C-z starts with non-prefix key C-c")
```

keeping C-c C-z key in block list keeps this message away from appearing in message buffer.

**Comment by jojojames** [comment]
It's likely you have a binding that conflicts with that binding.
