### ISSUE TITLE
Request: calc

### ISSUE THREAD

**Issue by Dickby** [emacs-evil/evil-collection#84]
This is a big one: evil support for the mighty calc would be nice!

**Comment by Ambrevar** [comment]
Indeed!

Unless someone takes care of it, I'll work on it as soon as I have time to invest in evil-collection's development.

**Comment by dieggsy** [comment]
Yikes, this is a very big one. I've mostly stayed away from evil bindings for calc since the current system has short and IMO fairly sensible bindings (though I guess a lot of evil-collection just re-implements bindings so). That said I have missed some things like j/k scrolling (both for the calculator and trace).

**Comment by Ambrevar** [comment]
I've just pushed an initial setup: b967945f9bbcc9d08dfdf9c0284302273b1fd2f2.

It's a very hard one though, worse than I even expected.

Calc bindings are set up on demand, so if you start calc and press `C-h m`, you'll see that nothing is correctly bound.
You need to first press a key that calls for and extension command (one of those defined in `calc-ext`), then everything will be set up properly.
It's not ideal, maybe there is a better way.

For now the main changes are `hjkl` and some yank/paste/kill commands.

**Comment by dieggsy** [comment]
@Ambrevar I think it's seriously worth considering whether it's worth re-doing all of calc's bindings at all. Most of them are fairly quick and "modal" (ish) already. Maybe an exception could be made in this case to keep it in emacs state and just add hjkl + yank/past/kill bindings, as well as bindings for the commands displaced by those bindings.

**Comment by Ambrevar** [comment]
That's basically what I did, the rest is copy-pasted.

**Comment by saheratarch** [comment]
I'm having an issue with calc. It seems that pressing backspace does not delete the previous entry. For now I'm using emacs state.

**Comment by saheratarch** [comment]
For some reason, Backspace is not working properly in calc. It runs evil-backward-char instead of deleting the previous entry. Is this intentional?

**Comment by Ambrevar** [comment]
Fixed in 
d26f7acbd9f7a32ee7dee33d098d60406eff31be.
Thanks for reporting!

**Comment by saheratarch** [comment]
Glad to be of help :)

**Comment by jojojames** [comment]
Calc could definitely still use more polish, open to more PRs here. Closing this as we do have calc now.
