### ISSUE TITLE
Vertico: setting C-u in insert mode

### ISSUE THREAD

**Issue by marczz** [emacs-evil/evil-collection#842]
In the bindings of evil-collection-vertico.el, when `evil-want-C-u-scroll` is true,  `C-u` is bound to `vertico-scroll-down` both in normal-state and insert-state. But  in evil  `evil-want-C-u-scroll`  bind  `C-u` to  `evil-scroll-up` only in motion-state and not in insert state.
So an evil user having opted to  `evil-want-C-u-scroll`  is still used to enter an universal argument with `C-u` in insert state.
And when you use the extension vertico-indexed, in the minibuffer, initially in insert state, you have to enter `<universal-argument> <index> RET` to jump to an index., so I would do `C-u 22 RET` to jump to 22nd entry.
I can add that this binding in insert state is asymmetric since `C-d`  is not bound in insert state.
I think that `C-u` should be bound to a scroll command only in normal-state. It is easy in insert-state to enter `ESC C-u` to enter normal state before scrolling.

**Comment by condy0919** [comment]
Right. Welcome to raise a PR!
