### ISSUE TITLE
eshell binding suggestions

### ISSUE THREAD

**Issue by scottgrayson** [emacs-evil/evil-collection#95]
Since eshell is read only besides the current command, could we make the editing commands operate only on the current command? (After the last prompt)

### Example 1:
1. run some command
2. enter normal mode to navigate output
3. Now, I want to enter another command

key `A` (maybe some others too)  should put me after the last prompt in instert mode

### Example 2:
1. type some multi word command
2. Now, I changed my mind and want to remove all the text

keys `cc` or `dd` should operate on the current command only. By default, eshell will say `Text is read-only` if you try this because read-only prompt is also part of the current line.

---

Let me know what you think. Will these cause conflicts? I'm a beginner with elisp, but if i get these working i'll post my code or submit a PR.

**Comment by dieggsy** [comment]
Agreed, esp. since `0` already goes only to the end of the prompt

**Comment by Ambrevar** [comment]
See this issue: https://github.com/emacs-evil/evil/issues/852

**Comment by Ambrevar** [comment]
Also note that the output is editable and some users might expect to be able to edit it.

If you want that editing commands automatically move the point to the last prompt (e.g. when on an output section), then it should be made an option.

**Comment by scottgrayson** [comment]
Here are the workarounds i'm using right now

Example 1:
I wrote this one. Feedback appreciated. It did not work for ansi-term, just eshell
```elisp
  (defun my-shell-kill-pending-command ()
    (interactive)
    (eshell-bol)
    (kill-line)
    (evil-insert 1))

  (defun my-evil-shell ()
    (evil-define-key 'normal eshell-mode-map
      "cc" 'my-shell-kill-pending-command))

  (add-hook 'eshell-mode-hook 'my-evil-shell)
```

Example 2
https://stackoverflow.com/a/46937891

**Comment by Ambrevar** [comment]
We can't define "cc" directly like this for it overrides the `c` operator.

See
```
(defvar evil-collection-delete-operators '(evil-delete
                                           evil-cp-delete
                                           evil-sp-delete
                                           lispyville-delete)
  "List of delete operators.")
```

and `evil-collection-vdiff.el`.

Your function should also handle the different cases whether the point is on the output or on the prompt.

That said, I don't think that extending all possible operators is the right approach.
Maybe a smarter way would be to define a new operator, `evil-delete-eshell`, which would behave like the original operator on the output and on the whole prompt when on the prompt.

**Comment by jojojames** [comment]
Not much to add here other than that this sounds like a good idea to support eshell better.

**Comment by jojojames** [comment]
Going to close this for now but if someone else was sufficiently motivated, we can definitely support ^.

**Comment by dakling** [comment]
Not sure if this is the right place to report this, but I just noticed that Doom Emacs supports `dd` and `cc` in eshell. The relevant parts seem to be in [https://github.com/hlissner/doom-emacs/blob/develop/modules/term/eshell/config.el](https://github.com/hlissner/doom-emacs/blob/develop/modules/term/eshell/config.el), though I haven't really looked into it too deeply.

Would it be straightforward to include this in evil-collection?

**Comment by jojojames** [comment]
@dakling PR welcome, definitely.

**Comment by dakling** [comment]
Perfect - see  #343
