### ISSUE TITLE
Symbol’s value as variable is void: pdf-outline-buffer-mode-map

### ISSUE THREAD

**Issue by maxsandova** [emacs-evil/evil-collection#97]
The file `evil-collection-pdf.el` is missing a
```lisp
(require 'pdf-tools nil t)
```
at the start. I have a very complicated init file in terms of loading order,  without that line I can't do a `pdf-tools-install` without an error.  *Thanks!*

**Comment by Ambrevar** [comment]
I've added it.

Note that `pdf-tools-install takes optional arguments which allow you to
ignore errors.

Feel free to close this if everything works.

**Comment by remigourdon** [comment]
Hi,

I upgraded to the last version but I am still having the exact same issue.
Any idea?

Thanks!

**Comment by Ambrevar** [comment]
I believe that `mark` branch should fix this.  Merge is inbound.

**Comment by Ambrevar** [comment]
Hmm... Thinking more about it, I think the issue is a bit deeper.
It comes from my new `evil-collection-inhibit-insert-state` function which takes a map as argument.
As opposed to `evil-define-key`, execution is not delayed if the map hasn't been defined yet.  So if the map does not exist (of if it has just been defvar'd), then it won't do the right thing I believe.

I think `evil-collection-inhibit-insert-state` should just be a macro call `evil-define-key` instead of `evil-define-key*`.  @jojojames, any comments?

**Comment by maxsandova** [comment]
The latest commit fixed it for me. I am going to leave this open until we hear @jojojames's reply.

**Comment by jojojames** [comment]
> I think evil-collection-inhibit-insert-state should just be a macro call evil-define-key instead of evil-define-key*. @jojojames, any comments?

I don't have anything to add other than that I don't see a problem with that.

**Comment by Ambrevar** [comment]
@maxsandova: Can you make sure that the bindings defined in evil-collection-pdf.el are working?
I can't test pdf-tools at the moment I'm afraid.

**Comment by maxsandova** [comment]
I cleared my `.emacs.d` folder leaving only my `init.el` file. My `pdf-tools` config is the following
```elisp
 (use-package pdf-tools
  :ensure t
  :magic ("%PDF" . pdf-view-mode)
  :commands pdf-tools-install
  :config (pdf-tools-install))
```
Have in mind that that part is before `evil-collection`. After `use-package` finished installing everything I ran `pdf-tools-install`, it finished compiling but still showed a lot of "errors/warnings" and the keybindings worked just fine.

**Comment by Ambrevar** [comment]
The bindings might fail when pdf-tools is initialized _after_ evil-collection.  Can you confirm?

**Comment by maxsandova** [comment]
They work fine, but the compile error is still there.

**Comment by jojojames** [comment]
I might take a look at setting up pdf-tools to see if I can fix this. Otherwise, if someone else wanted to have a go at it, go for it!

**Comment by maxsandova** [comment]
For some reasons I get the same error when running `org-ref`.

**Comment by remigourdon** [comment]
Same here with `org-ref`, although the latest commits seemed to have solved the problem with `pdf-tools`.

**Comment by jojojames** [comment]
Can you guys give the last commit a shot and see if it helps?

Not sure if I broke anything moving the function to a macro but from what I can tell.. the macroexpansion looks like what I'd expect.

**Comment by jojojames** [comment]
Can you list your config?

**Comment by maxsandova** [comment]
I cleared my `elpa` folder to have a clean install. `use-package` installed everything without problems or errors (I got a helm error `helm-lib.el:489:26:Warning: reference to free variable ‘helm-initial-frame’`, which is weird considering that I don't use helm, it may be `evil-collection`'s fault).  I ran `pdf-tools-install` and worked just right. 

I got a `evil-collection-calc-setup: Invalid function: evil-collection-inhibit-insert-state` error, i guess thats an easy fix. Then i got the same errors as @ItsHoff .

**Comment by maxsandova** [comment]
I also ge the error 
```elisp
evil-collection-info-setup: Invalid function: evil-collection-inhibit-insert-state
```

**Comment by jojojames** [comment]
I've pushed a change for this.

**Comment by maxsandova** [comment]
Thanks, it just works. I will leave this open to know if it works for @ItsHoff .

**Comment by Ambrevar** [comment]
@jojojames: I was offline for a few days, I could not follow up on this.  I think you fixed it the right way, thanks!

**Comment by ItsHoff** [comment]
I updated and I'm no longer getting the error on init. Thanks for the quick fix!

**Comment by maxsandova** [comment]
This issue is fixed, Thanks.
